;; Ren test-orakel for den indlejrede normative reference.
;; Filen må aldrig kaldes fra produktionsstien.

(load "src/constants.scm")
(load "src/source-language-catalog.scm")

(define (regular-mod x d)
  (if (< d 1)
      (error "Divisor skal være positiv" d)
      (modulo x d)))

(define (save x)
  (+ 1 (regular-mod (- x 1) M)))

(define (square x) (* x x))

(define (ceil-div a b)
  (if (or (< a 0) (< b 1))
      (error "Ugyldige argumenter til loftsdivision" a b)
      (quotient (+ a b -1) b)))

(define (wrap1 position size)
  (+ 1 (regular-mod (- position 1) size)))

(define (vref1 v i) (vector-ref v (- i 1)))
(define (vset1! v i x) (vector-set! v (- i 1) x))

(define (copy-vector v)
  (let* ((n (vector-length v))
         (out (make-vector n)))
    (let loop ((i 0))
      (if (= i n)
          out
          (begin
            (vector-set! out i (vector-ref v i))
            (loop (+ i 1)))))))

(define (vector->plain-list v)
  (let loop ((i 0) (out '()))
    (if (= i (vector-length v))
        (reverse out)
        (loop (+ i 1) (cons (vector-ref v i) out)))))

(define (list-ref1 xs i)
  (list-ref xs (- i 1)))

(define (range-inclusive first last)
  (let loop ((i first) (out '()))
    (if (> i last)
        (reverse out)
        (loop (+ i 1) (cons i out)))))

(define (take-list xs n)
  (if (= n 0)
      '()
      (cons (car xs) (take-list (cdr xs) (- n 1)))))

(define (assoc-equal key table)
  (cond
   ((null? table) #f)
   ((equal? key (caar table)) (car table))
   (else (assoc-equal key (cdr table)))))

(define (insert-stable item sorted before?)
  (cond
   ((null? sorted) (list item))
   ((before? item (car sorted)) (cons item sorted))
   (else (cons (car sorted)
               (insert-stable item (cdr sorted) before?)))))

(define (stable-sort xs before?)
  (let loop ((rest xs) (out '()))
    (if (null? rest)
        out
        (loop (cdr rest) (insert-stable (car rest) out before?)))))

(define (factorial n)
  (let loop ((i 2) (r 1))
    (if (> i n)
        r
        (loop (+ i 1) (* r i)))))

(define (falling-factorial n k)
  (let loop ((j 0) (r 1))
    (if (= j k)
        r
        (loop (+ j 1) (* r (- n j))))))

(define (remove-at1 xs index1)
  (cond
   ((null? xs) (error "Indeks uden for listen" index1))
   ((= index1 1) (cdr xs))
   (else (cons (car xs) (remove-at1 (cdr xs) (- index1 1))))))

(define (day-count day)
  (cond
   ((= day FOUNDATION-DAY) 1)
   ((> day FOUNDATION-DAY) (+ (* 2 (- day FOUNDATION-DAY)) 1))
   (else (* 2 (- FOUNDATION-DAY day)))))

;; Arbejdsmængder lagres som: handling, mål, afstand, forbindelse, retning.
(define (work-counts calculation-day target-day)
  (let* ((c (day-count calculation-day))
         (t (day-count target-day))
         (distance (+ (abs (- target-day calculation-day)) 1))
         (connection (+ c t))
         (direction (cond ((< target-day calculation-day) 1)
                          ((= target-day calculation-day) 2)
                          (else 3))))
    (vector c t distance connection direction)))

(define (counts-action c) (vref1 c 1))
(define (counts-target c) (vref1 c 2))
(define (counts-distance c) (vref1 c 3))
(define (counts-connection c) (vref1 c 4))
(define (counts-direction c) (vref1 c 5))

(define (build-stones)
  (let ((table (make-vector 46)))
    (vector-set! table 0 (vector 17 29 43 71 101))
    (let loop ((i 2))
      (if (> i 46)
          table
          (let* ((old (vector-ref table (- i 2)))
                 (w (save (+ (square (vref1 old WHEAT))
                             (* 3 (vref1 old BARLEY)) i)))
                 (b (save (+ (square (vref1 old BARLEY))
                             (* 5 (vref1 old SALT))
                             (vref1 old WHEAT))))
                 (s (save (+ (square (vref1 old SALT))
                             (* 7 (vref1 old BITTER))
                             (vref1 old BARLEY))))
                 (m (save (+ (square (vref1 old BITTER))
                             (* 11 (vref1 old RED))
                             (vref1 old SALT))))
                 (r (save (+ (square (vref1 old RED))
                             (* 13 (vref1 old WHEAT))
                             (vref1 old BITTER)))))
            (vector-set! table (- i 1) (vector w b s m r))
            (loop (+ i 1)))))))

(define STONES (build-stones))

(define HIDDEN-COEFF
  (vector
   (vector 3 4 6 8)
   (vector 5 7 10 12)
   (vector 7 10 14 16)
   (vector 9 13 18 20)
   (vector 11 16 22 24)
   (vector 13 19 26 28)
   (vector 15 22 30 32)))

(define HIDDEN-GRIND-STONE
  (vector WHEAT BARLEY SALT BITTER RED WHEAT BARLEY))

(define VISIBLE-GRINDS
  (vector
   (vector 3 5 7 11 WHEAT)
   (vector 5 7 11 13 BARLEY)
   (vector 7 11 13 17 SALT)
   (vector 11 13 17 19 BITTER)
   (vector 13 17 19 23 RED)
   (vector 17 19 23 29 WHEAT)
   (vector 19 23 29 31 BARLEY)
   (vector 23 29 31 37 SALT)
   (vector 29 31 37 41 BITTER)
   (vector 31 37 41 43 RED)
   (vector 37 41 43 47 WHEAT)))

(define (build-hidden-drops counts stones)
  (let ((hidden (make-vector 7)))
    (let loop-k ((k 1))
      (if (> k 7)
          hidden
          (let* ((coeff (vref1 HIDDEN-COEFF k))
                 (stone (vref1 stones k))
                 (x0 (+ (counts-action counts)
                        (* (vref1 coeff 1) (counts-target counts))
                        (* (vref1 coeff 2) (counts-distance counts))
                        (* (vref1 coeff 3) (counts-connection counts))
                        (* (vref1 coeff 4) (counts-direction counts))
                        (vref1 stone WHEAT)
                        (vref1 stone BARLEY)
                        (vref1 stone SALT)
                        (vref1 stone BITTER)
                        (vref1 stone RED)))
                 (x1 (save x0)))
            (let loop-g ((g 1) (x x1))
              (if (> g 7)
                  (begin
                    (vset1! hidden k x)
                    (loop-k (+ k 1)))
                  (let ((old-x x))
                    (loop-g
                     (+ g 1)
                     (save (+ (square old-x)
                              (* 3 old-x)
                              (vref1 stone (vref1 HIDDEN-GRIND-STONE g))
                              g)))))))))))

(define (timeline-ref timeline key)
  (let loop ((rest timeline))
    (cond
     ((null? rest) (error "Manglende dråbe i tidslinjen" key))
     ((= key (caar rest)) (cdar rest))
     (else (loop (cdr rest))))))

(define (timeline-put timeline key value)
  (cons (cons key value) timeline))

(define (seed-drop-timeline hidden)
  (let loop ((k 1) (timeline '()))
    (if (> k 7)
        timeline
        (loop (+ k 1)
              (timeline-put timeline (- 1 k) (vref1 hidden k))))))

(define (build-visible-drops counts stones hidden)
  (let ((visible (make-vector 46)))
    (let loop-i ((i 1) (timeline (seed-drop-timeline hidden)))
      (if (> i 46)
          visible
          (let* ((p1 (timeline-ref timeline (- i 1)))
                 (p3 (timeline-ref timeline (- i 3)))
                 (p7 (timeline-ref timeline (- i 7)))
                 (stone (vref1 stones i))
                 (x0 (save (+ (* (vref1 stone WHEAT) (counts-action counts))
                              (* (vref1 stone BARLEY) (counts-target counts))
                              (* (vref1 stone SALT) (counts-distance counts))
                              (* (vref1 stone BITTER) (counts-connection counts))
                              (* (vref1 stone RED) (counts-direction counts))
                              p1 (* 3 p3) (* 5 p7) i))))
            (let loop-g ((g 1) (x x0))
              (if (> g 11)
                  (begin
                    (vset1! visible i x)
                    (loop-i (+ i 1) (timeline-put timeline i x)))
                  (let* ((row (vref1 VISIBLE-GRINDS g))
                         (old-x x))
                    (loop-g
                     (+ g 1)
                     (save (+ (square old-x)
                              (* (vref1 row 1) old-x)
                              (* (vref1 row 2) p1)
                              (* (vref1 row 3) p3)
                              (* (vref1 row 4) p7)
                              (vref1 stone (vref1 row 5)))))))))))))

(define (permutation-unrank1 rank1 items-ascending)
  (if (or (< rank1 1) (> rank1 (factorial (length items-ascending))))
      (error "Ugyldig permutationsrang" rank1)
      (let loop ((rank0 (- rank1 1))
                 (remaining items-ascending)
                 (result '()))
        (if (null? remaining)
            (reverse result)
            (let* ((slots-left (length remaining))
                   (block (factorial (- slots-left 1)))
                   (q (if (= block 0) 0 (quotient rank0 block)))
                   (next-rank (if (= block 0) 0 (regular-mod rank0 block)))
                   (chosen (list-ref remaining q)))
              (loop next-rank
                    (remove-at1 remaining (+ q 1))
                    (cons chosen result)))))))

(define (bowl-order-from-number order-number)
  (permutation-unrank1 order-number '(1 2 3 4 5 6)))

(define (bowl-order-from-drop drop-value)
  (let ((order-number (+ (regular-mod (- drop-value 1) 720) 1)))
    (bowl-order-from-number order-number)))

(define BOWL-PRIME (vector 17 19 23 29 31 37))
(define BOWL-STIR-STONE-BY-POSITION
  (vector WHEAT BARLEY SALT BITTER RED WHEAT))

(define (initial-bowls counts)
  (let ((bowls (make-vector 6)))
    (let loop ((id 1))
      (if (> id 6)
          bowls
          (let ((s (+ (counts-action counts)
                      (* (counts-target counts) id)
                      (counts-distance counts)
                      (counts-connection counts)
                      (counts-direction counts)
                      (square (vref1 BOWL-PRIME id)))))
            (vset1! bowls id (save (+ (square s) id)))
            (loop (+ id 1)))))))

(define (order-index order bowl-id)
  (let loop ((rest order) (i 1))
    (cond
     ((null? rest) (error "Skål findes ikke i rækkefølgen" bowl-id))
     ((= (car rest) bowl-id) i)
     (else (loop (cdr rest) (+ i 1))))))

(define (apply-visible-drops-to-bowls bowls visible stones)
  (let loop-i ((i 1) (current bowls) (order-at-46 #f))
    (if (> i 46)
        (vector current order-at-46)
        (let* ((drop (vref1 visible i))
               (order (bowl-order-from-drop drop))
               (old (copy-vector current))
               (pour (make-vector 6 0))
               (first-bowl (list-ref1 order 1))
               (second-bowl (list-ref1 order 2))
               (third-bowl (list-ref1 order 3))
               (next-bowls (make-vector 6)))
          (vset1! pour 1
                  (save (+ (square drop)
                           (* (vref1 (vref1 stones i) WHEAT)
                              (vref1 old first-bowl))
                           (* 3 i))))
          (vset1! pour 2
                  (save (+ (square drop)
                           (* (vref1 (vref1 stones i) BARLEY)
                              (vref1 old second-bowl))
                           (* 5 i))))
          (vset1! pour 3
                  (save (+ (square drop)
                           (* (vref1 (vref1 stones i) SALT)
                              (vref1 old third-bowl))
                           (* 7 i))))
          (let loop-p ((position 1))
            (if (> position 6)
                (loop-i (+ i 1)
                        next-bowls
                        (if (= i 46) (append order '()) order-at-46))
                (let* ((bowl-id (list-ref1 order position))
                       (prev-id (list-ref1 order (wrap1 (- position 1) 6)))
                       (next-id (list-ref1 order (wrap1 (+ position 1) 6)))
                       (stone-kind (vref1 BOWL-STIR-STONE-BY-POSITION position))
                       (s (+ (vref1 old bowl-id)
                             (* 2 (vref1 old prev-id))
                             (* 3 (vref1 old next-id))
                             (vref1 pour position)
                             drop
                             (vref1 (vref1 stones i) stone-kind))))
                  (vset1! next-bowls bowl-id
                          (save (+ (square s)
                                   (* 5 (vref1 old prev-id) (vref1 old next-id))
                                   (* i position))))
                  (loop-p (+ position 1)))))))))

(define (post-stir12 bowls)
  (let loop-stir ((stir 1) (current bowls))
    (if (> stir 12)
        current
        (let* ((old (copy-vector current))
               (saved-bowl-sum
                (save (+ (vref1 old 1) (vref1 old 2) (vref1 old 3)
                         (vref1 old 4) (vref1 old 5) (vref1 old 6)
                         (* 149 stir))))
               (order-number (+ (regular-mod (- saved-bowl-sum 1) 720) 1))
               (order (bowl-order-from-number order-number))
               (next-bowls (make-vector 6)))
          (let loop-p ((position 1))
            (if (> position 6)
                (loop-stir (+ stir 1) next-bowls)
                (let* ((bowl-id (list-ref1 order position))
                       (prev-id (list-ref1 order (wrap1 (- position 1) 6)))
                       (next-id (list-ref1 order (wrap1 (+ position 1) 6)))
                       (s (+ (vref1 old bowl-id)
                             (* 3 (vref1 old prev-id))
                             (* 5 (vref1 old next-id))
                             saved-bowl-sum
                             stir
                             (square position))))
                  (vset1! next-bowls bowl-id
                          (save (+ (square s)
                                   (* 7 (vref1 old prev-id) (vref1 old next-id)))))
                  (loop-p (+ position 1)))))))))

;; Sauce-resultat: mærke, seks skåle, rækkefølgen ved dråbe 46.
(define (sauce calculation-day target-day)
  (let* ((counts (work-counts calculation-day target-day))
         (hidden (build-hidden-drops counts STONES))
         (visible (build-visible-drops counts STONES hidden))
         (bowls (initial-bowls counts))
         (after-drops (apply-visible-drops-to-bowls bowls visible STONES))
         (final-bowls (post-stir12 (vector-ref after-drops 0)))
         (order-at-46 (vector-ref after-drops 1)))
    (vector 'sauce final-bowls order-at-46)))

(define (sauce-bowls r) (vector-ref r 1))
(define (sauce-order-at-46 r) (vector-ref r 2))

;; Svarstrøm: mærke, første tal, retningsskridt.
(define (next-bowl-in-drop46-order sauce-result queried-bowl-id)
  (let* ((order (sauce-order-at-46 sauce-result))
         (p (order-index order queried-bowl-id)))
    (list-ref1 order (wrap1 (+ p 1) 6))))

(define (ask-bowl sauce-result queried-bowl-id seal)
  (let* ((bowls (sauce-bowls sauce-result))
         (next-id (next-bowl-in-drop46-order sauce-result queried-bowl-id))
         (first
          (save (+ (square (+ (vref1 bowls queried-bowl-id) seal 181))
                   (* 179 (vref1 bowls next-id))
                   seal)))
         (direction-number
          (save (+ (square (+ first seal 1 193))
                   (* 193 first)
                   (* 197 (vref1 bowls 6)))))
         (step (if (= (regular-mod direction-number 2) 1) 1 -1)))
    (vector 'answer-stream first step)))

(define (stream-first s) (vector-ref s 1))
(define (stream-step s) (vector-ref s 2))

(define (answer-at stream k)
  (+ 1 (regular-mod (+ (- (stream-first stream) 1)
                       (* (stream-step stream) k))
                    M)))

(define (choose-rank-short stream n)
  (if (or (< n 1) (> n M))
      (error "Ugyldig kort valgrumsstørrelse" n)
      (let ((limit (* (quotient M n) n)))
        (let loop ((k 0))
          (let ((x (answer-at stream k)))
            (if (<= x limit)
                (+ (regular-mod (- x 1) n) 1)
                (loop (+ k 1))))))))

(define (smallest-power-count base n)
  (let loop ((k 1) (space base))
    (if (>= space n)
        (vector k space)
        (loop (+ k 1) (* space base)))))

(define (choose-rank-wide stream n)
  (if (<= n M)
      (error "Det brede valg kræver et større valgrum" n)
      (let* ((kp (smallest-power-count M n))
             (k (vector-ref kp 0))
             (space (vector-ref kp 1)))
        (let loop-digits ((j 0) (wide 1) (weight 1))
          (if (= j k)
              (let ((limit (* (quotient space n) n)))
                (let loop-reject ((w wide))
                  (if (<= w limit)
                      (+ (regular-mod (- w 1) n) 1)
                      (loop-reject
                       (+ 1 (regular-mod (+ (- w 1) (stream-step stream))
                                         space))))))
              (loop-digits (+ j 1)
                           (+ wide (* (- (answer-at stream j) 1) weight))
                           (* weight M)))))))

(define (choose-rank stream n)
  (if (< n 1)
      (error "Valgrummet skal være positivt" n)
      (if (<= n M)
          (choose-rank-short stream n)
          (choose-rank-wide stream n))))

(define (unrank-distinct-indices master-count k rank1)
  (let ((maximum (falling-factorial master-count k)))
    (if (or (< rank1 1) (> rank1 maximum))
        (error "Ugyldig rang for forskellige navne" rank1)
        (let loop-position ((position 1)
                            (remaining (range-inclusive 1 master-count))
                            (r rank1)
                            (out '()))
          (if (> position k)
              (reverse out)
              (let* ((suffix-length (- k position))
                     (block (falling-factorial (- (length remaining) 1)
                                               suffix-length)))
                (let loop-candidate ((candidate-position 1)
                                     (candidate-list remaining)
                                     (rr r))
                  (if (null? candidate-list)
                      (error "Rangen kunne ikke åbnes" rank1)
                      (if (> rr block)
                          (loop-candidate (+ candidate-position 1)
                                          (cdr candidate-list)
                                          (- rr block))
                          (let ((chosen (car candidate-list)))
                            (loop-position
                             (+ position 1)
                             (remove-at1 remaining candidate-position)
                             rr
                             (cons chosen out))))))))))))

;; Ordnet familie: mærke, præcis tæller, 1-baseret åbner.
(define (make-family count-proc unrank-proc)
  (vector 'ordered-family count-proc unrank-proc))
(define (family-count family) ((vector-ref family 1)))
(define (family-unrank1 family rank1) ((vector-ref family 2) rank1))

(define (make-bounded-composition-family total slots lo hi)
  (let ((memo '()))
    (define (count rem k)
      (cond
       ((= k 0) (if (= rem 0) 1 0))
       ((or (< rem (* k lo)) (> rem (* k hi))) 0)
       (else
        (let* ((key (list rem k))
               (hit (assoc-equal key memo)))
          (if hit
              (cdr hit)
              (let loop-x ((x lo) (sum 0))
                (if (> x hi)
                    (begin
                      (set! memo (cons (cons key sum) memo))
                      sum)
                    (loop-x (+ x 1) (+ sum (count (- rem x) (- k 1)))))))))))
    (define (count-all) (count total slots))
    (define (unrank rank1)
      (let ((maximum (count-all)))
        (if (or (< rank1 1) (> rank1 maximum))
            (error "Ugyldig rang for begrænset komposition" rank1)
            (let loop-position ((position 1)
                                (rem total)
                                (r rank1)
                                (out '()))
              (if (> position slots)
                  (reverse out)
                  (let loop-x ((x lo) (rr r))
                    (if (> x hi)
                        (error "Kompositionens rang kunne ikke åbnes" rank1)
                        (let ((block (count (- rem x) (- slots position))))
                          (if (> rr block)
                              (loop-x (+ x 1) (- rr block))
                              (loop-position (+ position 1)
                                             (- rem x)
                                             rr
                                             (cons x out)))))))))))
    (make-family count-all unrank)))

;; Port-registeret er test-oraklets eneste mutable kalendercache.
(define GATE-CACHE '())
(define MIN-KNOWN-GATE-INDEX 0)
(define MAX-KNOWN-GATE-INDEX 0)

(define (reset-gates!)
  (set! GATE-CACHE (list (cons 0 FOUNDATION-DAY)))
  (set! MIN-KNOWN-GATE-INDEX 0)
  (set! MAX-KNOWN-GATE-INDEX 0))

(reset-gates!)

(define (gate-get k)
  (let loop ((rest GATE-CACHE))
    (cond
     ((null? rest) (error "Ukendt portindeks" k))
     ((= k (caar rest)) (cdar rest))
     (else (loop (cdr rest))))))

(define (gate-put! k day)
  (set! GATE-CACHE (cons (cons k day) GATE-CACHE))
  day)

(define (positive-gate-gap n)
  (let* ((r (sauce FOUNDATION-DAY (+ FOUNDATION-DAY n)))
         (stream (ask-bowl r 1 SEAL-GATE-GAP))
         (chosen (choose-rank stream 922)))
    (+ 41 chosen)))

(define (negative-gate-gap n)
  (let* ((r (sauce FOUNDATION-DAY (- FOUNDATION-DAY n)))
         (stream (ask-bowl r 1 SEAL-GATE-GAP))
         (chosen (choose-rank stream 922)))
    (+ 41 chosen)))

(define (ensure-gate-index k)
  (cond
   ((> k MAX-KNOWN-GATE-INDEX)
    (let loop ((n (+ MAX-KNOWN-GATE-INDEX 1)))
      (if (> n k)
          (gate-get k)
          (begin
            (gate-put! n (+ (gate-get (- n 1)) (positive-gate-gap n)))
            (set! MAX-KNOWN-GATE-INDEX n)
            (loop (+ n 1))))))
   ((< k MIN-KNOWN-GATE-INDEX)
    (let loop ((n (- MIN-KNOWN-GATE-INDEX 1)))
      (if (< n k)
          (gate-get k)
          (begin
            (gate-put! n (- (gate-get (+ n 1)) (negative-gate-gap (abs n))))
            (set! MIN-KNOWN-GATE-INDEX n)
            (loop (- n 1))))))
   (else (gate-get k))))

(define (ensure-gates-cover low-day high-day)
  (if (> low-day high-day)
      (error "Ugyldigt portinterval" low-day high-day)
      (begin
        (let loop-left ()
          (if (> (gate-get MIN-KNOWN-GATE-INDEX) low-day)
              (begin (ensure-gate-index (- MIN-KNOWN-GATE-INDEX 1))
                     (loop-left))
              #t))
        (let loop-right ()
          (if (< (gate-get MAX-KNOWN-GATE-INDEX) high-day)
              (begin (ensure-gate-index (+ MAX-KNOWN-GATE-INDEX 1))
                     (loop-right))
              #t)))))

(define (ensure-gates-forward-through-day day)
  (ensure-gates-cover (gate-get MIN-KNOWN-GATE-INDEX) day))

(define (ensure-gates-backward-through-day day)
  (ensure-gates-cover day (gate-get MAX-KNOWN-GATE-INDEX)))

(define (gate-index-at-or-before day)
  (ensure-gates-cover day day)
  (let loop ((lo MIN-KNOWN-GATE-INDEX) (hi MAX-KNOWN-GATE-INDEX))
    (if (= lo hi)
        lo
        (let ((mid (+ lo (quotient (+ (- hi lo) 1) 2))))
          (if (<= (gate-get mid) day)
              (loop mid hi)
              (loop lo (- mid 1)))))))

(define (gate-index-at-or-after day)
  (let ((i (gate-index-at-or-before day)))
    (if (= (gate-get i) day)
        i
        (begin (ensure-gate-index (+ i 1)) (+ i 1)))))

(define (exact-gate-index day)
  (let ((i (gate-index-at-or-before day)))
    (if (= (gate-get i) day) i #f)))

;; År: mærke, nummer, åbningsport, lukningsport, åbningsdag, lukningsdag.
(define (make-year number open-index close-index)
  (vector 'year number open-index close-index
          (gate-get open-index) (gate-get close-index)))
(define (year-number y) (vector-ref y 1))
(define (year-open-index y) (vector-ref y 2))
(define (year-close-index y) (vector-ref y 3))
(define (year-open-day y) (vector-ref y 4))
(define (year-close-day y) (vector-ref y 5))

(define (year-length open-index close-index)
  (- (gate-get close-index) (gate-get open-index)))

(define (valid-year-pair? open-index close-index)
  (let ((length (year-length open-index close-index)))
    (and (>= (- close-index open-index) MIN-GATE-GAPS-PER-YEAR)
         (>= length YEAR-MIN-DAYS)
         (<= length YEAR-MAX-DAYS))))

(define (candidate-pair-before? a b)
  (let ((la (list-ref a 2)) (lb (list-ref b 2))
        (oa (gate-get (car a))) (ob (gate-get (car b))))
    (or (< la lb) (and (= la lb) (< oa ob)))))

(define (year5000 calculation-day)
  (ensure-gates-cover (- calculation-day YEAR-MAX-DAYS)
                      (+ calculation-day YEAR-MAX-DAYS))
  (let loop-i ((i MIN-KNOWN-GATE-INDEX) (candidates '()))
    (if (>= i MAX-KNOWN-GATE-INDEX)
        (let* ((sorted (stable-sort candidates candidate-pair-before?))
               (r (sauce calculation-day calculation-day))
               (stream (ask-bowl r 1 SEAL-YEAR-5000))
               (rank (choose-rank stream (length sorted)))
               (chosen (list-ref1 sorted rank)))
          (make-year 5000 (car chosen) (cadr chosen)))
        (let loop-j ((j (+ i 1)) (acc candidates))
          (if (> j MAX-KNOWN-GATE-INDEX)
              (loop-i (+ i 1) acc)
              (let ((len (year-length i j)))
                (if (and (valid-year-pair? i j)
                         (< (gate-get i) calculation-day)
                         (<= calculation-day (gate-get j)))
                    (loop-j (+ j 1) (cons (list i j len) acc))
                    (loop-j (+ j 1) acc))))))))

(define (next-year calculation-day known-year)
  (let ((open-index (year-close-index known-year)))
    (ensure-gates-forward-through-day
     (+ (gate-get open-index) YEAR-MAX-DAYS))
    (let loop ((close-index (+ open-index 1)) (candidates '()))
      (ensure-gate-index close-index)
      (let ((len (year-length open-index close-index)))
        (if (> len YEAR-MAX-DAYS)
            (let* ((sorted
                    (stable-sort candidates
                                 (lambda (a b)
                                   (< (year-length open-index a)
                                      (year-length open-index b)))))
                   (r (sauce calculation-day (gate-get open-index)))
                   (stream (ask-bowl r 1 SEAL-NEXT-YEAR))
                   (rank (choose-rank stream (length sorted)))
                   (chosen (list-ref1 sorted rank)))
              (make-year (+ (year-number known-year) 1)
                         open-index chosen))
            (loop (+ close-index 1)
                  (if (valid-year-pair? open-index close-index)
                      (append candidates (list close-index))
                      candidates)))))))

(define (previous-year calculation-day known-year)
  (let ((close-index (year-open-index known-year)))
    (ensure-gates-backward-through-day
     (- (gate-get close-index) YEAR-MAX-DAYS))
    (let loop ((open-index (- close-index 1)) (candidates '()))
      (ensure-gate-index open-index)
      (let ((len (year-length open-index close-index)))
        (if (> len YEAR-MAX-DAYS)
            (let* ((sorted
                    (stable-sort candidates
                                 (lambda (a b)
                                   (< (year-length a close-index)
                                      (year-length b close-index)))))
                   (r (sauce calculation-day (gate-get close-index)))
                   (stream (ask-bowl r 1 SEAL-PREVIOUS-YEAR))
                   (rank (choose-rank stream (length sorted)))
                   (chosen (list-ref1 sorted rank)))
              (make-year (- (year-number known-year) 1)
                         chosen close-index))
            (loop (- open-index 1)
                  (if (valid-year-pair? open-index close-index)
                      (append candidates (list open-index))
                      candidates)))))))

(define (find-target-year calculation-day target-day)
  (let loop ((y (year5000 calculation-day)))
    (cond
     ((> target-day (year-close-day y))
      (loop (next-year calculation-day y)))
     ((<= target-day (year-open-day y))
      (loop (previous-year calculation-day y)))
     (else y))))

(define (make-cutlet-partition-family g k required-boundary)
  (let ((memo '()))
    (define (count rem slots cumulative hit-boundary)
      (cond
       ((= slots 0)
        (if (and (= rem 0) (or (not required-boundary) hit-boundary)) 1 0))
       ((< rem slots) 0)
       (else
        (let* ((key (list rem slots cumulative hit-boundary))
               (hit (assoc-equal key memo)))
          (if hit
              (cdr hit)
              (let ((max-x (- rem (- slots 1))))
                (let loop-x ((x 1) (total 0))
                  (if (> x max-x)
                      (begin
                        (set! memo (cons (cons key total) memo))
                        total)
                      (let* ((next-cumulative (+ cumulative x))
                             (next-hit
                              (or hit-boundary
                                  (and required-boundary
                                       (= next-cumulative required-boundary)))))
                        (if (and required-boundary
                                 (not hit-boundary)
                                 (> next-cumulative required-boundary))
                            (loop-x (+ x 1) total)
                            (loop-x (+ x 1)
                                    (+ total
                                       (count (- rem x)
                                              (- slots 1)
                                              next-cumulative
                                              next-hit)))))))))))))
    (define (count-all) (count g k 0 #f))
    (define (unrank rank1)
      (let ((maximum (count-all)))
        (if (or (< rank1 1) (> rank1 maximum))
            (error "Ugyldig rang for koteletdeling" rank1)
            (let loop-position ((rem g) (slots k) (cumulative 0)
                                (hit-boundary #f) (r rank1) (out '()))
              (if (= slots 0)
                  (reverse out)
                  (let ((max-x (- rem (- slots 1))))
                    (let loop-x ((x 1) (rr r))
                      (if (> x max-x)
                          (error "Koteletdelingens rang kunne ikke åbnes" rank1)
                          (let* ((next-cumulative (+ cumulative x))
                                 (next-hit
                                  (or hit-boundary
                                      (and required-boundary
                                           (= next-cumulative required-boundary)))))
                            (if (and required-boundary
                                     (not hit-boundary)
                                     (> next-cumulative required-boundary))
                                (loop-x (+ x 1) rr)
                                (let ((block
                                       (count (- rem x) (- slots 1)
                                              next-cumulative next-hit)))
                                  (if (> rr block)
                                      (loop-x (+ x 1) (- rr block))
                                      (loop-position (- rem x) (- slots 1)
                                                     next-cumulative next-hit
                                                     rr (cons x out)))))))))))))))
    (make-family count-all unrank)))

(define (choose-cutlet-count structure-sauce year)
  (let* ((gate-gaps (- (year-close-index year) (year-open-index year)))
         (candidates
          (let loop ((k MIN-CUTLETS) (out '()))
            (if (> k MAX-CUTLETS)
                (reverse out)
                (loop (+ k 1) (if (<= k gate-gaps) (cons k out) out)))))
         (stream (ask-bowl structure-sauce 2 SEAL-CUTLET-COUNT))
         (rank (choose-rank stream (length candidates))))
    (list-ref1 candidates rank)))

(define (choose-cutlet-partition calculation-day structure-sauce year cutlet-count)
  (let* ((gaps (- (year-close-index year) (year-open-index year)))
         (gate-index (exact-gate-index calculation-day))
         (required
          (if (and gate-index
                   (> gate-index (year-open-index year))
                   (< gate-index (year-close-index year)))
              (- gate-index (year-open-index year))
              #f))
         (family (make-cutlet-partition-family gaps cutlet-count required))
         (stream (ask-bowl structure-sauce 2 SEAL-CUTLET-PARTITION))
         (rank (choose-rank stream (family-count family))))
    (family-unrank1 family rank)))

(define (choose-cutlet-name-indices structure-sauce cutlet-count)
  (let* ((n (falling-factorial 17 cutlet-count))
         (stream (ask-bowl structure-sauce 5 SEAL-CUTLET-NAMES))
         (rank (choose-rank stream n)))
    (unrank-distinct-indices 17 cutlet-count rank)))

;; Kotelet: mærke, navnindeks, åbningsport, lukningsport, første dag, sidste dag.
(define (materialize-cutlets year partition name-indices)
  (let loop ((parts partition)
             (names name-indices)
             (cursor (year-open-index year))
             (out '()))
    (if (null? parts)
        (reverse out)
        (let* ((close (+ cursor (car parts)))
               (cutlet (vector 'cutlet (car names) cursor close
                               (+ (gate-get cursor) 1) (gate-get close))))
          (loop (cdr parts) (cdr names) close (cons cutlet out))))))

(define (cutlet-name-index c) (vector-ref c 1))
(define (cutlet-first-day c) (vector-ref c 4))
(define (cutlet-last-day c) (vector-ref c 5))

(define (choose-month-count structure-sauce year)
  (let* ((length (- (year-close-day year) (year-open-day year)))
         (min-months (ceil-div length MAX-MONTH-DAYS))
         (max-months (min MAX-MONTHS (quotient length MIN-MONTH-DAYS)))
         (candidates (range-inclusive min-months max-months))
         (stream (ask-bowl structure-sauce 3 SEAL-MONTH-COUNT))
         (rank (choose-rank stream (length candidates))))
    (list-ref1 candidates rank)))

(define (choose-month-lengths structure-sauce year month-count)
  (let* ((length (- (year-close-day year) (year-open-day year)))
         (family (make-bounded-composition-family
                  length month-count MIN-MONTH-DAYS MAX-MONTH-DAYS))
         (stream (ask-bowl structure-sauce 3 SEAL-MONTH-LENGTHS))
         (rank (choose-rank stream (family-count family))))
    (family-unrank1 family rank)))

(define (make-weaving-family lengths-list)
  (let* ((lengths (list->vector lengths-list))
         (m (vector-length lengths))
         (memo '()))
    (define (state-key remaining opened closed)
      (append (vector->plain-list remaining) (list opened closed)))
    (define (all-zero? remaining)
      (let loop ((j 1))
        (cond ((> j m) #t)
              ((not (= (vref1 remaining j) 0)) #f)
              (else (loop (+ j 1))))))
    (define (legal? remaining opened closed j)
      (let* ((rem (vref1 remaining j))
             (original (vref1 lengths j))
             (already-opened (< rem original))
             (will-close (= rem 1)))
        (and (> rem 0)
             (or already-opened (= j (+ opened 1)))
             (or (not will-close) (= j (+ closed 1))))))
    (define (move remaining opened closed j)
      (let* ((next (copy-vector remaining))
             (original (vref1 lengths j))
             (first? (= (vref1 next j) original))
             (next-opened (if first? j opened)))
        (vset1! next j (- (vref1 next j) 1))
        (vector next next-opened
                (if (= (vref1 next j) 0) j closed))))
    (define (count remaining opened closed)
      (if (all-zero? remaining)
          1
          (let* ((key (state-key remaining opened closed))
                 (hit (assoc-equal key memo)))
            (if hit
                (cdr hit)
                (let loop-j ((j 1) (total 0))
                  (if (> j m)
                      (begin
                        (set! memo (cons (cons key total) memo))
                        total)
                      (if (legal? remaining opened closed j)
                          (let* ((next (move remaining opened closed j))
                                 (next-rem (vector-ref next 0))
                                 (next-open (vector-ref next 1))
                                 (next-closed (vector-ref next 2)))
                            (loop-j (+ j 1)
                                    (+ total (count next-rem next-open next-closed))))
                          (loop-j (+ j 1) total))))))))
    (define (count-all)
      (count (copy-vector lengths) 0 0))
    (define (unrank rank1)
      (let ((maximum (count-all)))
        (if (or (< rank1 1) (> rank1 maximum))
            (error "Ugyldig rang for månedsvævning" rank1)
            (let loop-position ((remaining (copy-vector lengths))
                                (opened 0) (closed 0)
                                (r rank1) (out '())
                                (left (apply + lengths-list)))
              (if (= left 0)
                  (reverse out)
                  (let loop-j ((j 1) (rr r))
                    (if (> j m)
                        (error "Vævningens rang kunne ikke åbnes" rank1)
                        (if (legal? remaining opened closed j)
                            (let* ((next (move remaining opened closed j))
                                   (next-rem (vector-ref next 0))
                                   (next-open (vector-ref next 1))
                                   (next-closed (vector-ref next 2))
                                   (block (count next-rem next-open next-closed)))
                              (if (> rr block)
                                  (loop-j (+ j 1) (- rr block))
                                  (loop-position next-rem next-open next-closed
                                                 rr (cons j out) (- left 1))))
                            (loop-j (+ j 1) rr)))))))))
    (make-family count-all unrank)))

(define (choose-month-weaving structure-sauce month-lengths)
  (let* ((family (make-weaving-family month-lengths))
         (stream (ask-bowl structure-sauce 4 SEAL-MONTH-WEAVING))
         (rank (choose-rank stream (family-count family))))
    (family-unrank1 family rank)))

(define (choose-month-name-indices structure-sauce month-count)
  (let* ((n (falling-factorial 47 month-count))
         (stream (ask-bowl structure-sauce 5 SEAL-MONTH-NAMES))
         (rank (choose-rank stream n)))
    (unrank-distinct-indices 47 month-count rank)))

;; Årsstruktur: mærke, år, koteletdeling, koteletnavne, koteletter,
;; månedsantal, månedslængder, vævning og månedsnavne.
(define (build-year-structure calculation-day year)
  (let* ((first-day (+ (year-open-day year) 1))
         (r (sauce calculation-day first-day))
         (cutlet-count (choose-cutlet-count r year))
         (partition (choose-cutlet-partition calculation-day r year cutlet-count))
         (cutlet-names (choose-cutlet-name-indices r cutlet-count))
         (cutlets (materialize-cutlets year partition cutlet-names))
         (month-count (choose-month-count r year))
         (month-lengths (choose-month-lengths r year month-count))
         (weaving (choose-month-weaving r month-lengths))
         (month-names (choose-month-name-indices r month-count)))
    (vector 'year-structure year partition cutlet-names cutlets
            month-count month-lengths weaving month-names)))

(define (structure-year s) (vector-ref s 1))
(define (structure-cutlets s) (vector-ref s 4))
(define (structure-weaving s) (vector-ref s 7))
(define (structure-month-names s) (vector-ref s 8))

(define (find-cutlet-for-day cutlets target-day)
  (cond
   ((null? cutlets) (error "Ingen kotelet indeholder dagen" target-day))
   ((and (<= (cutlet-first-day (car cutlets)) target-day)
         (<= target-day (cutlet-last-day (car cutlets))))
    (car cutlets))
   (else (find-cutlet-for-day (cdr cutlets) target-day))))

(define (count-occurrences-through xs value count)
  (let loop ((rest xs) (left count) (n 0))
    (if (= left 0)
        n
        (loop (cdr rest) (- left 1)
              (if (= (car rest) value) (+ n 1) n)))))

(define (calendar-date calculation-day target-day)
  (let* ((year (find-target-year calculation-day target-day))
         (structure (build-year-structure calculation-day year))
         (cutlet (find-cutlet-for-day (structure-cutlets structure) target-day))
         (day-in-cutlet (+ (- target-day (cutlet-first-day cutlet)) 1))
         (year-offset (- target-day (+ (year-open-day year) 1)))
         (month-id (list-ref (structure-weaving structure) year-offset))
         (month-name-index (list-ref1 (structure-month-names structure) month-id))
         (day-in-month
          (count-occurrences-through (structure-weaving structure)
                                     month-id (+ year-offset 1))))
    (list (year-number year)
          (cutlet-name-by-index (cutlet-name-index cutlet))
          day-in-cutlet
          (month-name-by-index month-name-index)
          day-in-month)))
