local root=arg[1] or "."
package.path=root.."/src/?.lua;"..root.."/test/?.lua;"..package.path
local B=require("bigint")
local O=require("normative_oracle")
local function eq(a,b,label) assert(tostring(a)==tostring(b),label..": "..tostring(a).." ~= "..tostring(b)) end
assert(O.TABLETS_DAY-O.FOUNDATION_DAY==14777149)
assert(O.dayCount(O.FOUNDATION_DAY)==1)
assert(O.dayCount(O.FOUNDATION_DAY-1)==2)
assert(O.dayCount(O.FOUNDATION_DAY+1)==3)
local c=O.workCounts(O.FOUNDATION_DAY,O.FOUNDATION_DAY)
assert(c.distance==1 and c.direction==2 and c.connection==2)
eq(O.SAVE(1),"1","SAVE 1")
eq(O.SAVE(O.M),tostring(O.M),"SAVE M")
eq(O.SAVE(O.M*B.from(2)),tostring(O.M),"SAVE 2M")
eq(O.SAVE(O.M+B.from(1)),"1","SAVE M+1")
local p1=O.permutationUnrank1(1,{1,2,3,4,5,6})
local p720=O.permutationUnrank1(720,{1,2,3,4,5,6})
assert(table.concat(p1,",")=="1,2,3,4,5,6")
assert(table.concat(p720,",")=="6,5,4,3,2,1")
local fam=O.makeBoundedCompositionFamily(10,2,4,6)
eq(fam.count(),"3","kantite konpozisyon 10/2")
assert(table.concat(fam.unrank1(B.from(1)),",")=="4,6")
assert(table.concat(fam.unrank1(B.from(2)),",")=="5,5")
assert(table.concat(fam.unrank1(B.from(3)),",")=="6,4")
local names=O.unrankDistinctIndices(4,3,B.from(1))
assert(table.concat(names,",")=="1,2,3")
local wf=O.makeWeavingCounter({2,2})
eq(wf.count(),"2","kantite ti tise")
assert(table.concat(wf.unrank1(B.from(1)),",")=="1,1,2,2")
assert(table.concat(wf.unrank1(B.from(2)),",")=="1,2,1,2")
print("PASS oracle helpers")
