(module
  ;; Oráculo limpio para la salsa normativa. No contiene ninguna ruta heredada ni corrección de producción.
  ;; Los enteros guardados usan base 2^30. El módulo i64 solo es un adaptador de caso fijo;
  ;; la representación general de días de la entrega está en wide_integer.wat.
  (memory (export "memory") 8)
  (global $BASE i64 (i64.const 1073741824))
  (global $MASK i64 (i64.const 1073741823))
  (global $CELL i32 (i32.const 64))
  (global $MAXL i32 (i32.const 14))

  (global $M i32 (i32.const 4096))
  (global $TMP0 i32 (i32.const 4160))
  (global $TMP1 i32 (i32.const 4224))
  (global $TMP2 i32 (i32.const 4288))
  (global $TMP3 i32 (i32.const 4352))
  (global $TMP4 i32 (i32.const 4416))
  (global $TMP5 i32 (i32.const 4480))
  (global $TMP6 i32 (i32.const 4544))
  (global $TMP7 i32 (i32.const 4608))

  (global $STONES i32 (i32.const 8192))
  (global $COUNTS i32 (i32.const 24576))
  (global $HIDDEN i32 (i32.const 25088))
  (global $DROPS i32 (i32.const 25600))
  (global $BOWLS i32 (i32.const 28672))
  (global $OLD_BOWLS i32 (i32.const 29184))
  (global $NEXT_BOWLS i32 (i32.const 29696))
  (global $POURS i32 (i32.const 30208))
  (global $ORDER i32 (i32.const 30720))
  (global $ORDER46 i32 (i32.const 30784))
  (global $REMAINING_ORDER i32 (i32.const 30848))

  ;; Tablas normativas, codificadas como i32 en memoria con el miembro menos significativo primero.
  ;; HIDDEN_COEFF: siete filas [a,b,c,d].
  (data (i32.const 32000)
    "\03\00\00\00\04\00\00\00\06\00\00\00\08\00\00\00"
    "\05\00\00\00\07\00\00\00\0a\00\00\00\0c\00\00\00"
    "\07\00\00\00\0a\00\00\00\0e\00\00\00\10\00\00\00"
    "\09\00\00\00\0d\00\00\00\12\00\00\00\14\00\00\00"
    "\0b\00\00\00\10\00\00\00\16\00\00\00\18\00\00\00"
    "\0d\00\00\00\13\00\00\00\1a\00\00\00\1c\00\00\00"
    "\0f\00\00\00\16\00\00\00\1e\00\00\00\20\00\00\00")
  ;; HIDDEN_GRIND_STONE: 1,2,3,4,5,1,2.
  (data (i32.const 32500) "\01\00\00\00\02\00\00\00\03\00\00\00\04\00\00\00\05\00\00\00\01\00\00\00\02\00\00\00")
  ;; VISIBLE_GRINDS: once filas [a,b,c,d,kind].
  (data (i32.const 32600)
    "\03\00\00\00\05\00\00\00\07\00\00\00\0b\00\00\00\01\00\00\00"
    "\05\00\00\00\07\00\00\00\0b\00\00\00\0d\00\00\00\02\00\00\00"
    "\07\00\00\00\0b\00\00\00\0d\00\00\00\11\00\00\00\03\00\00\00"
    "\0b\00\00\00\0d\00\00\00\11\00\00\00\13\00\00\00\04\00\00\00"
    "\0d\00\00\00\11\00\00\00\13\00\00\00\17\00\00\00\05\00\00\00"
    "\11\00\00\00\13\00\00\00\17\00\00\00\1d\00\00\00\01\00\00\00"
    "\13\00\00\00\17\00\00\00\1d\00\00\00\1f\00\00\00\02\00\00\00"
    "\17\00\00\00\1d\00\00\00\1f\00\00\00\25\00\00\00\03\00\00\00"
    "\1d\00\00\00\1f\00\00\00\25\00\00\00\29\00\00\00\04\00\00\00"
    "\1f\00\00\00\25\00\00\00\29\00\00\00\2b\00\00\00\05\00\00\00"
    "\25\00\00\00\29\00\00\00\2b\00\00\00\2f\00\00\00\01\00\00\00")
  ;; Primos de las seis vasijas y piedra por posición.
  (data (i32.const 32900) "\11\00\00\00\13\00\00\00\17\00\00\00\1d\00\00\00\1f\00\00\00\25\00\00\00")
  (data (i32.const 32932) "\01\00\00\00\02\00\00\00\03\00\00\00\04\00\00\00\05\00\00\00\01\00\00\00")

  (func $addr (param $base i32) (param $index i32) (result i32)
    (i32.add (local.get $base) (i32.mul (local.get $index) (global.get $CELL))))
  (func $stone (param $i i32) (param $kind i32) (result i32)
    (call $addr (global.get $STONES)
      (i32.add (i32.mul (i32.sub (local.get $i) (i32.const 1)) (i32.const 5)) (i32.sub (local.get $kind) (i32.const 1)))))
  (func $count (param $which i32) (result i32) (call $addr (global.get $COUNTS) (i32.sub (local.get $which) (i32.const 1))))
  (func $hidden (param $k i32) (result i32) (call $addr (global.get $HIDDEN) (i32.sub (local.get $k) (i32.const 1))))
  (func $drop (param $i i32) (result i32) (call $addr (global.get $DROPS) (i32.sub (local.get $i) (i32.const 1))))
  (func $bowl (param $id i32) (result i32) (call $addr (global.get $BOWLS) (i32.sub (local.get $id) (i32.const 1))))
  (func $old_bowl (param $id i32) (result i32) (call $addr (global.get $OLD_BOWLS) (i32.sub (local.get $id) (i32.const 1))))
  (func $next_bowl (param $id i32) (result i32) (call $addr (global.get $NEXT_BOWLS) (i32.sub (local.get $id) (i32.const 1))))
  (func $pour (param $pos i32) (result i32) (call $addr (global.get $POURS) (i32.sub (local.get $pos) (i32.const 1))))

  ;; -------- Naturales exactos para los residuos 1..M --------
  (func $len (param $p i32) (result i32) (i32.load (local.get $p)))
  (func $set_len (param $p i32) (param $n i32) (i32.store (local.get $p) (local.get $n)))
  (func $limb_addr (param $p i32) (param $i i32) (result i32) (i32.add (i32.add (local.get $p) (i32.const 4)) (i32.mul (local.get $i) (i32.const 4))))
  (func $limb (param $p i32) (param $i i32) (result i32) (i32.load (call $limb_addr (local.get $p) (local.get $i))))
  (func $set_limb (param $p i32) (param $i i32) (param $v i32)
    (if (i32.ge_u (local.get $i) (global.get $MAXL)) (then unreachable))
    (i32.store (call $limb_addr (local.get $p) (local.get $i)) (local.get $v)))
  (func $zero (param $p i32) (call $set_len (local.get $p) (i32.const 0)))
  (func $normalize (param $p i32)
    (local $n i32)
    (local.set $n (call $len (local.get $p)))
    (block $done (loop $again
      (br_if $done (i32.eqz (local.get $n)))
      (br_if $done (i32.ne (call $limb (local.get $p) (i32.sub (local.get $n) (i32.const 1))) (i32.const 0)))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br $again)))
    (call $set_len (local.get $p) (local.get $n)))
  (func $copy (param $dst i32) (param $src i32)
    (local $i i32) (local $n i32)
    (local.set $n (call $len (local.get $src)))
    (call $set_len (local.get $dst) (local.get $n))
    (local.set $i (i32.const 0))
    (block $done (loop $again
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (call $set_limb (local.get $dst) (local.get $i) (call $limb (local.get $src) (local.get $i)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $again))))
  (func $from_u64 (param $p i32) (param $x i64)
    (local $n i32)
    (call $zero (local.get $p))
    (local.set $n (i32.const 0))
    (block $done (loop $again
      (br_if $done (i64.eqz (local.get $x)))
      (call $set_limb (local.get $p) (local.get $n) (i32.wrap_i64 (i64.and (local.get $x) (global.get $MASK))))
      (local.set $x (i64.shr_u (local.get $x) (i64.const 30)))
      (local.set $n (i32.add (local.get $n) (i32.const 1)))
      (br $again)))
    (call $set_len (local.get $p) (local.get $n)))
  (func $cmp (param $a i32) (param $b i32) (result i32)
    (local $la i32) (local $lb i32) (local $i i32) (local $av i32) (local $bv i32)
    (local.set $la (call $len (local.get $a))) (local.set $lb (call $len (local.get $b)))
    (if (i32.lt_u (local.get $la) (local.get $lb)) (then (return (i32.const -1))))
    (if (i32.gt_u (local.get $la) (local.get $lb)) (then (return (i32.const 1))))
    (local.set $i (local.get $la))
    (block $eq (loop $again
      (br_if $eq (i32.eqz (local.get $i)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (local.set $av (call $limb (local.get $a) (local.get $i)))
      (local.set $bv (call $limb (local.get $b) (local.get $i)))
      (if (i32.lt_u (local.get $av) (local.get $bv)) (then (return (i32.const -1))))
      (if (i32.gt_u (local.get $av) (local.get $bv)) (then (return (i32.const 1))))
      (br $again)))
    (i32.const 0))
  (func $add (param $dst i32) (param $a i32) (param $b i32)
    (local $la i32) (local $lb i32) (local $n i32) (local $i i32)
    (local $carry i64) (local $av i64) (local $bv i64) (local $s i64)
    (local.set $la (call $len (local.get $a))) (local.set $lb (call $len (local.get $b)))
    (local.set $n (select (local.get $la) (local.get $lb) (i32.gt_u (local.get $la) (local.get $lb))))
    (local.set $i (i32.const 0)) (local.set $carry (i64.const 0))
    (block $done (loop $again
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $av (if (result i64) (i32.lt_u (local.get $i) (local.get $la)) (then (i64.extend_i32_u (call $limb (local.get $a) (local.get $i)))) (else (i64.const 0))))
      (local.set $bv (if (result i64) (i32.lt_u (local.get $i) (local.get $lb)) (then (i64.extend_i32_u (call $limb (local.get $b) (local.get $i)))) (else (i64.const 0))))
      (local.set $s (i64.add (i64.add (local.get $av) (local.get $bv)) (local.get $carry)))
      (call $set_limb (local.get $dst) (local.get $i) (i32.wrap_i64 (i64.and (local.get $s) (global.get $MASK))))
      (local.set $carry (i64.shr_u (local.get $s) (i64.const 30)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $again)))
    (if (i64.ne (local.get $carry) (i64.const 0)) (then (call $set_limb (local.get $dst) (local.get $n) (i32.wrap_i64 (local.get $carry))) (local.set $n (i32.add (local.get $n) (i32.const 1)))))
    (call $set_len (local.get $dst) (local.get $n)))
  (func $sub (param $dst i32) (param $a i32) (param $b i32)
    (local $n i32) (local $lb i32) (local $i i32) (local $borrow i64) (local $av i64) (local $bv i64) (local $v i64)
    (if (i32.lt_s (call $cmp (local.get $a) (local.get $b)) (i32.const 0)) (then unreachable))
    (local.set $n (call $len (local.get $a))) (local.set $lb (call $len (local.get $b)))
    (local.set $borrow (i64.const 0)) (local.set $i (i32.const 0))
    (block $done (loop $again
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $av (i64.extend_i32_u (call $limb (local.get $a) (local.get $i))))
      (local.set $bv (if (result i64) (i32.lt_u (local.get $i) (local.get $lb)) (then (i64.extend_i32_u (call $limb (local.get $b) (local.get $i)))) (else (i64.const 0))))
      (local.set $v (i64.sub (i64.sub (local.get $av) (local.get $bv)) (local.get $borrow)))
      (if (i64.lt_s (local.get $v) (i64.const 0)) (then (local.set $v (i64.add (local.get $v) (global.get $BASE))) (local.set $borrow (i64.const 1))) (else (local.set $borrow (i64.const 0))))
      (call $set_limb (local.get $dst) (local.get $i) (i32.wrap_i64 (local.get $v)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $again)))
    (if (i64.ne (local.get $borrow) (i64.const 0)) (then unreachable))
    (call $set_len (local.get $dst) (local.get $n)) (call $normalize (local.get $dst)))
  (func $mul (param $dst i32) (param $a i32) (param $b i32)
    (local $la i32) (local $lb i32) (local $n i32) (local $i i32) (local $j i32) (local $k i32)
    (local $carry i64) (local $t i64)
    (local.set $la (call $len (local.get $a))) (local.set $lb (call $len (local.get $b)))
    (if (i32.or (i32.eqz (local.get $la)) (i32.eqz (local.get $lb))) (then (call $zero (local.get $dst)) (return)))
    (local.set $n (i32.add (local.get $la) (local.get $lb)))
    (local.set $i (i32.const 0))
    (block $zd (loop $z (br_if $zd (i32.ge_u (local.get $i) (local.get $n))) (call $set_limb (local.get $dst) (local.get $i) (i32.const 0)) (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $z)))
    (call $set_len (local.get $dst) (local.get $n))
    (local.set $i (i32.const 0))
    (block $od (loop $outer
      (br_if $od (i32.ge_u (local.get $i) (local.get $la)))
      (local.set $carry (i64.const 0)) (local.set $j (i32.const 0))
      (block $id (loop $inner
        (br_if $id (i32.ge_u (local.get $j) (local.get $lb)))
        (local.set $k (i32.add (local.get $i) (local.get $j)))
        (local.set $t (i64.add (i64.add (i64.extend_i32_u (call $limb (local.get $dst) (local.get $k))) (i64.mul (i64.extend_i32_u (call $limb (local.get $a) (local.get $i))) (i64.extend_i32_u (call $limb (local.get $b) (local.get $j))))) (local.get $carry)))
        (call $set_limb (local.get $dst) (local.get $k) (i32.wrap_i64 (i64.and (local.get $t) (global.get $MASK))))
        (local.set $carry (i64.shr_u (local.get $t) (i64.const 30)))
        (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $inner)))
      (local.set $k (i32.add (local.get $i) (local.get $lb)))
      (block $cd (loop $cl (br_if $cd (i64.eqz (local.get $carry)))
        (local.set $t (i64.add (i64.extend_i32_u (call $limb (local.get $dst) (local.get $k))) (local.get $carry)))
        (call $set_limb (local.get $dst) (local.get $k) (i32.wrap_i64 (i64.and (local.get $t) (global.get $MASK))))
        (local.set $carry (i64.shr_u (local.get $t) (i64.const 30)))
        (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $cl)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $outer)))
    (call $normalize (local.get $dst)))
  (func $mul_small (param $dst i32) (param $a i32) (param $x i32)
    (local $i i32) (local $n i32) (local $carry i64) (local $v i64)
    (if (i32.eqz (local.get $x)) (then (call $zero (local.get $dst)) (return)))
    (local.set $n (call $len (local.get $a))) (local.set $i (i32.const 0)) (local.set $carry (i64.const 0))
    (block $done (loop $again
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $v (i64.add (i64.mul (i64.extend_i32_u (call $limb (local.get $a) (local.get $i))) (i64.extend_i32_u (local.get $x))) (local.get $carry)))
      (call $set_limb (local.get $dst) (local.get $i) (i32.wrap_i64 (i64.and (local.get $v) (global.get $MASK))))
      (local.set $carry (i64.shr_u (local.get $v) (i64.const 30)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $again)))
    (if (i64.ne (local.get $carry) (i64.const 0)) (then (call $set_limb (local.get $dst) (local.get $n) (i32.wrap_i64 (local.get $carry))) (local.set $n (i32.add (local.get $n) (i32.const 1)))))
    (call $set_len (local.get $dst) (local.get $n)))
  (func $shift_left1 (param $p i32)
    (local $n i32) (local $i i32) (local $carry i64) (local $v i64)
    (local.set $n (call $len (local.get $p))) (local.set $i (i32.const 0)) (local.set $carry (i64.const 0))
    (block $done (loop $again
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $v (i64.add (i64.shl (i64.extend_i32_u (call $limb (local.get $p) (local.get $i))) (i64.const 1)) (local.get $carry)))
      (call $set_limb (local.get $p) (local.get $i) (i32.wrap_i64 (i64.and (local.get $v) (global.get $MASK))))
      (local.set $carry (i64.shr_u (local.get $v) (i64.const 30)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $again)))
    (if (i64.ne (local.get $carry) (i64.const 0)) (then (call $set_limb (local.get $p) (local.get $n) (i32.wrap_i64 (local.get $carry))) (call $set_len (local.get $p) (i32.add (local.get $n) (i32.const 1))))))
  (func $bitlen (param $p i32) (result i32)
    (local $n i32) (local $top i32) (local $bits i32)
    (local.set $n (call $len (local.get $p))) (if (i32.eqz (local.get $n)) (then (return (i32.const 0))))
    (local.set $top (call $limb (local.get $p) (i32.sub (local.get $n) (i32.const 1))))
    (local.set $bits (i32.mul (i32.sub (local.get $n) (i32.const 1)) (i32.const 30)))
    (block $done (loop $again (br_if $done (i32.eqz (local.get $top))) (local.set $bits (i32.add (local.get $bits) (i32.const 1))) (local.set $top (i32.shr_u (local.get $top) (i32.const 1))) (br $again)))
    (local.get $bits))
  (func $get_bit (param $p i32) (param $bit i32) (result i32)
    (local $li i32) (local $sh i32)
    (local.set $li (i32.div_u (local.get $bit) (i32.const 30)))
    (if (i32.ge_u (local.get $li) (call $len (local.get $p))) (then (return (i32.const 0))))
    (local.set $sh (i32.rem_u (local.get $bit) (i32.const 30)))
    (i32.and (i32.shr_u (call $limb (local.get $p) (local.get $li)) (local.get $sh)) (i32.const 1)))
  (func $add_small_inplace (param $p i32) (param $x i32)
    (local $i i32) (local $n i32) (local $carry i64) (local $v i64)
    (local.set $carry (i64.extend_i32_u (local.get $x))) (local.set $n (call $len (local.get $p))) (local.set $i (i32.const 0))
    (block $done (loop $again
      (br_if $done (i64.eqz (local.get $carry)))
      (if (i32.ge_u (local.get $i) (local.get $n)) (then (call $set_limb (local.get $p) (local.get $i) (i32.const 0)) (local.set $n (i32.add (local.get $n) (i32.const 1))) (call $set_len (local.get $p) (local.get $n))))
      (local.set $v (i64.add (i64.extend_i32_u (call $limb (local.get $p) (local.get $i))) (local.get $carry)))
      (call $set_limb (local.get $p) (local.get $i) (i32.wrap_i64 (i64.and (local.get $v) (global.get $MASK))))
      (local.set $carry (i64.shr_u (local.get $v) (i64.const 30)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $again))))
  (func $divmod (param $q i32) (param $r i32) (param $n i32) (param $d i32)
    (local $bits i32) (local $pos i32)
    (if (i32.eqz (call $len (local.get $d))) (then unreachable))
    (call $zero (local.get $q)) (call $zero (local.get $r))
    (local.set $bits (call $bitlen (local.get $n))) (local.set $pos (local.get $bits))
    (block $done (loop $again
      (br_if $done (i32.eqz (local.get $pos)))
      (local.set $pos (i32.sub (local.get $pos) (i32.const 1)))
      (call $shift_left1 (local.get $q)) (call $shift_left1 (local.get $r))
      (if (i32.ne (call $get_bit (local.get $n) (local.get $pos)) (i32.const 0)) (then (call $add_small_inplace (local.get $r) (i32.const 1))))
      (if (i32.ge_s (call $cmp (local.get $r) (local.get $d)) (i32.const 0)) (then (call $sub (global.get $TMP7) (local.get $r) (local.get $d)) (call $copy (local.get $r) (global.get $TMP7)) (call $add_small_inplace (local.get $q) (i32.const 1))))
      (br $again))))

  (func $init_m
    ;; M=2^127-1 en base 2^30: cuatro miembros completos y 127 en el quinto.
    (call $set_len (global.get $M) (i32.const 5))
    (call $set_limb (global.get $M) (i32.const 0) (i32.const 1073741823))
    (call $set_limb (global.get $M) (i32.const 1) (i32.const 1073741823))
    (call $set_limb (global.get $M) (i32.const 2) (i32.const 1073741823))
    (call $set_limb (global.get $M) (i32.const 3) (i32.const 1073741823))
    (call $set_limb (global.get $M) (i32.const 4) (i32.const 127)))

  ;; OPTIMIZACIÓN: se reduce después de cada suma o producto elemental.
  ;; EQUIVALENCIA: todos los pasos conservan la misma clase módulo M y SAVE elige el representante único 1..M.
  ;; CASOS LÍMITE: residuo cero se convierte en M.
  ;; POR QUÉ ES SEGURO: ninguna decisión normativa observa los intermedios anteriores al SAVE de la expresión.
  (func $save_big (param $dst i32) (param $raw i32)
    (call $divmod (global.get $TMP5) (global.get $TMP6) (local.get $raw) (global.get $M))
    (if (i32.eqz (call $len (global.get $TMP6))) (then (call $copy (local.get $dst) (global.get $M))) (else (call $copy (local.get $dst) (global.get $TMP6)))))
  (func $r_from_u64 (param $dst i32) (param $x i64) (call $from_u64 (global.get $TMP0) (local.get $x)) (call $save_big (local.get $dst) (global.get $TMP0)))
  (func $r_add (param $dst i32) (param $a i32) (param $b i32) (call $add (global.get $TMP0) (local.get $a) (local.get $b)) (call $save_big (local.get $dst) (global.get $TMP0)))
  (func $r_add_small (param $dst i32) (param $a i32) (param $x i32) (call $from_u64 (global.get $TMP1) (i64.extend_i32_u (local.get $x))) (call $r_add (local.get $dst) (local.get $a) (global.get $TMP1)))
  (func $r_mul (param $dst i32) (param $a i32) (param $b i32) (call $mul (global.get $TMP0) (local.get $a) (local.get $b)) (call $save_big (local.get $dst) (global.get $TMP0)))
  (func $r_mul_small (param $dst i32) (param $a i32) (param $x i32) (call $mul_small (global.get $TMP0) (local.get $a) (local.get $x)) (call $save_big (local.get $dst) (global.get $TMP0)))
  (func $r_square (param $dst i32) (param $a i32) (call $r_mul (local.get $dst) (local.get $a) (local.get $a)))
  (func $r_mod_small (param $a i32) (param $d i32) (result i32)
    (local $i i32) (local $r i64)
    (local.set $i (call $len (local.get $a))) (local.set $r (i64.const 0))
    (block $done (loop $again
      (br_if $done (i32.eqz (local.get $i)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (local.set $r (i64.rem_u (i64.add (i64.shl (local.get $r) (i64.const 30)) (i64.extend_i32_u (call $limb (local.get $a) (local.get $i)))) (i64.extend_i32_u (local.get $d))))
      (br $again)))
    (i32.wrap_i64 (local.get $r)))

  (func $copy_r (param $dst i32) (param $src i32) (call $copy (local.get $dst) (local.get $src)))
  (func $sum_into (param $acc i32) (param $x i32) (call $r_add (global.get $TMP2) (local.get $acc) (local.get $x)) (call $copy_r (local.get $acc) (global.get $TMP2)))
  (func $muladd_small (param $acc i32) (param $x i32) (param $k i32) (call $r_mul_small (global.get $TMP3) (local.get $x) (local.get $k)) (call $sum_into (local.get $acc) (global.get $TMP3)))
  (func $muladd (param $acc i32) (param $a i32) (param $b i32) (call $r_mul (global.get $TMP3) (local.get $a) (local.get $b)) (call $sum_into (local.get $acc) (global.get $TMP3)))

  ;; -------- Conteos del trabajo para el adaptador i64 --------
  (func $abs_diff_u64_safe (param $a i64) (param $b i64) (result i64)
    ;; Los casos fijos de esta etapa permanecen lejos de los extremos de i64.
    (if (result i64) (i64.ge_s (local.get $a) (local.get $b)) (then (i64.sub (local.get $a) (local.get $b))) (else (i64.sub (local.get $b) (local.get $a)))))
  (func $day_count_fixture (param $day i64) (param $dst i32)
    (local $d i64)
    (if (i64.eq (local.get $day) (i64.const -15055671)) (then (call $r_from_u64 (local.get $dst) (i64.const 1)) (return)))
    (if (i64.gt_s (local.get $day) (i64.const -15055671))
      (then (local.set $d (i64.sub (local.get $day) (i64.const -15055671))) (call $r_from_u64 (local.get $dst) (i64.add (i64.mul (local.get $d) (i64.const 2)) (i64.const 1))))
      (else (local.set $d (i64.sub (i64.const -15055671) (local.get $day))) (call $r_from_u64 (local.get $dst) (i64.mul (local.get $d) (i64.const 2))))))
  (func $work_counts_fixture (param $c i64) (param $t i64)
    (call $day_count_fixture (local.get $c) (call $count (i32.const 1)))
    (call $day_count_fixture (local.get $t) (call $count (i32.const 2)))
    (call $r_from_u64 (call $count (i32.const 3)) (i64.add (call $abs_diff_u64_safe (local.get $t) (local.get $c)) (i64.const 1)))
    (call $r_add (call $count (i32.const 4)) (call $count (i32.const 1)) (call $count (i32.const 2)))
    (call $r_from_u64 (call $count (i32.const 5))
      (if (result i64) (i64.lt_s (local.get $t) (local.get $c)) (then (i64.const 1)) (else (if (result i64) (i64.eq (local.get $t) (local.get $c)) (then (i64.const 2)) (else (i64.const 3)))))))

  ;; -------- Piedras --------
  (func $build_stones
    (local $i i32)
    (call $r_from_u64 (call $stone (i32.const 1) (i32.const 1)) (i64.const 17))
    (call $r_from_u64 (call $stone (i32.const 1) (i32.const 2)) (i64.const 29))
    (call $r_from_u64 (call $stone (i32.const 1) (i32.const 3)) (i64.const 43))
    (call $r_from_u64 (call $stone (i32.const 1) (i32.const 4)) (i64.const 71))
    (call $r_from_u64 (call $stone (i32.const 1) (i32.const 5)) (i64.const 101))
    (local.set $i (i32.const 2))
    (block $done (loop $again
      (br_if $done (i32.gt_u (local.get $i) (i32.const 46)))
      ;; trigo
      (call $r_square (global.get $TMP1) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 1)))
      (call $copy_r (global.get $TMP2) (global.get $TMP1))
      (call $muladd_small (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 2)) (i32.const 3))
      (call $r_add_small (call $stone (local.get $i) (i32.const 1)) (global.get $TMP2) (local.get $i))
      ;; cebada
      (call $r_square (global.get $TMP1) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 2)))
      (call $copy_r (global.get $TMP2) (global.get $TMP1))
      (call $muladd_small (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 3)) (i32.const 5))
      (call $sum_into (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 1)))
      (call $copy_r (call $stone (local.get $i) (i32.const 2)) (global.get $TMP2))
      ;; sal
      (call $r_square (global.get $TMP1) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 3)))
      (call $copy_r (global.get $TMP2) (global.get $TMP1))
      (call $muladd_small (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 4)) (i32.const 7))
      (call $sum_into (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 2)))
      (call $copy_r (call $stone (local.get $i) (i32.const 3)) (global.get $TMP2))
      ;; amargo
      (call $r_square (global.get $TMP1) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 4)))
      (call $copy_r (global.get $TMP2) (global.get $TMP1))
      (call $muladd_small (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 5)) (i32.const 11))
      (call $sum_into (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 3)))
      (call $copy_r (call $stone (local.get $i) (i32.const 4)) (global.get $TMP2))
      ;; rojo
      (call $r_square (global.get $TMP1) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 5)))
      (call $copy_r (global.get $TMP2) (global.get $TMP1))
      (call $muladd_small (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 1)) (i32.const 13))
      (call $sum_into (global.get $TMP2) (call $stone (i32.sub (local.get $i) (i32.const 1)) (i32.const 4)))
      (call $copy_r (call $stone (local.get $i) (i32.const 5)) (global.get $TMP2))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $again))))

  ;; -------- Gotas ocultas y visibles --------
  (func $build_hidden
    (local $k i32) (local $g i32) (local $a i32) (local $b i32) (local $c i32) (local $d i32) (local $kind i32)
    (local.set $k (i32.const 1))
    (block $done (loop $again
      (br_if $done (i32.gt_u (local.get $k) (i32.const 7)))
      (local.set $a (i32.load (i32.add (i32.const 32000) (i32.mul (i32.sub (local.get $k) (i32.const 1)) (i32.const 16)))))
      (local.set $b (i32.load (i32.add (i32.const 32004) (i32.mul (i32.sub (local.get $k) (i32.const 1)) (i32.const 16)))))
      (local.set $c (i32.load (i32.add (i32.const 32008) (i32.mul (i32.sub (local.get $k) (i32.const 1)) (i32.const 16)))))
      (local.set $d (i32.load (i32.add (i32.const 32012) (i32.mul (i32.sub (local.get $k) (i32.const 1)) (i32.const 16)))))
      (call $copy_r (global.get $TMP2) (call $count (i32.const 1)))
      (call $muladd_small (global.get $TMP2) (call $count (i32.const 2)) (local.get $a))
      (call $muladd_small (global.get $TMP2) (call $count (i32.const 3)) (local.get $b))
      (call $muladd_small (global.get $TMP2) (call $count (i32.const 4)) (local.get $c))
      (call $muladd_small (global.get $TMP2) (call $count (i32.const 5)) (local.get $d))
      (call $sum_into (global.get $TMP2) (call $stone (local.get $k) (i32.const 1)))
      (call $sum_into (global.get $TMP2) (call $stone (local.get $k) (i32.const 2)))
      (call $sum_into (global.get $TMP2) (call $stone (local.get $k) (i32.const 3)))
      (call $sum_into (global.get $TMP2) (call $stone (local.get $k) (i32.const 4)))
      (call $sum_into (global.get $TMP2) (call $stone (local.get $k) (i32.const 5)))
      (call $copy_r (call $hidden (local.get $k)) (global.get $TMP2))
      (local.set $g (i32.const 1))
      (block $gd (loop $grind
        (br_if $gd (i32.gt_u (local.get $g) (i32.const 7)))
        (call $r_square (global.get $TMP1) (call $hidden (local.get $k)))
        (call $copy_r (global.get $TMP2) (global.get $TMP1))
        (call $muladd_small (global.get $TMP2) (call $hidden (local.get $k)) (i32.const 3))
        (local.set $kind (i32.load (i32.add (i32.const 32500) (i32.mul (i32.sub (local.get $g) (i32.const 1)) (i32.const 4)))))
        (call $sum_into (global.get $TMP2) (call $stone (local.get $k) (local.get $kind)))
        (call $r_add_small (call $hidden (local.get $k)) (global.get $TMP2) (local.get $g))
        (local.set $g (i32.add (local.get $g) (i32.const 1))) (br $grind)))
      (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $again))))

  (func $prior (param $i i32) (param $back i32) (result i32)
    (local $slot i32)
    (local.set $slot (i32.sub (local.get $i) (local.get $back)))
    (if (result i32) (i32.ge_s (local.get $slot) (i32.const 1))
      (then (call $drop (local.get $slot)))
      (else (call $hidden (i32.sub (i32.const 1) (local.get $slot))))))

  (func $build_visible
    (local $i i32) (local $g i32) (local $p1 i32) (local $p3 i32) (local $p7 i32)
    (local $row i32) (local $a i32) (local $b i32) (local $c i32) (local $d i32) (local $kind i32)
    (local.set $i (i32.const 1))
    (block $done (loop $again
      (br_if $done (i32.gt_u (local.get $i) (i32.const 46)))
      (local.set $p1 (call $prior (local.get $i) (i32.const 1)))
      (local.set $p3 (call $prior (local.get $i) (i32.const 3)))
      (local.set $p7 (call $prior (local.get $i) (i32.const 7)))
      (call $r_mul (global.get $TMP2) (call $stone (local.get $i) (i32.const 1)) (call $count (i32.const 1)))
      (call $muladd (global.get $TMP2) (call $stone (local.get $i) (i32.const 2)) (call $count (i32.const 2)))
      (call $muladd (global.get $TMP2) (call $stone (local.get $i) (i32.const 3)) (call $count (i32.const 3)))
      (call $muladd (global.get $TMP2) (call $stone (local.get $i) (i32.const 4)) (call $count (i32.const 4)))
      (call $muladd (global.get $TMP2) (call $stone (local.get $i) (i32.const 5)) (call $count (i32.const 5)))
      (call $sum_into (global.get $TMP2) (local.get $p1))
      (call $muladd_small (global.get $TMP2) (local.get $p3) (i32.const 3))
      (call $muladd_small (global.get $TMP2) (local.get $p7) (i32.const 5))
      (call $r_add_small (call $drop (local.get $i)) (global.get $TMP2) (local.get $i))
      (local.set $g (i32.const 1))
      (block $gd (loop $grind
        (br_if $gd (i32.gt_u (local.get $g) (i32.const 11)))
        (local.set $row (i32.add (i32.const 32600) (i32.mul (i32.sub (local.get $g) (i32.const 1)) (i32.const 20))))
        (local.set $a (i32.load (local.get $row))) (local.set $b (i32.load offset=4 (local.get $row))) (local.set $c (i32.load offset=8 (local.get $row))) (local.set $d (i32.load offset=12 (local.get $row))) (local.set $kind (i32.load offset=16 (local.get $row)))
        (call $r_square (global.get $TMP1) (call $drop (local.get $i)))
        (call $copy_r (global.get $TMP2) (global.get $TMP1))
        (call $muladd_small (global.get $TMP2) (call $drop (local.get $i)) (local.get $a))
        (call $muladd_small (global.get $TMP2) (local.get $p1) (local.get $b))
        (call $muladd_small (global.get $TMP2) (local.get $p3) (local.get $c))
        (call $muladd_small (global.get $TMP2) (local.get $p7) (local.get $d))
        (call $sum_into (global.get $TMP2) (call $stone (local.get $i) (local.get $kind)))
        (call $copy_r (call $drop (local.get $i)) (global.get $TMP2))
        (local.set $g (i32.add (local.get $g) (i32.const 1))) (br $grind)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $again))))

  ;; -------- Orden lexicográfico de las seis vasijas --------
  (func $fact (param $n i32) (result i32)
    (if (i32.eq (local.get $n) (i32.const 0)) (then (return (i32.const 1))))
    (if (i32.eq (local.get $n) (i32.const 1)) (then (return (i32.const 1))))
    (if (i32.eq (local.get $n) (i32.const 2)) (then (return (i32.const 2))))
    (if (i32.eq (local.get $n) (i32.const 3)) (then (return (i32.const 6))))
    (if (i32.eq (local.get $n) (i32.const 4)) (then (return (i32.const 24))))
    (if (i32.eq (local.get $n) (i32.const 5)) (then (return (i32.const 120))))
    (i32.const 720))
  (func $order_from_rank (param $rank i32)
    (local $rank0 i32) (local $slots i32) (local $q i32) (local $block i32) (local $p i32) (local $j i32) (local $count i32)
    (local.set $j (i32.const 0)) (block $initd (loop $init (br_if $initd (i32.ge_u (local.get $j) (i32.const 6))) (i32.store (i32.add (global.get $REMAINING_ORDER) (i32.mul (local.get $j) (i32.const 4))) (i32.add (local.get $j) (i32.const 1))) (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $init)))
    (local.set $rank0 (i32.sub (local.get $rank) (i32.const 1))) (local.set $slots (i32.const 6)) (local.set $p (i32.const 0))
    (block $done (loop $again
      (br_if $done (i32.eqz (local.get $slots)))
      (local.set $block (call $fact (i32.sub (local.get $slots) (i32.const 1))))
      (local.set $q (i32.div_u (local.get $rank0) (local.get $block)))
      (local.set $rank0 (i32.rem_u (local.get $rank0) (local.get $block)))
      (i32.store (i32.add (global.get $ORDER) (i32.mul (local.get $p) (i32.const 4))) (i32.load (i32.add (global.get $REMAINING_ORDER) (i32.mul (local.get $q) (i32.const 4)))))
      (local.set $j (local.get $q)) (local.set $count (i32.sub (local.get $slots) (i32.const 1)))
      (block $sd (loop $shift (br_if $sd (i32.ge_u (local.get $j) (local.get $count))) (i32.store (i32.add (global.get $REMAINING_ORDER) (i32.mul (local.get $j) (i32.const 4))) (i32.load (i32.add (global.get $REMAINING_ORDER) (i32.mul (i32.add (local.get $j) (i32.const 1)) (i32.const 4))))) (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $shift)))
      (local.set $slots (i32.sub (local.get $slots) (i32.const 1))) (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $again))))
  (func $order_from_drop (param $r i32)
    (local $n i32)
    (local.set $n (call $r_mod_small (local.get $r) (i32.const 720)))
    (if (i32.eqz (local.get $n)) (then (local.set $n (i32.const 720))))
    (call $order_from_rank (local.get $n)))
  (func $wrap6 (param $p i32) (result i32)
    (i32.add (i32.rem_u (i32.add (local.get $p) (i32.const 5)) (i32.const 6)) (i32.const 1)))
  (func $order_id (param $pos i32) (result i32) (i32.load (i32.add (global.get $ORDER) (i32.mul (i32.sub (local.get $pos) (i32.const 1)) (i32.const 4)))))

  ;; -------- Vasijas --------
  (func $initial_bowls
    (local $id i32) (local $prime i32)
    (local.set $id (i32.const 1))
    (block $done (loop $again
      (br_if $done (i32.gt_u (local.get $id) (i32.const 6)))
      (call $copy_r (global.get $TMP2) (call $count (i32.const 1)))
      (call $muladd_small (global.get $TMP2) (call $count (i32.const 2)) (local.get $id))
      (call $sum_into (global.get $TMP2) (call $count (i32.const 3)))
      (call $sum_into (global.get $TMP2) (call $count (i32.const 4)))
      (call $sum_into (global.get $TMP2) (call $count (i32.const 5)))
      (local.set $prime (i32.load (i32.add (i32.const 32900) (i32.mul (i32.sub (local.get $id) (i32.const 1)) (i32.const 4)))))
      (call $r_add_small (global.get $TMP2) (global.get $TMP2) (i32.mul (local.get $prime) (local.get $prime)))
      (call $r_square (global.get $TMP1) (global.get $TMP2))
      (call $r_add_small (call $bowl (local.get $id)) (global.get $TMP1) (local.get $id))
      (local.set $id (i32.add (local.get $id) (i32.const 1))) (br $again))))

  (func $copy_bowls_to_old
    (local $id i32) (local.set $id (i32.const 1))
    (block $done (loop $again (br_if $done (i32.gt_u (local.get $id) (i32.const 6))) (call $copy_r (call $old_bowl (local.get $id)) (call $bowl (local.get $id))) (local.set $id (i32.add (local.get $id) (i32.const 1))) (br $again))))
  (func $commit_next_bowls
    (local $id i32) (local.set $id (i32.const 1))
    (block $done (loop $again (br_if $done (i32.gt_u (local.get $id) (i32.const 6))) (call $copy_r (call $bowl (local.get $id)) (call $next_bowl (local.get $id))) (local.set $id (i32.add (local.get $id) (i32.const 1))) (br $again))))

  (func $apply_drops
    (local $i i32) (local $pos i32) (local $id i32) (local $prev i32) (local $next i32) (local $kind i32)
    (local.set $i (i32.const 1))
    (block $done (loop $again
      (br_if $done (i32.gt_u (local.get $i) (i32.const 46)))
      (call $order_from_drop (call $drop (local.get $i)))
      (call $copy_bowls_to_old)
      ;; vertidos 1..3; 4..6 = 0 exacto, que se suma sin pasar por SAVE.
      (local.set $pos (i32.const 1))
      (block $pd (loop $pl
        (br_if $pd (i32.gt_u (local.get $pos) (i32.const 3)))
        (local.set $id (call $order_id (local.get $pos)))
        (call $r_square (global.get $TMP1) (call $drop (local.get $i)))
        (call $copy_r (global.get $TMP2) (global.get $TMP1))
        (call $muladd (global.get $TMP2) (call $stone (local.get $i) (local.get $pos)) (call $old_bowl (local.get $id)))
        (call $r_add_small (call $pour (local.get $pos)) (global.get $TMP2) (i32.mul (if (result i32) (i32.eq (local.get $pos) (i32.const 1)) (then (i32.const 3)) (else (if (result i32) (i32.eq (local.get $pos) (i32.const 2)) (then (i32.const 5)) (else (i32.const 7))))) (local.get $i)))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1))) (br $pl)))
      (local.set $pos (i32.const 4)) (block $zpd (loop $zpl (br_if $zpd (i32.gt_u (local.get $pos) (i32.const 6))) (call $zero (call $pour (local.get $pos))) (local.set $pos (i32.add (local.get $pos) (i32.const 1))) (br $zpl)))
      (local.set $pos (i32.const 1))
      (block $sd (loop $stir
        (br_if $sd (i32.gt_u (local.get $pos) (i32.const 6)))
        (local.set $id (call $order_id (local.get $pos)))
        (local.set $prev (call $order_id (call $wrap6 (i32.sub (local.get $pos) (i32.const 1)))))
        (local.set $next (call $order_id (call $wrap6 (i32.add (local.get $pos) (i32.const 1)))))
        (local.set $kind (i32.load (i32.add (i32.const 32932) (i32.mul (i32.sub (local.get $pos) (i32.const 1)) (i32.const 4)))))
        (call $copy_r (global.get $TMP2) (call $old_bowl (local.get $id)))
        (call $muladd_small (global.get $TMP2) (call $old_bowl (local.get $prev)) (i32.const 2))
        (call $muladd_small (global.get $TMP2) (call $old_bowl (local.get $next)) (i32.const 3))
        (if (i32.le_u (local.get $pos) (i32.const 3)) (then (call $sum_into (global.get $TMP2) (call $pour (local.get $pos)))))
        (call $sum_into (global.get $TMP2) (call $drop (local.get $i)))
        (call $sum_into (global.get $TMP2) (call $stone (local.get $i) (local.get $kind)))
        (call $r_square (global.get $TMP1) (global.get $TMP2))
        (call $copy_r (global.get $TMP2) (global.get $TMP1))
        (call $r_mul (global.get $TMP3) (call $old_bowl (local.get $prev)) (call $old_bowl (local.get $next)))
        (call $muladd_small (global.get $TMP2) (global.get $TMP3) (i32.const 5))
        (call $r_add_small (call $next_bowl (local.get $id)) (global.get $TMP2) (i32.mul (local.get $i) (local.get $pos)))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1))) (br $stir)))
      (call $commit_next_bowls)
      (if (i32.eq (local.get $i) (i32.const 46))
        (then
          (local.set $pos (i32.const 1))
          (block $ld (loop $ll (br_if $ld (i32.gt_u (local.get $pos) (i32.const 6))) (i32.store (i32.add (global.get $ORDER46) (i32.mul (i32.sub (local.get $pos) (i32.const 1)) (i32.const 4))) (call $order_id (local.get $pos))) (local.set $pos (i32.add (local.get $pos) (i32.const 1))) (br $ll)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $again))))

  (func $post_stir12
    (local $stir i32) (local $id i32) (local $pos i32) (local $prev i32) (local $next i32) (local $orderN i32)
    (local.set $stir (i32.const 1))
    (block $done (loop $again
      (br_if $done (i32.gt_u (local.get $stir) (i32.const 12)))
      (call $copy_bowls_to_old)
      (call $copy_r (global.get $TMP2) (call $old_bowl (i32.const 1)))
      (local.set $id (i32.const 2)) (block $sumd (loop $suml (br_if $sumd (i32.gt_u (local.get $id) (i32.const 6))) (call $sum_into (global.get $TMP2) (call $old_bowl (local.get $id))) (local.set $id (i32.add (local.get $id) (i32.const 1))) (br $suml)))
      (call $r_add_small (global.get $TMP2) (global.get $TMP2) (i32.mul (i32.const 149) (local.get $stir)))
      (local.set $orderN (call $r_mod_small (global.get $TMP2) (i32.const 720))) (if (i32.eqz (local.get $orderN)) (then (local.set $orderN (i32.const 720))))
      (call $order_from_rank (local.get $orderN))
      ;; TMP2 debe conservar la suma guardada de las vasijas durante las seis vasijas; se copia a TMP4.
      (call $copy_r (global.get $TMP4) (global.get $TMP2))
      (local.set $pos (i32.const 1))
      (block $sd (loop $sl
        (br_if $sd (i32.gt_u (local.get $pos) (i32.const 6)))
        (local.set $id (call $order_id (local.get $pos)))
        (local.set $prev (call $order_id (call $wrap6 (i32.sub (local.get $pos) (i32.const 1)))))
        (local.set $next (call $order_id (call $wrap6 (i32.add (local.get $pos) (i32.const 1)))))
        (call $copy_r (global.get $TMP2) (call $old_bowl (local.get $id)))
        (call $muladd_small (global.get $TMP2) (call $old_bowl (local.get $prev)) (i32.const 3))
        (call $muladd_small (global.get $TMP2) (call $old_bowl (local.get $next)) (i32.const 5))
        (call $sum_into (global.get $TMP2) (global.get $TMP4))
        (call $r_add_small (global.get $TMP2) (global.get $TMP2) (i32.add (local.get $stir) (i32.mul (local.get $pos) (local.get $pos))))
        (call $r_square (global.get $TMP1) (global.get $TMP2))
        (call $copy_r (global.get $TMP2) (global.get $TMP1))
        (call $r_mul (global.get $TMP3) (call $old_bowl (local.get $prev)) (call $old_bowl (local.get $next)))
        (call $muladd_small (global.get $TMP2) (global.get $TMP3) (i32.const 7))
        (call $copy_r (call $next_bowl (local.get $id)) (global.get $TMP2))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1))) (br $sl)))
      (call $commit_next_bowls)
      (local.set $stir (i32.add (local.get $stir) (i32.const 1))) (br $again))))

  (func $sauce_fixture (param $c i64) (param $t i64)
    (call $init_m)
    (call $build_stones)
    (call $work_counts_fixture (local.get $c) (local.get $t))
    (call $build_hidden)
    (call $build_visible)
    (call $initial_bowls)
    (call $apply_drops)
    (call $post_stir12))

  ;; Siguiente vasija según el orden de la gota 46, usado por askBowl.
  (func $next46 (param $queried i32) (result i32)
    (local $p i32) (local $id i32)
    (local.set $p (i32.const 0))
    (block $found (loop $again
      (br_if $found (i32.ge_u (local.get $p) (i32.const 6)))
      (local.set $id (i32.load (i32.add (global.get $ORDER46) (i32.mul (local.get $p) (i32.const 4)))))
      (if (i32.eq (local.get $id) (local.get $queried))
        (then (return (i32.load (i32.add (global.get $ORDER46) (i32.mul (i32.rem_u (i32.add (local.get $p) (i32.const 1)) (i32.const 6)) (i32.const 4)))))))
      (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $again)))
    unreachable)

  ;; el primer valor se escribe en dstFirst y el resultado devuelto es directionStep.
  (func $ask (param $bowlId i32) (param $seal i32) (param $dstFirst i32) (result i32)
    (local $next i32) (local $parity i32)
    (local.set $next (call $next46 (local.get $bowlId)))
    (call $copy_r (global.get $TMP2) (call $bowl (local.get $bowlId)))
    (call $r_add_small (global.get $TMP2) (global.get $TMP2) (i32.add (local.get $seal) (i32.const 181)))
    (call $r_square (global.get $TMP1) (global.get $TMP2))
    (call $copy_r (global.get $TMP2) (global.get $TMP1))
    (call $muladd_small (global.get $TMP2) (call $bowl (local.get $next)) (i32.const 179))
    (call $r_add_small (local.get $dstFirst) (global.get $TMP2) (local.get $seal))
    (call $copy_r (global.get $TMP2) (local.get $dstFirst))
    (call $r_add_small (global.get $TMP2) (global.get $TMP2) (i32.add (local.get $seal) (i32.const 194)))
    (call $r_square (global.get $TMP1) (global.get $TMP2))
    (call $copy_r (global.get $TMP2) (global.get $TMP1))
    (call $muladd_small (global.get $TMP2) (local.get $dstFirst) (i32.const 193))
    (call $muladd_small (global.get $TMP2) (call $bowl (i32.const 6)) (i32.const 197))
    (local.set $parity (call $r_mod_small (global.get $TMP2) (i32.const 2)))
    (if (result i32) (i32.eq (local.get $parity) (i32.const 1)) (then (i32.const 1)) (else (i32.const -1))))

  ;; -------- Exportaciones de comprobación --------
  (func (export "test_save_m") (result i32)
    (call $init_m)
    (call $save_big (global.get $TMP0) (global.get $M))
    (i32.eq (call $cmp (global.get $TMP0) (global.get $M)) (i32.const 0)))
  (func (export "test_order_rank_1") (result i32)
    (call $order_from_rank (i32.const 1))
    (i32.and (i32.eq (call $order_id (i32.const 1)) (i32.const 1)) (i32.eq (call $order_id (i32.const 6)) (i32.const 6))))
  (func (export "test_order_rank_720") (result i32)
    (call $order_from_rank (i32.const 720))
    (i32.and (i32.eq (call $order_id (i32.const 1)) (i32.const 6)) (i32.eq (call $order_id (i32.const 6)) (i32.const 1))))
  (func (export "fixture_foundation_bowl1_mod1000003") (result i32)
    (call $sauce_fixture (i64.const -15055671) (i64.const -15055671))
    (call $r_mod_small (call $bowl (i32.const 1)) (i32.const 1000003)))
  (func (export "fixture_foundation_order46_first") (result i32)
    (call $sauce_fixture (i64.const -15055671) (i64.const -15055671))
    (i32.load (global.get $ORDER46)))
  (func (export "fixture_foundation_ask1_seal1_mod1000003") (result i32)
    (call $sauce_fixture (i64.const -15055671) (i64.const -15055671))
    (drop (call $ask (i32.const 1) (i32.const 1) (global.get $TMP4)))
    (call $r_mod_small (global.get $TMP4) (i32.const 1000003)))
  (func (export "fixture_foundation_ask1_seal1_direction") (result i32)
    (call $sauce_fixture (i64.const -15055671) (i64.const -15055671))
    (call $ask (i32.const 1) (i32.const 1) (global.get $TMP4)))
)
