function run_stage27_tests()
% PATCH 13: rejection na tym samym answer ring przed biasedLegacyPick.

% Niezmieniony regression Discovery 13 ma po PATCH 13 przejść na GREEN.
run_stage26_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(here, 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root, here)); %#ok<NASGU>

M = pastafari.BigInt('170141183460469231731687303715884105727');
N = pastafari.BigInt(922);
limit = M.floorDiv(N) * N;

% Główny witness: dokładnie jeden reject w kierunku -1.
stream = struct( ...
    'first', limit + pastafari.BigInt(1), ...
    'directionStep', -1);

[patchedRank, acceptedX, offset, patchLimit] = ...
    pastafari.AnswerRingRejectionPatch.apply(stream, N);

assert(patchLimit == limit, ...
    'PATCH 13 wyliczył błędny acceptance limit.');
assert(offset == pastafari.BigInt(1), ...
    'Główny witness powinien wymagać dokładnie jednego rejection.');
assert(acceptedX == limit, ...
    'Po jednym kroku -1 zaakceptowane x powinno być równe limit.');
assert(patchedRank == N, ...
    'Po rejection rank powinien wynosić 922.');

rawX = pastafari.AnswerRingStreamFactory.answerAt( ...
    stream, pastafari.BigInt(0));
rawRank = pastafari.LegacyBiasedPick.pick(rawX, N);
assert(rawRank == pastafari.BigInt(1), ...
    'Surowa blizna Discovery 13 powinna nadal zwracać rank 1.');

ctx = pastafari.MonsterContext(0, 0);
[ctx, actualRank] = pastafari.SmallPickCompatibilityRoute.call( ...
    ctx, stream, N);

assert(actualRank == patchedRank, ...
    'Publikowana trasa PATCH 13 nie zwróciła patched rank.');
assert(ctx.smallPickCandidate == patchedRank, ...
    'Kontekst utracił publikowany patched rank.');
assert(ctx.legacyBiasedPickInput == rawX, ...
    'PATCH 13 utracił surowy input Discovery 13.');
assert(ctx.legacyBiasedPickRank == rawRank, ...
    'PATCH 13 zmienił surowy legacy rank.');

assert(any(strcmp(ctx.branchTrace, ...
    'DISCOVERY_13_BIASED_LEGACY_PICK_MODULO')), ...
    'Brakuje śladu surowej ścieżki Discovery 13.');
assert(any(strcmp(ctx.branchTrace, ...
    'PATCH_13_REJECTION_ON_ANSWER_RING')), ...
    'Brakuje śladu PATCH 13.');

legacyKey = matlab.lang.makeValidName( ...
    'discovery13.biasedLegacyPick.calls');
patchKey = matlab.lang.makeValidName( ...
    'patch13.rejectionOnAnswerRing.calls');
assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
    'Licznik raw biasedLegacyPick jest niepoprawny.');
assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
    'Licznik PATCH 13 jest niepoprawny.');

% Brak rejection: first już należy do accepted prefix.
noReject = struct('first', limit, 'directionStep', -1);
[rank0, x0, offset0, limit0] = ...
    pastafari.AnswerRingRejectionPatch.apply(noReject, N);
assert(limit0 == limit && x0 == limit, ...
    'No-reject control zmienił accepted x lub limit.');
assert(offset0 == pastafari.BigInt(0), ...
    'No-reject control nie powinien przesuwać answer ring.');
assert(rank0 == N, ...
    'No-reject control powinien zwracać rank 922.');

% Wrap tego samego pierścienia: M przy direction +1 odrzuca się,
% a następna odpowiedź jest 1.
wrapStream = struct('first', M, 'directionStep', 1);
[wrapRank, wrapX, wrapOffset, ~] = ...
    pastafari.AnswerRingRejectionPatch.apply(wrapStream, N);
assert(wrapOffset == pastafari.BigInt(1), ...
    'Wrap witness powinien wymagać jednego kroku.');
assert(wrapX == pastafari.BigInt(1), ...
    'Ten sam answer ring powinien zawinąć M -> 1.');
assert(wrapRank == pastafari.BigInt(1), ...
    'Po zawinięciu zaakceptowany rank powinien wynosić 1.');

% Wielokrotne rejection bez restartu strumienia.
multiStream = struct( ...
    'first', limit + pastafari.BigInt(17), ...
    'directionStep', -1);
[multiRank, multiX, multiOffset, ~] = ...
    pastafari.AnswerRingRejectionPatch.apply(multiStream, N);
assert(multiOffset == pastafari.BigInt(17), ...
    'Multi-reject witness powinien wykonać 17 kolejnych kroków.');
assert(multiX == limit, ...
    'Multi-reject witness powinien zakończyć dokładnie na limit.');
assert(multiRank == N, ...
    'Multi-reject witness powinien zwrócić rank 922.');

% Kilka różnych N: patched wynik ma być identyczny z oracle chooseRank.
sizes = [2 3 7 17 922 1000];
for i = 1:numel(sizes)
    candidateN = pastafari.BigInt(sizes(i));
    candidateLimit = M.floorDiv(candidateN) * candidateN;

    if candidateLimit < M
        candidateStream = struct( ...
            'first', candidateLimit + pastafari.BigInt(1), ...
            'directionStep', -1);
    else
        candidateStream = struct( ...
            'first', candidateLimit, ...
            'directionStep', -1);
    end

    expected = normative_oracle( ...
        'chooseRank', candidateStream, candidateN);
    [actual, ~, ~, ~] = ...
        pastafari.AnswerRingRejectionPatch.apply( ...
            candidateStream, candidateN);

    assert(actual == expected, ...
        ['PATCH 13 rozchodzi się z oracle dla N=', ...
         num2str(sizes(i)), '.']);
end

% Legacy picker pozostaje fizycznie tym samym modulo mapperem.
assert(pastafari.LegacyBiasedPick.pick( ...
    limit + pastafari.BigInt(1), N) == pastafari.BigInt(1), ...
    'LegacyBiasedPick został zmieniony przez PATCH 13.');

fprintf('STAGE_27_PATCH_13_GREEN\n');
end

function cleanupPaths(root, here)
rmpath(fullfile(root, 'src'));
rmpath(fullfile(here, 'oracle'));
end
