function run_stage12_tests()
% DISCOVERY 06: legacyPrior nie rozumie slotów 0..-6.
% Surowa blizna ma pozostać także po PATCH 06, ale publikowane visible
% mają wtedy przejść na GREEN.

run_stage11_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(here, 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root, here)); %#ok<NASGU>

foundation = pastafari.BigInt('-15055671');
counts = normative_oracle('workCounts', foundation, foundation);
stones = normative_oracle('stones');
hidden = referenceHiddenDrops(counts, stones);
expected = referenceVisibleDrops(counts, stones, hidden);

% Sama historyczna funkcja nie może nagle nauczyć się slotów ujemnych.
probeVisible = {pastafari.BigInt(123)};
[~, found0, slot0] = pastafari.LegacyPriorAdapter.legacyPrior( ...
    probeVisible, 1, 1);
[~, foundNeg, slotNeg] = pastafari.LegacyPriorAdapter.legacyPrior( ...
    probeVisible, 1, 7);
assert(~found0 && slot0 == 0, ...
    'legacyPrior musi nadal nie znajdować slotu 0.');
assert(~foundNeg && slotNeg == -6, ...
    'legacyPrior musi nadal nie znajdować slotu -6.');

ctx = pastafari.MonsterContext(foundation, foundation);
[ctx, actual] = pastafari.VisibleDropCompatibilityRoute.call( ...
    ctx, counts, stones, hidden);

expectedSlots = [ ...
     0 -2 -6; ...
     1 -1 -5; ...
     2  0 -4; ...
     3  1 -3; ...
     4  2 -2; ...
     5  3 -1; ...
     6  4  0; ...
     7  5  1];

expectedMissing = logical([ ...
    1 1 1; ...
    0 1 1; ...
    0 1 1; ...
    0 0 1; ...
    0 0 1; ...
    0 0 1; ...
    0 0 1; ...
    0 0 0]);

assert(isequal(ctx.legacyPriorRequestedSlots(1:8, :), expectedSlots), ...
    'Discovery 06 zapisało nieoczekiwane sloty poprzedników dla kropli 1..8.');
assert(isequal(ctx.legacyPriorMissingMatrix(1:8, :), expectedMissing), ...
    'Discovery 06 ma nie znajdować pełnej historii dokładnie w kroplach 1..7.');

% Pełna surowa ścieżka legacy pozostaje historyczną blizną także po patchu.
legacyDivergentFirst7 = false(1, 7);
for i = 1:7
    legacyDivergentFirst7(i) = ctx.legacyVisibleDrops{i} ~= expected{i};
end
assert(all(legacyDivergentFirst7), ...
    'Surowa ścieżka legacyPrior musi rozchodzić się w każdej z kropli 1..7.');

divergent = false(1, 46);
for i = 1:46
    divergent(i) = actual{i} ~= expected{i};
    if i <= 8
        fprintf(['STAGE12 DISCOVERY06 DROP=%d ACTUAL=%s EXPECTED=%s ', ...
            'MISSING=[%d %d %d] CLASSIFICATION=%s\n'], ...
            i, char(actual{i}), char(expected{i}), ...
            ctx.legacyPriorMissingMatrix(i, 1), ...
            ctx.legacyPriorMissingMatrix(i, 2), ...
            ctx.legacyPriorMissingMatrix(i, 3), ...
            classification(divergent(i)));
    end
end

assert(any(ctx.legacyPriorMissingMatrix(1:7, :), 'all'), ...
    'Krople 1..7 powinny ujawnić brak pełnej historii legacyPrior.');
assert(~any(ctx.legacyPriorMissingMatrix(8, :)), ...
    'Kropla 8 nie powinna już wymagać slotu 0 ani ujemnego.');

assert(any(strcmp(ctx.branchTrace, 'DISCOVERY_06_LEGACY_PRIOR')), ...
    'Brakuje śladu Discovery 06.');
metricKey = matlab.lang.makeValidName('discovery06.legacyPrior.calls');
assert(isfield(ctx.metrics, metricKey) && ctx.metrics.(metricKey) == 1, ...
    'Licznik legacyPrior jest niepoprawny.');

caught = false;
try
    calendarDateSpaghetti(foundation, foundation);
catch err
    caught = strcmp(err.identifier, 'Pastafari:Bootstrap:NotImplementedYet');
end
assert(caught, ...
    'Publiczna trasa nie zachowała kontrolowanej granicy etapu 12.');

if any(divergent)
    assert(all(divergent(1:7)), ...
        'W stanie Discovery 06 każda z kropli 1..7 ma ujawnić rozbieżność.');
    fprintf('STAGE_12_DISCOVERY_06_EXPECTED_RED\n');
    error('Pastafari:Discovery06:LegacyPriorMissingHistory', ...
        ['Oczekiwana rozbieżność Discovery 06: legacyPrior nie mapuje ', ...
         'slotów 0..-6 na siedem hidden.']);
end

fprintf('STAGE_12_DISCOVERY_06_REGRESSION_GREEN\n');
end

function hidden = referenceHiddenDrops(counts, stones)
coeff = [ ...
    3 4 6 8; ...
    5 7 10 12; ...
    7 10 14 16; ...
    9 13 18 20; ...
    11 16 22 24; ...
    13 19 26 28; ...
    15 22 30 32];
grindStone = [1 2 3 4 5 1 2];
hidden = cell(1, 7);

for k = 1:7
    row = coeff(k, :);
    x = counts.action + ...
        pastafari.BigInt(row(1)) * counts.target + ...
        pastafari.BigInt(row(2)) * counts.distance + ...
        pastafari.BigInt(row(3)) * counts.connection + ...
        pastafari.BigInt(row(4)) * pastafari.BigInt(counts.direction);

    for kind = 1:5
        x = x + stones{k, kind};
    end
    x = saveReference(x);

    for grind = 1:7
        oldX = x;
        x = saveReference( ...
            oldX.square() + pastafari.BigInt(3) * oldX + ...
            stones{k, grindStone(grind)} + pastafari.BigInt(grind));
    end
    hidden{k} = x;
end
end

function visible = referenceVisibleDrops(counts, stones, hidden)
timeline = cell(1, 53);
for k = 1:7
    timeline{8 - k} = hidden{k};
end

visible = cell(1, 46);
grinds = [ ...
    3 5 7 11 1; ...
    5 7 11 13 2; ...
    7 11 13 17 3; ...
    11 13 17 19 4; ...
    13 17 19 23 5; ...
    17 19 23 29 1; ...
    19 23 29 31 2; ...
    23 29 31 37 3; ...
    29 31 37 41 4; ...
    31 37 41 43 5; ...
    37 41 43 47 1];

for i = 1:46
    p1 = timeline{i + 6};
    p3 = timeline{i + 4};
    p7 = timeline{i};

    x = saveReference( ...
        stones{i, 1} * counts.action + ...
        stones{i, 2} * counts.target + ...
        stones{i, 3} * counts.distance + ...
        stones{i, 4} * counts.connection + ...
        stones{i, 5} * pastafari.BigInt(counts.direction) + ...
        p1 + pastafari.BigInt(3) * p3 + ...
        pastafari.BigInt(5) * p7 + pastafari.BigInt(i));

    for grind = 1:11
        oldX = x;
        row = grinds(grind, :);
        x = saveReference( ...
            oldX.square() + pastafari.BigInt(row(1)) * oldX + ...
            pastafari.BigInt(row(2)) * p1 + ...
            pastafari.BigInt(row(3)) * p3 + ...
            pastafari.BigInt(row(4)) * p7 + ...
            stones{i, row(5)});
    end

    visible{i} = x;
    timeline{i + 7} = x;
end
end

function value = saveReference(x)
M = pastafari.BigInt('170141183460469231731687303715884105727');
value = pastafari.BigInt(1) + ...
    (pastafari.BigInt.coerce(x) - pastafari.BigInt(1)).regularMod(M);
end

function text = classification(isDivergent)
if isDivergent
    text = 'EXPECTED_RED';
else
    text = 'MATCH';
end
end

function cleanupPaths(root, here)
rmpath(fullfile(root, 'src'));
rmpath(fullfile(here, 'oracle'));
end
