function run_stage53_tests()
% PATCH 26: raw [open,close] ghost zostaje, semantic year używa (open,close].

% Niezmieniony regression Discovery 26 ma po PATCH 26 przejść na GREEN.
run_stage52_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

years = syntheticYears();

% 1. Główny opening-gate witness: anchor po prawej, target na wspólnej granicy.
anchor = years{4}; % year 12: (100,200]
target = pastafari.BigInt(100);

[legacy, legacyTelemetry] = ...
    pastafari.LegacyClosedOpeningYearResolver.apply( ...
        anchor, target, years);
[patched, patchTelemetry] = ...
    pastafari.OpenClosedYearIntervalPatch.apply( ...
        anchor, target, years);

assert(legacy.number == pastafari.BigInt(12), ...
    'Fizyczny legacy ghost powinien nadal zwracać year 12.');
assert(legacyTelemetry.backwardSteps == 0, ...
    'Fizyczny legacy ghost powinien nadal mieć zero backward steps.');
assert(patched.number == pastafari.BigInt(11), ...
    'PATCH 26 powinien przypisać opening gate 100 do year 11.');
assert(patchTelemetry.backwardSteps == 1, ...
    'PATCH 26 powinien wykonać jeden krok wstecz dla target==open.');
assert(patchTelemetry.finalOpenDay == pastafari.BigInt(0) && ...
       patchTelemetry.finalCloseDay == pastafari.BigInt(100), ...
    'PATCH 26 zakończył się na błędnym przedziale dla target 100.');

% 2. Closing gate pozostaje domknięty.
[closingYear, closingTelemetry] = ...
    pastafari.OpenClosedYearIntervalPatch.apply( ...
        anchor, pastafari.BigInt(200), years);

assert(closingYear.number == pastafari.BigInt(12), ...
    'Closing gate 200 musi pozostać w year 12.');
assert(closingTelemetry.backwardSteps == 0 && ...
       closingTelemetry.forwardSteps == 0, ...
    'Closing gate anchor year nie powinien wymagać spaceru.');

% 3. Kolejna wspólna granica: 200 należy do year 11, nie year 12.
[secondBoundary, secondTelemetry] = ...
    pastafari.OpenClosedYearIntervalPatch.apply( ...
        years{5}, pastafari.BigInt(200), years);

assert(secondBoundary.number == pastafari.BigInt(12), ...
    'Opening gate 200 year 13 musi należeć do year 12.');
assert(secondTelemetry.backwardSteps == 1, ...
    'Opening gate 200 powinien wykonać jeden backward step.');

% 4. Wielokrokowy spacer wstecz dla opening gate.
[farBack, farBackTelemetry] = ...
    pastafari.OpenClosedYearIntervalPatch.apply( ...
        years{6}, pastafari.BigInt(100), years);

assert(farBack.number == pastafari.BigInt(11), ...
    'Far-back target 100 powinien zakończyć się w year 11.');
assert(farBackTelemetry.backwardSteps == 3, ...
    'Far-back opening witness powinien wykonać trzy backward steps.');
assert(farBackTelemetry.forwardSteps == 0, ...
    'Far-back witness nie powinien wykonywać forward steps.');

% 5. Wielokrokowy spacer wprzód i domknięcie close.
[farForward, farForwardTelemetry] = ...
    pastafari.OpenClosedYearIntervalPatch.apply( ...
        years{3}, pastafari.BigInt(400), years);

assert(farForward.number == pastafari.BigInt(14), ...
    'Target 400 powinien należeć do year 14.');
assert(farForwardTelemetry.forwardSteps == 3, ...
    'Far-forward witness powinien wykonać trzy forward steps.');
assert(farForwardTelemetry.backwardSteps == 0, ...
    'Far-forward witness nie powinien wykonywać backward steps.');

% 6. Cały kontrolowany zakres jest zgodny z test-only (open,close].
targets = [ ...
    -99, -1, 0, 1, 99, 100, 101, 199, 200, ...
    201, 299, 300, 301, 399, 400];

for k = 1:numel(targets)
    targetDay = pastafari.BigInt(targets(k));
    normative = normativeYearTestOnly(years, targetDay);

    [actual, telemetry] = ...
        pastafari.OpenClosedYearIntervalPatch.apply( ...
            years{4}, targetDay, years);

    assert(actual.number == normative.number, ...
        ['PATCH 26 różni się od (open,close] dla target ', ...
         num2str(targets(k)), '.']);
    assert(pastafari.BigInt.coerce(actual.openGateDay) < targetDay && ...
           targetDay <= pastafari.BigInt.coerce(actual.closeGateDay), ...
        'PATCH 26 opublikował rok niespełniający (open,close].');
    assert(strcmp(telemetry.interval, '(open,close]'), ...
        'PATCH 26 telemetry utraciła interval marker.');
end

% 7. Produkcyjna route zachowuje raw scar i publikuje corrected year.
ctx = pastafari.MonsterContext(0, 0);
[ctx, actual] = ...
    pastafari.YearIntervalCompatibilityRoute.call( ...
        ctx, anchor, pastafari.BigInt(100), years);

assert(actual.number == pastafari.BigInt(11), ...
    'Produkcyjna route powinna publikować year 11.');
assert(ctx.yearIntervalCandidate.number == pastafari.BigInt(11), ...
    'Kontekst utracił semantic year 11.');

assert(ctx.legacyClosedOpeningYearNumber == pastafari.BigInt(12), ...
    'PATCH 26 musi zachować raw legacy year 12.');
assert(ctx.legacyClosedOpeningOpenDay == pastafari.BigInt(100), ...
    'PATCH 26 musi zachować raw legacy open 100.');
assert(ctx.legacyClosedOpeningCloseDay == pastafari.BigInt(200), ...
    'PATCH 26 musi zachować raw legacy close 200.');
assert(ctx.legacyClosedOpeningBackwardSteps == 0, ...
    'PATCH 26 musi zachować raw zero backward steps.');
assert(ctx.legacyClosedOpeningForwardSteps == 0, ...
    'PATCH 26 musi zachować raw zero forward steps.');
assert(ctx.legacyClosedOpeningYearCandidate.number == ...
    pastafari.BigInt(12), ...
    'PATCH 26 musi zachować pełny raw legacy candidate.');

assert(any(strcmp(ctx.branchTrace, ...
    'DISCOVERY_26_CLOSED_OPENING_GATE')), ...
    'Brakuje raw Discovery 26 trace.');
assert(any(strcmp(ctx.branchTrace, ...
    'PATCH_26_OPEN_CLOSED_INTERVAL')), ...
    'Brakuje PATCH 26 trace.');

legacyKey = matlab.lang.makeValidName( ...
    'discovery26.closedOpeningGate.calls');
patchKey = matlab.lang.makeValidName( ...
    'patch26.openClosedInterval.calls');

assert(isfield(ctx.metrics, legacyKey) && ...
       ctx.metrics.(legacyKey) == 1, ...
    'Raw Discovery 26 metric jest błędny.');
assert(isfield(ctx.metrics, patchKey) && ...
       ctx.metrics.(patchKey) == 1, ...
    'PATCH 26 metric jest błędny.');

% 8. Fizyczny legacy resolver pozostaje błędny na opening gate.
[legacyAgain, legacyAgainTelemetry] = ...
    pastafari.LegacyClosedOpeningYearResolver.apply( ...
        anchor, pastafari.BigInt(100), years);

assert(legacyAgain.number == pastafari.BigInt(12), ...
    'LegacyClosedOpeningYearResolver został cicho naprawiony.');
assert(legacyAgainTelemetry.backwardSteps == 0, ...
    'LegacyClosedOpeningYearResolver utracił historyczny scar.');

fprintf('STAGE_53_PATCH_26_GREEN\n');
end

function years = syntheticYears()
years = { ...
    struct( ...
        'number', pastafari.BigInt(9), ...
        'openGateDay', pastafari.BigInt(-200), ...
        'closeGateDay', pastafari.BigInt(-100)), ...
    struct( ...
        'number', pastafari.BigInt(10), ...
        'openGateDay', pastafari.BigInt(-100), ...
        'closeGateDay', pastafari.BigInt(0)), ...
    struct( ...
        'number', pastafari.BigInt(11), ...
        'openGateDay', pastafari.BigInt(0), ...
        'closeGateDay', pastafari.BigInt(100)), ...
    struct( ...
        'number', pastafari.BigInt(12), ...
        'openGateDay', pastafari.BigInt(100), ...
        'closeGateDay', pastafari.BigInt(200)), ...
    struct( ...
        'number', pastafari.BigInt(13), ...
        'openGateDay', pastafari.BigInt(200), ...
        'closeGateDay', pastafari.BigInt(300)), ...
    struct( ...
        'number', pastafari.BigInt(14), ...
        'openGateDay', pastafari.BigInt(300), ...
        'closeGateDay', pastafari.BigInt(400))};
end

function year = normativeYearTestOnly(years, targetDay)
target = pastafari.BigInt.coerce(targetDay);
matches = {};

for k = 1:numel(years)
    openDay = pastafari.BigInt.coerce(years{k}.openGateDay);
    closeDay = pastafari.BigInt.coerce(years{k}.closeGateDay);

    if openDay < target && target <= closeDay
        matches{end + 1} = years{k}; %#ok<AGROW>
    end
end

if numel(matches) ~= 1
    error('Pastafari:Stage53:NormativeFixture', ...
        'Test-only (open,close] resolver oczekiwał dokładnie jednego roku.');
end

year = matches{1};
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'src'));
end
