function run_stage29_tests()
% PATCH 14: wide detour dla N>M z zachowaniem raw short-only scar.

% Niezmieniony regression Discovery 14 ma po PATCH 14 przejść na GREEN.
run_stage28_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(here, 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root, here)); %#ok<NASGU>

M = pastafari.BigInt('170141183460469231731687303715884105727');

stream = struct('first', pastafari.BigInt(1), 'directionStep', 1);
witnesses = { ...
    M + pastafari.BigInt(1), ...
    M * M, ...
    M * M * M};
expectedPlaces = [2 2 3];

for k = 1:numel(witnesses)
    N = witnesses{k};
    expected = normative_oracle('chooseRank', stream, N);

    [direct, wide, acceptedWide, places, space, limit, rejectionSteps] = ...
        pastafari.WideSelectionDetourPatch.apply(stream, N);

    assert(direct == expected, ...
        ['WideSelectionDetourPatch rozchodzi się z oracle, case ', ...
         num2str(k), '.']);
    assert(places == expectedPlaces(k), ...
        ['Niepoprawna minimalna liczba places, case ', num2str(k), '.']);
    assert(space >= N, ...
        'space musi pokrywać cały zakres N.');
    if places > 1
        assert(space.floorDiv(M) < N, ...
            'places nie jest minimalne.');
    end
    assert(acceptedWide <= limit, ...
        'Końcowe wide musi należeć do accepted prefix.');
    assert(rejectionSteps >= pastafari.BigInt(0), ...
        'Liczba rejection nie może być ujemna.');
    assert(wide >= pastafari.BigInt(1) && wide <= space, ...
        'Początkowe wide musi należeć do przestrzeni 1..space.');

    ctx = pastafari.MonsterContext(0, 0);
    [ctx, actual] = ...
        pastafari.GeneralSelectionCompatibilityRoute.call( ...
            ctx, stream, N);

    assert(actual == expected, ...
        ['General route rozchodzi się z oracle, case ', num2str(k), '.']);
    assert(ctx.generalSelectionCandidate == expected, ...
        'Kontekst utracił publikowany wide rank.');

    assert(ctx.legacyShortOnlyAssumed, ...
        'PATCH 14 utracił raw short-only assumption.');
    assert(ctx.legacyGeneralSelectionRequestedSize == N, ...
        'PATCH 14 utracił raw requested N.');
    assert(ctx.legacyWideSelectionUnsupported, ...
        'PATCH 14 usunął raw wide-unsupported scar.');
    assert(strcmp(ctx.legacyWideSelectionError, ...
        'Pastafari:Selection:LegacyShortAssumption'), ...
        'PATCH 14 zmienił raw legacy error.');
    assert(isempty(ctx.legacyGeneralSelectionResult), ...
        'PATCH 14 nie może wypełniać raw legacy wide result.');

    assert(any(strcmp(ctx.branchTrace, ...
        'DISCOVERY_14_SHORT_ONLY_SELECTOR')), ...
        'Brakuje śladu historycznego Discovery 14.');
    assert(any(strcmp(ctx.branchTrace, ...
        'PATCH_14_WIDE_DETOUR')), ...
        'Brakuje śladu PATCH 14 wide detour.');

    legacyKey = matlab.lang.makeValidName( ...
        'discovery14.shortOnlySelector.calls');
    patchKey = matlab.lang.makeValidName( ...
        'patch14.wideDetour.calls');
    assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
        'Licznik raw short-only selector jest niepoprawny.');
    assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
        'Licznik wide detour jest niepoprawny.');
end

% Short selection musi pozostać dokładnie ścieżką PATCH 13.
shortSizes = [1 2 7 922];
for k = 1:numel(shortSizes)
    N = pastafari.BigInt(shortSizes(k));
    expected = normative_oracle('chooseRank', stream, N);

    ctx = pastafari.MonsterContext(0, 0);
    [ctx, actual] = ...
        pastafari.GeneralSelectionCompatibilityRoute.call( ...
            ctx, stream, N);

    assert(actual == expected, ...
        ['Short passthrough rozchodzi się z oracle dla N=', ...
         num2str(shortSizes(k)), '.']);
    assert(~ctx.legacyWideSelectionUnsupported, ...
        'Short passthrough nie może wyglądać jak wide failure.');
    assert(~isempty(ctx.legacyGeneralSelectionResult), ...
        'Short passthrough musi zachować raw short result.');
    assert(any(strcmp(ctx.branchTrace, ...
        'PATCH_13_REJECTION_ON_ANSWER_RING')), ...
        'Short passthrough musi nadal używać PATCH 13.');
    assert(any(strcmp(ctx.branchTrace, ...
        'PATCH_14_WIDE_DETOUR_SHORT_PASSTHROUGH')), ...
        'Brakuje śladu short passthrough PATCH 14.');
end

% Dokładny wide-rejection witness.
% first=M, direction=-1 daje:
% digit0=M-1, digit1=M-2,
% wide = 1 + (M-1) + (M-2)*M = M^2-M.
% Dla N=M^2-M-1 otrzymujemy wide=N+1 i acceptanceLimit=N,
% więc następuje dokładnie jeden krok w szerokim pierścieniu.
rejectStream = struct('first', M, 'directionStep', -1);
Nreject = M * M - M - pastafari.BigInt(1);
expectedReject = normative_oracle('chooseRank', rejectStream, Nreject);

[actualReject, wideReject, acceptedReject, placesReject, ...
    spaceReject, limitReject, stepsReject] = ...
    pastafari.WideSelectionDetourPatch.apply(rejectStream, Nreject);

assert(placesReject == 2, ...
    'Wide rejection witness powinien używać dwóch places.');
assert(spaceReject == M * M, ...
    'Wide rejection witness ma błędną przestrzeń M^2.');
assert(wideReject == Nreject + pastafari.BigInt(1), ...
    'Wide rejection witness powinien zaczynać dokładnie na N+1.');
assert(limitReject == Nreject, ...
    'Dla tego witness acceptanceLimit powinien być równy N.');
assert(stepsReject == pastafari.BigInt(1), ...
    'Wide rejection witness powinien wykonać dokładnie jeden krok.');
assert(acceptedReject == Nreject, ...
    'Po jednym kroku acceptedWide powinien być równy N.');
assert(actualReject == expectedReject && actualReject == Nreject, ...
    'Wide rejection witness rozchodzi się z oracle.');

fprintf('STAGE_29_PATCH_14_GREEN\n');
end

function cleanupPaths(root, here)
rmpath(fullfile(root, 'src'));
rmpath(fullfile(here, 'oracle'));
end
