function run_stage51_tests()
% PATCH 25: zachowaj contiguous ghost, publikuj prefix occurrence count.

% Niezmieniony regression Discovery 25 ma po PATCH 25 przejść na GREEN.
run_stage50_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

lengths = [4 4 4];
family = pastafari.WholeMonthWeavingFamily(lengths);
weaving = family.itemAt1(pastafari.BigInt(396));
expectedWeaving = [1 1 2 3 2 1 3 2 1 2 3 3];

assert(isequal(weaving, expectedWeaving), ...
    'Stage 51 witness musi używać exact Stage 49 whole weave.');

yearOpenDay = pastafari.BigInt(1000);
expectedOccurrences = [1 2 1 1 2 3 2 3 4 4 3 4];

for position = 1:numel(weaving)
    targetDay = yearOpenDay + pastafari.BigInt(position);

    legacyGhost = pastafari.LegacyContiguousMonthDay.compute( ...
        weaving, yearOpenDay, targetDay);
    expected = pastafari.BigInt(expectedOccurrences(position));

    ctx = pastafari.MonsterContext(0, 0);
    [ctx, monthId, actual] = ...
        pastafari.MonthDayCompatibilityRoute.call( ...
            ctx, weaving, yearOpenDay, targetDay);

    assert(monthId == weaving(position), ...
        ['PATCH 25 zmienił month id przy position ', ...
         num2str(position), '.']);
    assert(actual == expected, ...
        ['PATCH 25 ma błędny occurrence day przy position ', ...
         num2str(position), '.']);
    assert(ctx.dayInMonthCandidate == expected, ...
        'Kontekst utracił semantic occurrence day.');
    assert(ctx.monthAtTargetCandidate == weaving(position), ...
        'Kontekst utracił semantic month id.');

    assert(ctx.legacyContiguousMonthId == legacyGhost.monthId, ...
        'PATCH 25 zmienił legacy month id.');
    assert(ctx.legacyContiguousMonthFirstPosition1 == ...
        legacyGhost.firstPosition1, ...
        'PATCH 25 zmienił legacy first position.');
    assert(ctx.legacyContiguousMonthFirstDay == legacyGhost.firstDay, ...
        'PATCH 25 zmienił legacy first day.');
    assert(ctx.legacyContiguousDayInMonth == legacyGhost.dayInMonth, ...
        'PATCH 25 zmienił legacy contiguous dayInMonth.');

    assert(any(strcmp(ctx.branchTrace, ...
        'DISCOVERY_25_CONTIGUOUS_MONTH_DAY')), ...
        'Brakuje raw Discovery 25 trace.');
    assert(any(strcmp(ctx.branchTrace, ...
        'PATCH_25_OCCURRENCE_COUNT')), ...
        'Brakuje PATCH 25 trace.');

    legacyKey = matlab.lang.makeValidName( ...
        'discovery25.contiguousMonthDay.calls');
    patchKey = matlab.lang.makeValidName( ...
        'patch25.occurrenceCount.calls');

    assert(isfield(ctx.metrics, legacyKey) && ...
           ctx.metrics.(legacyKey) == 1, ...
        'Raw Discovery 25 metric jest błędny.');
    assert(isfield(ctx.metrics, patchKey) && ...
           ctx.metrics.(patchKey) == 1, ...
        'PATCH 25 metric jest błędny.');
end

mainGhost = pastafari.LegacyContiguousMonthDay.compute( ...
    weaving, yearOpenDay, pastafari.BigInt(1009));
[mainCorrect, mainReused] = ...
    pastafari.MonthDayOccurrencePatchWrapper.apply( ...
        weaving, mainGhost);

assert(mainGhost.monthId == 1, ...
    'Główny witness powinien należeć do month 1.');
assert(mainGhost.dayInMonth == pastafari.BigInt(9), ...
    'Główny legacy scar powinien pozostać równy 9.');
assert(mainCorrect == pastafari.BigInt(4), ...
    'Główny occurrence result powinien wynosić 4.');
assert(~mainReused, ...
    'Rozdzielony główny witness nie może reuse legacy day=9.');

prefixGhost = pastafari.LegacyContiguousMonthDay.compute( ...
    weaving, yearOpenDay, pastafari.BigInt(1006));
[prefixCorrect, prefixReused] = ...
    pastafari.MonthDayOccurrencePatchWrapper.apply( ...
        weaving, prefixGhost);

assert(prefixGhost.monthId == 1, ...
    'Position 6 powinno należeć do month 1.');
assert(prefixCorrect == pastafari.BigInt(3), ...
    'Do position 6 month 1 wystąpił dokładnie trzy razy.');
assert(sum(weaving == 1) == 4, ...
    'Control wymaga czterech łącznych wystąpień month 1.');
assert(~prefixReused, ...
    'Position 6 nie może reuse legacy contiguous result.');

reuseGhost = pastafari.LegacyContiguousMonthDay.compute( ...
    weaving, yearOpenDay, pastafari.BigInt(1002));
[reuseCorrect, reused] = ...
    pastafari.MonthDayOccurrencePatchWrapper.apply( ...
        weaving, reuseGhost);

assert(reuseGhost.dayInMonth == pastafari.BigInt(2) && ...
       reuseCorrect == pastafari.BigInt(2), ...
    'Control position 2 powinno mieć dayInMonth=2.');
assert(reused, ...
    'Jeżeli legacy day jest już równy occurrence count, reuse flag ma być true.');

legacyAgain = pastafari.LegacyContiguousMonthDay.compute( ...
    weaving, yearOpenDay, pastafari.BigInt(1009));
assert(legacyAgain.dayInMonth == pastafari.BigInt(9), ...
    'LegacyContiguousMonthDay został cicho naprawiony przez PATCH 25.');

fprintf('STAGE_51_PATCH_25_GREEN\n');
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'src'));
end
