function run_stage07_tests()
% PATCH 03: zachowaj oldDistance, zastąp go chronologicznym abs(t-c)+1.

% Niezmieniony regression Discovery 03 musi po nałożeniu patcha stać się zielony.
run_stage06_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(here, 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root, here)); %#ok<NASGU>

foundation = pastafari.BigInt('-15055671');

cases = { ...
    foundation,      foundation; ...
    foundation,      foundation + 3; ...
    foundation - 1,  foundation; ...
    foundation - 3,  foundation + 3; ...
    foundation,      foundation + 1; ...
    foundation + 9,  foundation + 2; ...
    foundation - 12, foundation - 4};
labels = { ...
    'SAME_DAY', ...
    'FOUNDATION_TO_PLUS_3', ...
    'MINUS_1_TO_FOUNDATION', ...
    'CROSS_MINUS_3_PLUS_3', ...
    'FOUNDATION_TO_PLUS_1', ...
    'BACKWARD_AFTER_FOUNDATION', ...
    'FORWARD_BEFORE_FOUNDATION'};

for k = 1:size(cases, 1)
    c = cases{k, 1};
    t = cases{k, 2};

    rawLegacy = pastafari.LegacyDistanceAdapter.oldDistance(c, t);
    patchedDirect = pastafari.ChronologicalDistancePatch.apply(c, t, rawLegacy);
    expectedDistance = abs(t - c) + pastafari.BigInt(1);

    assert(patchedDirect == expectedDistance, ...
        ['PATCH 03 nie zwrócił abs(t-c)+1 dla przypadku ', labels{k}, '.']);

    ctx = pastafari.MonsterContext(c, t);
    [ctx, counts] = pastafari.WorkCountsCompatibilityRoute.call(ctx, c, t);
    normative = normative_oracle('workCounts', c, t);

    assert(ctx.legacyDistanceValue == rawLegacy, ...
        ['Trasa utraciła historyczny oldDistance dla przypadku ', labels{k}, '.']);
    assert(ctx.distanceCandidate == expectedDistance, ...
        ['Kontekst nie zachował poprawionego distance dla przypadku ', labels{k}, '.']);
    assert(counts.distance == normative.distance, ...
        ['Distance po PATCH 03 jest niepoprawne dla przypadku ', labels{k}, '.']);
    assert(counts.direction == normative.direction, ...
        ['Direction jest niepoprawne dla przypadku ', labels{k}, '.']);
    assert(counts.connection == normative.connection, ...
        ['Connection jest niepoprawne dla przypadku ', labels{k}, '.']);
    assert(counts.action == normative.action && counts.target == normative.target, ...
        ['Action lub target jest niepoprawne dla przypadku ', labels{k}, '.']);

    assert(any(strcmp(ctx.branchTrace, 'DISCOVERY_03_OLD_DISTANCE')), ...
        ['Brakuje śladu historycznego oldDistance dla przypadku ', labels{k}, '.']);
    assert(any(strcmp(ctx.branchTrace, 'PATCH_03_CHRONOLOGICAL_DISTANCE')), ...
        ['Brakuje śladu PATCH 03 dla przypadku ', labels{k}, '.']);

    legacyKey = matlab.lang.makeValidName('discovery03.oldDistance.calls');
    patchKey = matlab.lang.makeValidName('patch03.chronologicalDistance.calls');
    assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
        ['Licznik oldDistance jest niepoprawny dla przypadku ', labels{k}, '.']);
    assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
        ['Licznik PATCH 03 jest niepoprawny dla przypadku ', labels{k}, '.']);
end

% Najważniejsza granica: ten sam dzień musi mieć dystans 1.
same = pastafari.BigInt('9876543210123456789');
rawSame = pastafari.LegacyDistanceAdapter.oldDistance(same, same);
assert(rawSame == pastafari.BigInt(0), ...
    'Historyczny oldDistance dla tego samego dnia musi pozostać równy 0.');
assert(pastafari.ChronologicalDistancePatch.apply(same, same, rawSame) == pastafari.BigInt(1), ...
    'PATCH 03 musi mapować ten sam dzień na dystans 1.');

fprintf('STAGE_07_PATCH_03_GREEN\n');
end

function cleanupPaths(root, here)
rmpath(fullfile(root, 'src'));
rmpath(fullfile(here, 'oracle'));
end
