function run_stage52_tests()
% DISCOVERY 26: historyczne [open,close] przypisuje opening gate do
% niewłaściwego roku.
%
% Po PATCH 26 ten sam regression ma zachować raw ghost, ale publikować rok
% według (open,close].

run_stage51_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

years = syntheticYears();
anchor = years{2};

% 1. Opening gate bieżącego roku: legacy zatrzymuje się za wcześnie.
[legacyOpen, openTelemetry] = ...
    pastafari.LegacyClosedOpeningYearResolver.apply( ...
        anchor, pastafari.BigInt(100), years);

assert(legacyOpen.number == pastafari.BigInt(11), ...
    'Legacy [open,close] powinno błędnie przypisać open=100 do year 11.');
assert(openTelemetry.backwardSteps == 0, ...
    'Historyczna wada polega właśnie na braku kroku wstecz dla target==open.');
assert(openTelemetry.finalOpenDay == pastafari.BigInt(100) && ...
       openTelemetry.finalCloseDay == pastafari.BigInt(200), ...
    'Legacy opening witness ma błędny końcowy przedział.');

normativeOpen = normativeYearTestOnly(years, pastafari.BigInt(100));
assert(normativeOpen.number == pastafari.BigInt(10), ...
    'Normatywne (open,close] powinno przypisać day 100 do year 10.');

% 2. Closing gate bieżącego roku jest już poprawny.
[legacyClose, closeTelemetry] = ...
    pastafari.LegacyClosedOpeningYearResolver.apply( ...
        anchor, pastafari.BigInt(200), years); %#ok<ASGLU>
normativeClose = normativeYearTestOnly(years, pastafari.BigInt(200));

assert(legacyClose.number == pastafari.BigInt(11), ...
    'Closing gate 200 powinien pozostać w year 11.');
assert(normativeClose.number == pastafari.BigInt(11), ...
    'Normatywne (open,close] również przypisuje close=200 do year 11.');

% 3. Punkty wewnętrzne oraz zwykły forward/backward walk.
targets = [99 101 199 201 300];
expectedLegacy = [10 11 11 12 12];
expectedNormative = [10 11 11 12 12];

for k = 1:numel(targets)
    target = pastafari.BigInt(targets(k));
    [legacyYear, ~] = ...
        pastafari.LegacyClosedOpeningYearResolver.apply( ...
            anchor, target, years);
    normativeYear = normativeYearTestOnly(years, target);

    assert(legacyYear.number == pastafari.BigInt(expectedLegacy(k)), ...
        ['Legacy resolver ma błędny wynik dla target ', ...
         num2str(targets(k)), '.']);
    assert(normativeYear.number == pastafari.BigInt(expectedNormative(k)), ...
        ['Normative test-only resolver ma błędny wynik dla target ', ...
         num2str(targets(k)), '.']);
end

% 4. Każda wspólna granica ujawnia tę samą wadę, jeśli anchor jest po prawej.
[secondOpeningGhost, ~] = ...
    pastafari.LegacyClosedOpeningYearResolver.apply( ...
        years{3}, pastafari.BigInt(200), years);
secondOpeningNormative = ...
    normativeYearTestOnly(years, pastafari.BigInt(200));

assert(secondOpeningGhost.number == pastafari.BigInt(12), ...
    'Legacy powinno błędnie przypisać open=200 do year 12.');
assert(secondOpeningNormative.number == pastafari.BigInt(11), ...
    'Normatywne (open,close] powinno przypisać 200 do year 11.');

% 5. Produkcyjna route: RED przed PATCH 26, GREEN po nim.
ctx = pastafari.MonsterContext(0, 0);
[ctx, actual] = ...
    pastafari.YearIntervalCompatibilityRoute.call( ...
        ctx, anchor, pastafari.BigInt(100), years);

rawPattern = actual.number == pastafari.BigInt(11);
greenPattern = actual.number == pastafari.BigInt(10);
assert(rawPattern || greenPattern, ...
    ['Stage 52 powinno publikować closed-opening ghost przed PATCH 26 ', ...
     'albo previous year po PATCH 26.']);

assert(ctx.yearIntervalAnchorNumber == pastafari.BigInt(11), ...
    'Kontekst utracił anchor year number.');
assert(ctx.yearIntervalTargetDay == pastafari.BigInt(100), ...
    'Kontekst utracił target opening gate.');
assert(ctx.legacyClosedOpeningYearNumber == pastafari.BigInt(11), ...
    'Kontekst musi zachować raw legacy year 11.');
assert(ctx.legacyClosedOpeningOpenDay == pastafari.BigInt(100), ...
    'Kontekst utracił raw legacy open day.');
assert(ctx.legacyClosedOpeningCloseDay == pastafari.BigInt(200), ...
    'Kontekst utracił raw legacy close day.');
assert(ctx.legacyClosedOpeningBackwardSteps == 0, ...
    'Raw scar powinien zachować brak backward step.');
assert(ctx.legacyClosedOpeningForwardSteps == 0, ...
    'Opening witness nie powinien wykonywać forward step.');
assert(ctx.legacyClosedOpeningYearCandidate.number == ...
    pastafari.BigInt(11), ...
    'Kontekst utracił pełny raw legacy year candidate.');

assert(any(strcmp(ctx.branchTrace, ...
    'DISCOVERY_26_CLOSED_OPENING_GATE')), ...
    'Brakuje śladu Discovery 26.');
metricKey = matlab.lang.makeValidName( ...
    'discovery26.closedOpeningGate.calls');
assert(isfield(ctx.metrics, metricKey) && ctx.metrics.(metricKey) == 1, ...
    'Licznik closed-opening-gate jest niepoprawny.');

fprintf(['STAGE52 DISCOVERY26 TARGET=100 ANCHOR=11 ', ...
    'LEGACY=11 NORMATIVE=10 ACTUAL=%s CLASSIFICATION=%s\n'], ...
    char(actual.number), classification(rawPattern));

% 6. Public route nadal dochodzi do kontrolowanej granicy bootstrapu.
pastafari.LegacyYearNumberStructureCache.clear();
foundation = pastafari.BigInt('-15055671');
caught = false;
try
    calendarDateSpaghetti(foundation, foundation);
catch err
    caught = strcmp(err.identifier, ...
        'Pastafari:Bootstrap:NotImplementedYet');
end
assert(caught, ...
    'Publiczna trasa nie zachowała kontrolowanej granicy etapu 52.');

if rawPattern
    fprintf('STAGE_52_DISCOVERY_26_EXPECTED_RED\n');
    error('Pastafari:Discovery26:ClosedOpeningGate', ...
        ['Oczekiwana rozbieżność Discovery 26: historyczne [open,close] ', ...
         'przypisuje opening gate do roku po prawej stronie granicy.']);
end

fprintf('STAGE_52_DISCOVERY_26_REGRESSION_GREEN\n');
end

function years = syntheticYears()
years = { ...
    struct( ...
        'number', pastafari.BigInt(10), ...
        'openGateDay', pastafari.BigInt(0), ...
        'closeGateDay', pastafari.BigInt(100)), ...
    struct( ...
        'number', pastafari.BigInt(11), ...
        'openGateDay', pastafari.BigInt(100), ...
        'closeGateDay', pastafari.BigInt(200)), ...
    struct( ...
        'number', pastafari.BigInt(12), ...
        'openGateDay', pastafari.BigInt(200), ...
        'closeGateDay', pastafari.BigInt(300))};
end

function year = normativeYearTestOnly(years, targetDay)
target = pastafari.BigInt.coerce(targetDay);
matches = {};

for k = 1:numel(years)
    openDay = pastafari.BigInt.coerce(years{k}.openGateDay);
    closeDay = pastafari.BigInt.coerce(years{k}.closeGateDay);

    if openDay < target && target <= closeDay
        matches{end + 1} = years{k}; %#ok<AGROW>
    end
end

if numel(matches) ~= 1
    error('Pastafari:Stage52:NormativeFixture', ...
        'Test-only (open,close] resolver oczekiwał dokładnie jednego roku.');
end

year = matches{1};
end

function text = classification(isRed)
if isRed
    text = 'EXPECTED_RED';
else
    text = 'MATCH';
end
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'src'));
end
