function run_stage37_tests()
% PATCH 18: zachowaj raw /365 guess i publikuj sequential year walk.

% Niezmieniony regression Discovery 18 ma po PATCH 18 przejść na GREEN.
run_stage36_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

years = makeYearChain();
anchor = yearByNumber(years, 5000);

% Controls: lokalne przypadki pozostają zgodne, ale teraz wynik pochodzi
% z tej samej sequential semantyki co przypadki odległe.
controls = { ...
    struct('target', -100, 'expected', 4999, ...
           'forward', 0, 'backward', 1), ...
    struct('target', 100, 'expected', 5000, ...
           'forward', 0, 'backward', 0), ...
    struct('target', 400, 'expected', 5001, ...
           'forward', 1, 'backward', 0)};

for k = 1:numel(controls)
    c = controls{k};
    [actual, walk] = pastafari.SequentialYearWalkPatch.apply( ...
        anchor, pastafari.BigInt(c.target), years);

    assert(pastafari.BigInt.coerce(actual.number) == ...
        pastafari.BigInt(c.expected), ...
        'Sequential control wybrał błędny rok.');
    assert(walk.forwardSteps == c.forward, ...
        'Sequential control ma błędną liczbę forward steps.');
    assert(walk.backwardSteps == c.backward, ...
        'Sequential control ma błędną liczbę backward steps.');
end

% Distant future/past: raw /365 nadal jest błędny, patched path jest poprawny.
cases = { ...
    struct('label', 'FUTURE', 'target', 1500, ...
           'rawNumber', 5004, 'expectedNumber', 5003, ...
           'forward', 3, 'backward', 0), ...
    struct('label', 'PAST', 'target', -1200, ...
           'rawNumber', 4996, 'expectedNumber', 4997, ...
           'forward', 0, 'backward', 3)};

for k = 1:numel(cases)
    c = cases{k};
    target = pastafari.BigInt(c.target);

    [raw, rawTelemetry] = ...
        pastafari.LegacyOldYearJumpGuess.apply(anchor, target, years);
    [direct, walk] = ...
        pastafari.SequentialYearWalkPatch.apply(anchor, target, years);

    assert(~isempty(raw), 'Raw /365 guess nie może być pusty.');
    assert(rawTelemetry.guessedNumber == pastafari.BigInt(c.rawNumber), ...
        ['Raw guessed number jest błędny dla ', c.label, '.']);
    assert(pastafari.BigInt.coerce(raw.number) == ...
        pastafari.BigInt(c.rawNumber), ...
        ['Raw guessed year jest błędny dla ', c.label, '.']);

    assert(pastafari.BigInt.coerce(direct.number) == ...
        pastafari.BigInt(c.expectedNumber), ...
        ['Sequential patch wybrał błędny rok dla ', c.label, '.']);
    assert(walk.forwardSteps == c.forward, ...
        ['Błędna liczba forward steps dla ', c.label, '.']);
    assert(walk.backwardSteps == c.backward, ...
        ['Błędna liczba backward steps dla ', c.label, '.']);

    ctx = pastafari.MonsterContext(0, 0);
    [ctx, actual] = pastafari.TargetYearCompatibilityRoute.call( ...
        ctx, anchor, target, years);

    assert(pastafari.BigInt.coerce(actual.number) == ...
        pastafari.BigInt(c.expectedNumber), ...
        ['Publikowany target year jest błędny dla ', c.label, '.']);
    assert(pastafari.BigInt.coerce(ctx.targetYearCandidate.number) == ...
        pastafari.BigInt(c.expectedNumber), ...
        'Kontekst utracił patched target year.');

    % Raw scar Stage 36 musi pozostać dokładnie obserwowalny.
    assert(ctx.legacyYearJumpAnchorNumber == pastafari.BigInt(5000), ...
        'PATCH 18 utracił raw anchor number.');
    assert(ctx.legacyYearJumpAnchorOpenDay == pastafari.BigInt(0), ...
        'PATCH 18 utracił raw anchor open day.');
    assert(ctx.legacyYearJumpTargetDay == target, ...
        'PATCH 18 utracił raw target day.');
    assert(ctx.legacyYearJumpGuessNumber == pastafari.BigInt(c.rawNumber), ...
        'PATCH 18 zmienił raw /365 guessed number.');
    assert(~isempty(ctx.legacyYearJumpGuessedYear), ...
        'PATCH 18 utracił raw guessed year.');
    assert(pastafari.BigInt.coerce(ctx.legacyYearJumpGuessedYear.number) == ...
        pastafari.BigInt(c.rawNumber), ...
        'PATCH 18 zmienił raw guessed year.');

    assert(any(strcmp(ctx.branchTrace, ...
        'DISCOVERY_18_OLD_YEAR_JUMP_GUESS_BY_365')), ...
        'Brakuje śladu historycznego Discovery 18.');
    assert(any(strcmp(ctx.branchTrace, ...
        'PATCH_18_SEQUENTIAL_YEAR_WALK')), ...
        'Brakuje śladu PATCH 18.');

    legacyKey = matlab.lang.makeValidName( ...
        'discovery18.oldYearJumpGuess.calls');
    patchKey = matlab.lang.makeValidName( ...
        'patch18.sequentialYearWalk.calls');
    assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
        'Licznik raw /365 guess jest niepoprawny.');
    assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
        'Licznik sequential year walk jest niepoprawny.');
end

% Dokładna semantyka granic: (open, close].
boundaryCases = { ...
    struct('target', 365, 'expected', 5000), ...
    struct('target', 0, 'expected', 4999), ...
    struct('target', -365, 'expected', 4998), ...
    struct('target', 730, 'expected', 5001), ...
    struct('target', 1330, 'expected', 5002)};

for k = 1:numel(boundaryCases)
    c = boundaryCases{k};
    [actual, ~] = pastafari.SequentialYearWalkPatch.apply( ...
        anchor, pastafari.BigInt(c.target), years);
    assert(pastafari.BigInt.coerce(actual.number) == ...
        pastafari.BigInt(c.expected), ...
        'Sequential boundary (open, close] jest błędny.');
end

% Brak wymaganego sąsiada ma być jawnie odrzucony, nie przeskakiwany.
brokenYears = years;
brokenYears(7) = []; % usuń rok 5002
caughtMissing = false;
try
    pastafari.SequentialYearWalkPatch.apply( ...
        anchor, pastafari.BigInt(1500), brokenYears);
catch err
    caughtMissing = strcmp(err.identifier, ...
        'Pastafari:Years:SequentialNeighborMissing');
end
assert(caughtMissing, ...
    'Sequential walk nie może przeskakiwać brakującego numeru roku.');

% Niespójna granica sąsiadów również ma być jawnie odrzucona.
brokenBoundary = years;
brokenBoundary{6}.openGateDay = pastafari.BigInt(366);
caughtBoundary = false;
try
    pastafari.SequentialYearWalkPatch.apply( ...
        anchor, pastafari.BigInt(400), brokenBoundary);
catch err
    caughtBoundary = strcmp(err.identifier, ...
        'Pastafari:Years:SequentialBoundaryGap');
end
assert(caughtBoundary, ...
    'Sequential walk nie może akceptować nieciągłej granicy lat.');

% Fizyczny legacy /365 guess pozostaje bez zmian.
[legacyAgain, telemetryAgain] = ...
    pastafari.LegacyOldYearJumpGuess.apply( ...
        anchor, pastafari.BigInt(1500), years);
assert(telemetryAgain.guessedNumber == pastafari.BigInt(5004), ...
    'LegacyOldYearJumpGuess został zmieniony przez PATCH 18.');
assert(pastafari.BigInt.coerce(legacyAgain.number) == pastafari.BigInt(5004), ...
    'Legacy raw guessed year powinien nadal wynosić 5004.');

fprintf('STAGE_37_PATCH_18_GREEN\n');
end

function years = makeYearChain()
years = { ...
    makeYear(4996, -1930, -1565), ...
    makeYear(4997, -1565, -965), ...
    makeYear(4998, -965, -365), ...
    makeYear(4999, -365, 0), ...
    makeYear(5000, 0, 365), ...
    makeYear(5001, 365, 730), ...
    makeYear(5002, 730, 1330), ...
    makeYear(5003, 1330, 1930), ...
    makeYear(5004, 1930, 2295)};
end

function year = makeYear(number, openDay, closeDay)
year = struct( ...
    'number', pastafari.BigInt(number), ...
    'openGateDay', pastafari.BigInt(openDay), ...
    'closeGateDay', pastafari.BigInt(closeDay));
end

function year = yearByNumber(years, number)
year = [];
for k = 1:numel(years)
    if pastafari.BigInt.coerce(years{k}.number) == pastafari.BigInt(number)
        year = years{k};
        return
    end
end
error('Pastafari:Stage37:MissingYear', ...
    'Fixture nie zawiera wymaganego numeru roku.');
end

function cleanupPaths(root)
rmpath(fullfile(root, 'src'));
end
