function run_stage40_tests()
% DISCOVERY 20: structure sauce używa originalTargetDay zamiast
% autorytatywnego pierwszego dnia roku openGateDay+1.
%
% oldStructureSauce musi pozostać fizycznie callable po PATCH 20,
% a raw ghost ma nadal ujawniać historyczny target.

run_stage39_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(root, 'tests', 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

witnesses = { ...
    struct( ...
        'cDay', '-15055671', ...
        'originalTarget', '-15055668', ...
        'yearFirstDay', '-15050770', ...
        'rawBowl2', ...
            '30490712077192838912252735934522861502', ...
        'expectedBowl2', ...
            '25571125800832315000523776987293072647'), ...
    struct( ...
        'cDay', '-15055664', ...
        'originalTarget', '-15055666', ...
        'yearFirstDay', '-15055564', ...
        'rawBowl2', ...
            '44486119807401318534404702377176765242', ...
        'expectedBowl2', ...
            '163498808332082587884523302982947090138'), ...
    struct( ...
        'cDay', '-15055682', ...
        'originalTarget', '-15055677', ...
        'yearFirstDay', '-15055782', ...
        'rawBowl2', ...
            '115056314572464196578969473149772288830', ...
        'expectedBowl2', ...
            '73239755307544431731595307996239836106')};

divergent = false(1, numel(witnesses));

for k = 1:numel(witnesses)
    w = witnesses{k};
    cDay = pastafari.BigInt(w.cDay);
    originalTarget = pastafari.BigInt(w.originalTarget);
    yearFirstDay = pastafari.BigInt(w.yearFirstDay);
    year = makeYear(5000 + k, yearFirstDay - pastafari.BigInt(1), ...
        yearFirstDay + pastafari.BigInt(399));

    % Raw helper: exact historical call signature and exact recorded scar.
    raw = pastafari.oldStructureSauce(cDay, originalTarget);
    assert(raw.targetDay == originalTarget, ...
        'oldStructureSauce utracił originalTargetDay.');
    assert(raw.bowl2 == pastafari.BigInt(w.rawBowl2), ...
        ['Historyczny bowl2 witness ', num2str(k), ' jest błędny.']);

    % Independent normative comparison: first day of year = openGateDay+1.
    expected = normative_oracle('sauce', cDay, yearFirstDay);
    assert(expected.bowls{2} == pastafari.BigInt(w.expectedBowl2), ...
        ['Normatywny bowl2 witness ', num2str(k), ' jest błędny.']);
    assert(raw.bowl2 ~= expected.bowls{2}, ...
        'Discovery 20 witness musi odróżniać oba sauce targets.');

    ctx = pastafari.MonsterContext(cDay, originalTarget);
    [ctx, actual] = ...
        pastafari.StructureSauceCompatibilityRoute.call( ...
            ctx, cDay, originalTarget, year);

    % Raw scar musi pozostać również po PATCH 20.
    assert(ctx.structureSauceCalculationDay == cDay, ...
        'Kontekst utracił structure sauce cDay.');
    assert(ctx.structureSauceOriginalTargetDay == originalTarget, ...
        'Kontekst utracił originalTargetDay.');
    assert(ctx.structureSauceYearFirstDay == yearFirstDay, ...
        'Kontekst utracił yearFirstDay.');
    assert(ctx.legacyStructureSauce.targetDay == originalTarget, ...
        'Raw ghost nie zachował historycznego target.');
    assert(ctx.legacyStructureSauceBowl2 == pastafari.BigInt(w.rawBowl2), ...
        'Raw ghost bowl2 został zmieniony.');
    assert(isequal(ctx.legacyStructureSauceOrderAt46, raw.orderAt46Latch), ...
        'Raw ghost orderAt46 został zmieniony.');

    actualBowl2 = actual.bowl2;
    rawPattern = actualBowl2 == raw.bowl2;
    greenPattern = actualBowl2 == expected.bowls{2};
    assert(rawPattern || greenPattern, ...
        ['Stage 40 powinno publikować raw old sauce przed PATCH 20 ', ...
         'albo first-day sauce po PATCH 20.']);

    divergent(k) = rawPattern;

    assert(any(strcmp(ctx.branchTrace, ...
        'DISCOVERY_20_OLD_STRUCTURE_SAUCE_TARGET')), ...
        'Brakuje śladu Discovery 20.');
    metricKey = matlab.lang.makeValidName( ...
        'discovery20.oldStructureSauceTarget.calls');
    assert(isfield(ctx.metrics, metricKey) && ctx.metrics.(metricKey) == 1, ...
        'Licznik old-structure-sauce-target jest niepoprawny.');

    fprintf(['STAGE40 DISCOVERY20 WITNESS=%d CDAY=%s RAW_TARGET=%s ', ...
        'FIRST_DAY=%s RAW_BOWL2=%s ACTUAL_BOWL2=%s EXPECTED_BOWL2=%s ', ...
        'CLASSIFICATION=%s\n'], ...
        k, char(cDay), char(originalTarget), char(yearFirstDay), ...
        char(raw.bowl2), char(actualBowl2), char(expected.bowls{2}), ...
        classification(rawPattern));
end

assert(all(divergent) || ~any(divergent), ...
    ['Stage 40 ma być RED dla wszystkich trzech witnesses przed ', ...
     'PATCH 20 albo GREEN dla wszystkich po authoritative sauce.']);

% Control: gdy originalTargetDay już jest first day, stary i normatywny
% sauce są identyczne. PATCH 20 może później reuse ghost bez recompute.
controlCDay = pastafari.BigInt('-15055571');
controlFirstDay = pastafari.BigInt('-15055660');
controlYear = makeYear(5100, ...
    controlFirstDay - pastafari.BigInt(1), ...
    controlFirstDay + pastafari.BigInt(399));

controlRaw = pastafari.oldStructureSauce(controlCDay, controlFirstDay);
controlExpected = normative_oracle('sauce', controlCDay, controlFirstDay);
assert(controlRaw.bowl2 == controlExpected.bowls{2}, ...
    'Equal-target control powinien mieć identyczny sauce.');

controlCtx = pastafari.MonsterContext(controlCDay, controlFirstDay);
[controlCtx, controlActual] = ...
    pastafari.StructureSauceCompatibilityRoute.call( ...
        controlCtx, controlCDay, controlFirstDay, controlYear);
assert(controlActual.bowl2 == controlExpected.bowls{2}, ...
    'Equal-target control nie może być uszkodzony przez Discovery 20.');

% Public route nadal kończy się na kontrolowanej granicy etapu.
pastafari.LegacyYearNumberStructureCache.clear();
foundation = pastafari.BigInt('-15055671');
caught = false;
try
    calendarDateSpaghetti(foundation, foundation);
catch err
    caught = strcmp(err.identifier, 'Pastafari:Bootstrap:NotImplementedYet');
end
assert(caught, ...
    'Publiczna trasa nie zachowała kontrolowanej granicy etapu 40.');

if any(divergent)
    assert(all(divergent), ...
        'Discovery 20 powinno mylić wszystkie trzy non-equal witnesses.');
    fprintf('STAGE_40_DISCOVERY_20_EXPECTED_RED\n');
    error('Pastafari:Discovery20:OldStructureSauceTarget', ...
        ['Oczekiwana rozbieżność Discovery 20: year structure używa ', ...
         'Sauce(cDay, originalTargetDay) zamiast Sauce(cDay, firstDayOfYear).']);
end

fprintf('STAGE_40_DISCOVERY_20_REGRESSION_GREEN\n');
end

function year = makeYear(number, openDay, closeDay)
year = struct( ...
    'number', pastafari.BigInt(number), ...
    'openGateDay', pastafari.BigInt.coerce(openDay), ...
    'closeGateDay', pastafari.BigInt.coerce(closeDay));
end

function text = classification(isRed)
if isRed
    text = 'EXPECTED_RED';
else
    text = 'MATCH';
end
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'tests', 'oracle'));
rmpath(fullfile(root, 'src'));
end
