function run_stage38_tests()
% DISCOVERY 19: structure cache key jest wyłącznie year.number.
% Dwa calculationDay dla tego samego roku kolidują. Raw hit/scar ma
% pozostać po PATCH 19, ale publikowany value ma wtedy zostać guarded.

run_stage37_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

pastafari.LegacyYearNumberStructureCache.clear();

year = makeYear(5000, 1000, 1400);
cDayA = pastafari.BigInt(111);
cDayB = pastafari.BigInt(222);

valueA = structureValue('A', cDayA, year);
valueB = structureValue('B', cDayB, year);

% Cold fill dla calculationDay A.
ctxA = pastafari.MonsterContext(cDayA, 0);
[ctxA, actualA] = ...
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxA, year, cDayA, @() valueA);

assert(strcmp(actualA.marker, 'A'), ...
    'Cold cache powinien opublikować strukturę A.');
assert(~ctxA.legacyYearCacheHit, ...
    'Pierwszy lookup powinien być raw cache miss.');
assert(ctxA.legacyYearCacheProducerExecuted, ...
    'Cold miss powinien uruchomić producenta.');
assert(ctxA.legacyYearCacheEntryCalculationDayFingerprint == cDayA, ...
    'Cold entry ma błędny calculationDay fingerprint.');
assert(ctxA.legacyYearCacheEntryOpenGate == year.openGateDay, ...
    'Cold entry ma błędny open gate.');
assert(ctxA.legacyYearCacheEntryCloseGate == year.closeGateDay, ...
    'Cold entry ma błędny close gate.');

% Warm hit w tym samym kontekście jest poprawny nawet w legacy.
ctxWarm = pastafari.MonsterContext(cDayA, 0);
[ctxWarm, warmA] = ...
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxWarm, year, cDayA, ...
        @() structureValue('SHOULD_NOT_RUN', cDayA, year));

assert(strcmp(warmA.marker, 'A'), ...
    'Warm same-context hit powinien zwrócić A.');
assert(ctxWarm.legacyYearCacheHit, ...
    'Warm same-context lookup powinien być raw hit.');
assert(~ctxWarm.legacyYearCacheProducerExecuted, ...
    'Warm same-context raw hit nie powinien uruchamiać producenta.');

% Drugi calculationDay, ten sam year.number i te same gates.
% Sam raw cache musi ujawnić kolizję również po przyszłym PATCH 19.
[rawBefore, rawHitBefore, rawEntryBefore] = ...
    pastafari.LegacyYearNumberStructureCache.getRaw(year);

assert(rawHitBefore, ...
    'Raw cache powinien mieć entry dla year.number=5000.');
assert(strcmp(rawBefore.marker, 'A'), ...
    'Raw cache powinien nadal zawierać A przed drugim wywołaniem.');
assert(rawEntryBefore.calculationDayFingerprint == cDayA, ...
    'Raw entry powinien nadal mieć fingerprint A.');

ctxB = pastafari.MonsterContext(cDayB, 0);
[ctxB, actualB] = ...
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxB, year, cDayB, @() valueB);

% Historyczna blizna musi pozostać obserwowalna również po PATCH 19.
assert(ctxB.legacyYearCacheKey == pastafari.BigInt(5000), ...
    'Kontekst utracił zły key year.number.');
assert(ctxB.legacyYearCacheHit, ...
    'Drugi calculationDay powinien nadal widzieć raw year-number hit.');
assert(ctxB.legacyYearCacheEntryCalculationDayFingerprint == cDayA, ...
    'Raw hit powinien wskazywać fingerprint pierwszego calculationDay.');
assert(ctxB.legacyYearCacheEntryOpenGate == year.openGateDay, ...
    'Raw hit utracił open gate.');
assert(ctxB.legacyYearCacheEntryCloseGate == year.closeGateDay, ...
    'Raw hit utracił close gate.');
assert(strcmp(ctxB.legacyYearCacheRawValue.marker, 'A'), ...
    'Raw legacy value powinien pozostać strukturą A.');

rawPattern = strcmp(actualB.marker, 'A');
greenPattern = strcmp(actualB.marker, 'B');
assert(rawPattern || greenPattern, ...
    ['Stage 38 powinno publikować stale A przed PATCH 19 albo świeże B ', ...
     'po guardzie.']);

assert(any(strcmp(ctxB.branchTrace, ...
    'DISCOVERY_19_BAD_YEAR_CACHE_KEY')), ...
    'Brakuje śladu Discovery 19.');
metricKey = matlab.lang.makeValidName( ...
    'discovery19.badYearCacheKey.calls');
assert(isfield(ctxB.metrics, metricKey) && ctxB.metrics.(metricKey) == 1, ...
    'Licznik bad-year-cache-key jest niepoprawny.');

fprintf(['STAGE38 DISCOVERY19 KEY=%s RAW_FINGERPRINT=%s ', ...
    'RAW=%s ACTUAL=%s EXPECTED=%s CLASSIFICATION=%s\n'], ...
    char(ctxB.legacyYearCacheKey), ...
    char(ctxB.legacyYearCacheEntryCalculationDayFingerprint), ...
    ctxB.legacyYearCacheRawValue.marker, actualB.marker, valueB.marker, ...
    classification(rawPattern));

% Public entry nadal kończy się na kontrolowanej granicy etapu.
pastafari.LegacyYearNumberStructureCache.clear();
foundation = pastafari.BigInt('-15055671');
caught = false;
try
    calendarDateSpaghetti(foundation, foundation);
catch err
    caught = strcmp(err.identifier, 'Pastafari:Bootstrap:NotImplementedYet');
end
assert(caught, ...
    'Publiczna trasa nie zachowała kontrolowanej granicy etapu 38.');

if rawPattern
    fprintf('STAGE_38_DISCOVERY_19_EXPECTED_RED\n');
    error('Pastafari:Discovery19:BadYearCacheKey', ...
        ['Oczekiwana rozbieżność Discovery 19: cache hit po samym ', ...
         'year.number zwrócił strukturę innego calculationDay.']);
end

fprintf('STAGE_38_DISCOVERY_19_REGRESSION_GREEN\n');
end

function year = makeYear(number, openDay, closeDay)
year = struct( ...
    'number', pastafari.BigInt(number), ...
    'openGateDay', pastafari.BigInt(openDay), ...
    'closeGateDay', pastafari.BigInt(closeDay));
end

function value = structureValue(marker, cDay, year)
value = struct( ...
    'marker', marker, ...
    'calculationDay', pastafari.BigInt.coerce(cDay), ...
    'openGateDay', pastafari.BigInt.coerce(year.openGateDay), ...
    'closeGateDay', pastafari.BigInt.coerce(year.closeGateDay));
end

function text = classification(isRed)
if isRed
    text = 'EXPECTED_RED';
else
    text = 'MATCH';
end
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'src'));
end
