function run_stage41_tests()
% PATCH 20: zachowaj realny legacy ghost, publikuj Sauce(cDay,firstDayOfYear).

% Niezmieniony regression Discovery 20 ma po PATCH 20 przejść na GREEN.
run_stage40_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(root, 'tests', 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

witnesses = { ...
    struct( ...
        'cDay', '-15055671', ...
        'originalTarget', '-15055668', ...
        'yearFirstDay', '-15050770', ...
        'rawBowl2', ...
            '30490712077192838912252735934522861502', ...
        'expectedBowl2', ...
            '25571125800832315000523776987293072647'), ...
    struct( ...
        'cDay', '-15055664', ...
        'originalTarget', '-15055666', ...
        'yearFirstDay', '-15055564', ...
        'rawBowl2', ...
            '44486119807401318534404702377176765242', ...
        'expectedBowl2', ...
            '163498808332082587884523302982947090138'), ...
    struct( ...
        'cDay', '-15055682', ...
        'originalTarget', '-15055677', ...
        'yearFirstDay', '-15055782', ...
        'rawBowl2', ...
            '115056314572464196578969473149772288830', ...
        'expectedBowl2', ...
            '73239755307544431731595307996239836106')};

for k = 1:numel(witnesses)
    w = witnesses{k};
    cDay = pastafari.BigInt(w.cDay);
    originalTarget = pastafari.BigInt(w.originalTarget);
    yearFirstDay = pastafari.BigInt(w.yearFirstDay);
    year = makeYear(5000 + k, ...
        yearFirstDay - pastafari.BigInt(1), ...
        yearFirstDay + pastafari.BigInt(399));

    ghost = pastafari.oldStructureSauce(cDay, originalTarget);
    assert(ghost.targetDay == originalTarget, ...
        'PATCH 20 nie może zmienić targetu historycznego ghost.');
    assert(ghost.bowl2 == pastafari.BigInt(w.rawBowl2), ...
        'PATCH 20 nie może zmienić historycznego bowl2.');

    expected = normative_oracle('sauce', cDay, yearFirstDay);
    assert(expected.bowls{2} == pastafari.BigInt(w.expectedBowl2), ...
        'Authoritative witness ma błędny bowl2.');

    [direct, reusedGhost] = ...
        pastafari.StructureSauceDetourPatch.apply( ...
            cDay, originalTarget, yearFirstDay, ghost);

    assert(~reusedGhost, ...
        'Non-equal target witness powinien obliczyć authoritative sauce.');
    assert(direct.targetDay == yearFirstDay, ...
        'PATCH 20 direct path ma błędny semantic target.');
    assertSauceEqualsOracle(direct, expected);

    ctx = pastafari.MonsterContext(cDay, originalTarget);
    [ctx, actual] = ...
        pastafari.StructureSauceCompatibilityRoute.call( ...
            ctx, cDay, originalTarget, year);

    % Raw scar Discovery 20 pozostaje dokładnie obserwowalny.
    assert(ctx.structureSauceCalculationDay == cDay, ...
        'Kontekst utracił structure sauce cDay.');
    assert(ctx.structureSauceOriginalTargetDay == originalTarget, ...
        'Kontekst utracił originalTargetDay.');
    assert(ctx.structureSauceYearFirstDay == yearFirstDay, ...
        'Kontekst utracił yearFirstDay.');
    assert(ctx.legacyStructureSauce.targetDay == originalTarget, ...
        'Raw ghost target został zmieniony.');
    assert(ctx.legacyStructureSauceBowl2 == pastafari.BigInt(w.rawBowl2), ...
        'Raw ghost bowl2 został zmieniony.');
    assert(isequal(ctx.legacyStructureSauceOrderAt46, ...
        ghost.orderAt46Latch), ...
        'Raw ghost orderAt46 został zmieniony.');

    % Semantic path jest wyłącznie first-day sauce.
    assert(actual.targetDay == yearFirstDay, ...
        'Publikowany structure sauce ma błędny target.');
    assert(actual.bowl2 == pastafari.BigInt(w.expectedBowl2), ...
        'Publikowany structure sauce ma błędny bowl2.');
    assertSauceEqualsOracle(actual, expected);
    assert(ctx.structureSauceCandidate.targetDay == yearFirstDay, ...
        'Kontekst utracił authoritative sauce target.');
    assert(ctx.structureSauceBowl2Candidate == expected.bowls{2}, ...
        'Kontekst utracił authoritative bowl2.');

    assert(any(strcmp(ctx.branchTrace, ...
        'DISCOVERY_20_OLD_STRUCTURE_SAUCE_TARGET')), ...
        'Brakuje śladu historycznego Discovery 20.');
    assert(any(strcmp(ctx.branchTrace, ...
        'PATCH_20_STRUCTURE_SAUCE_DETOUR')), ...
        'Brakuje śladu PATCH 20.');

    legacyKey = matlab.lang.makeValidName( ...
        'discovery20.oldStructureSauceTarget.calls');
    patchKey = matlab.lang.makeValidName( ...
        'patch20.structureSauceDetour.calls');
    assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
        'Licznik raw old structure sauce jest niepoprawny.');
    assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
        'Licznik PATCH 20 jest niepoprawny.');
end

% Struktura tego samego roku musi być niezależna od original targetu.
independentCDay = pastafari.BigInt('-15055671');
independentFirstDay = pastafari.BigInt('-15050770');
independentYear = makeYear(5200, ...
    independentFirstDay - pastafari.BigInt(1), ...
    independentFirstDay + pastafari.BigInt(399));

targetA = pastafari.BigInt('-15055668');
targetB = pastafari.BigInt('-15055660');

ctxA = pastafari.MonsterContext(independentCDay, targetA);
[ctxA, sauceA] = ...
    pastafari.StructureSauceCompatibilityRoute.call( ...
        ctxA, independentCDay, targetA, independentYear);

ctxB = pastafari.MonsterContext(independentCDay, targetB);
[ctxB, sauceB] = ...
    pastafari.StructureSauceCompatibilityRoute.call( ...
        ctxB, independentCDay, targetB, independentYear);

assert(sauceA.targetDay == independentFirstDay && ...
       sauceB.targetDay == independentFirstDay, ...
    'Oba requesty muszą publikować ten sam first-day target.');
assertSaucesEqual(sauceA, sauceB);
assert(ctxA.legacyStructureSauce.targetDay == targetA, ...
    'Pierwszy raw ghost utracił original target.');
assert(ctxB.legacyStructureSauce.targetDay == targetB, ...
    'Drugi raw ghost utracił original target.');

% Equal-target control: ghost można reuse bez drugiego obliczenia.
controlCDay = pastafari.BigInt('-15055571');
controlFirstDay = pastafari.BigInt('-15055660');
controlYear = makeYear(5300, ...
    controlFirstDay - pastafari.BigInt(1), ...
    controlFirstDay + pastafari.BigInt(399));

controlGhost = ...
    pastafari.oldStructureSauce(controlCDay, controlFirstDay);
[controlDirect, reusedGhost] = ...
    pastafari.StructureSauceDetourPatch.apply( ...
        controlCDay, controlFirstDay, controlFirstDay, controlGhost);

assert(reusedGhost, ...
    'Equal-target control powinien reuse historyczny ghost.');
assertSaucesEqual(controlDirect, controlGhost);

controlCtx = pastafari.MonsterContext(controlCDay, controlFirstDay);
[controlCtx, controlActual] = ...
    pastafari.StructureSauceCompatibilityRoute.call( ...
        controlCtx, controlCDay, controlFirstDay, controlYear);
assertSaucesEqual(controlActual, controlGhost);
assert(controlCtx.legacyStructureSauceBowl2 == ...
    controlCtx.structureSauceBowl2Candidate, ...
    'Equal-target reuse powinien publikować ten sam bowl2.');

% Fizyczny oldStructureSauce nadal używa originalTargetDay.
legacyAgain = pastafari.oldStructureSauce( ...
    pastafari.BigInt('-15055671'), pastafari.BigInt('-15055668'));
assert(legacyAgain.targetDay == pastafari.BigInt('-15055668'), ...
    'oldStructureSauce został przekierowany przez PATCH 20.');
assert(legacyAgain.bowl2 == ...
    pastafari.BigInt('30490712077192838912252735934522861502'), ...
    'oldStructureSauce utracił historyczny witness.');

fprintf('STAGE_41_PATCH_20_GREEN\n');
end

function year = makeYear(number, openDay, closeDay)
year = struct( ...
    'number', pastafari.BigInt(number), ...
    'openGateDay', pastafari.BigInt.coerce(openDay), ...
    'closeGateDay', pastafari.BigInt.coerce(closeDay));
end

function assertSauceEqualsOracle(actual, expected)
assert(numel(actual.bowls) == numel(expected.bowls), ...
    'Sauce ma nieoczekiwaną liczbę bowls.');
for id = 1:numel(actual.bowls)
    assert(actual.bowls{id} == expected.bowls{id}, ...
        ['Sauce bowl ', num2str(id), ' różni się od oracle.']);
end
assert(isequal(actual.orderAt46Latch, expected.orderAtDrop46), ...
    'Sauce orderAt46 różni się od oracle.');
end

function assertSaucesEqual(a, b)
assert(a.calculationDay == b.calculationDay, ...
    'Sauce calculationDay różni się.');
assert(a.targetDay == b.targetDay, ...
    'Sauce targetDay różni się.');
assert(numel(a.bowls) == numel(b.bowls), ...
    'Sauce liczba bowls różni się.');
for id = 1:numel(a.bowls)
    assert(a.bowls{id} == b.bowls{id}, ...
        ['Sauce bowl ', num2str(id), ' różni się.']);
end
assert(isequal(a.orderAt46Latch, b.orderAt46Latch), ...
    'Sauce orderAt46 różni się.');
assert(a.bowl2 == b.bowl2, ...
    'Sauce bowl2 różni się.');
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'tests', 'oracle'));
rmpath(fullfile(root, 'src'));
end
