function run_stage15_tests()
% PATCH 07: zachowaj grind+1 i dodaj sentinel row pod indeksem logicznym 0.

% Poprawiona regresja Discovery 07 ma po PATCH 07 przejść na GREEN.
run_stage14_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(here, 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root, here)); %#ok<NASGU>

canonical = pastafari.LegacyGrindTableAdapter.rowsWithoutSentinel();
rows = pastafari.SentinelGrindRowPatch.rowsWithSentinel();

assert(isequal(size(rows), [12, 5]), ...
    'PATCH 07 musi utworzyć tabelę 12x5 z jednym sentinel row.');
assert(isequal(rows(1, :), zeros(1, 5)), ...
    'Pierwszy fizyczny wiersz musi być sentinel row logicznego indeksu 0.');
assert(isequal(rows(2:12, :), canonical), ...
    'PATCH 07 nie może zmieniać żadnego z 11 kanonicznych wierszy.');

for grind = 1:11
    [row, requested, resolved] = ...
        pastafari.LegacyGrindTableAdapter.rowForGrind(rows, grind);
    assert(requested == grind + 1, ...
        ['PATCH 07 zmienił historyczne indeksowanie dla grind ', ...
         num2str(grind), '.']);
    assert(resolved == grind + 1, ...
        ['Sentinel row nie usunął nasycenia/odchylenia dla grind ', ...
         num2str(grind), '.']);
    assert(isequal(row, canonical(grind, :)), ...
        ['PATCH 07 wybrał błędny wiersz dla grind ', num2str(grind), '.']);
end

% Surowa historyczna tabela bez sentinel nadal musi wykazywać wadę.
[legacyFirst, legacyRequested, legacyResolved] = ...
    pastafari.LegacyGrindTableAdapter.rowForGrind(canonical, 1);
assert(isequal(legacyFirst, canonical(2, :)), ...
    'Historyczna blizna pierwszego grind zniknęła.');
assert(legacyRequested == 2 && legacyResolved == 2, ...
    'Historyczne grind+1 zostało zmienione.');

foundation = pastafari.BigInt('-15055671');
cases = { ...
    foundation, foundation; ...
    foundation - 3, foundation + 4; ...
    foundation + 12, foundation - 5};
labels = {'FOUNDATION_SAME', 'CROSS_FOUNDATION', 'BACKWARD_WIDE'};

for caseIndex = 1:size(cases, 1)
    c = cases{caseIndex, 1};
    t = cases{caseIndex, 2};

    counts = normative_oracle('workCounts', c, t);
    stones = normative_oracle('stones');
    hidden = referenceHiddenDrops(counts, stones);
    expected = referenceVisibleDrops(counts, stones, hidden);

    priorCtx = pastafari.MonsterContext(c, t);
    [priorCtx, priorVisible] = ...
        pastafari.VisibleDropCompatibilityRoute.call( ...
            priorCtx, counts, stones, hidden);

    ctx = pastafari.MonsterContext(c, t);
    [ctx, actual] = pastafari.GrindTableCompatibilityRoute.call( ...
        ctx, counts, stones, hidden, priorVisible);

    for i = 1:46
        assert(actual{i} == expected{i}, ...
            ['PATCH 07 rozchodzi się z oracle dla ', ...
             labels{caseIndex}, ', drop ', num2str(i), '.']);
        assert(ctx.grindVisibleCandidate{i} == expected{i}, ...
            ['Kontekst nie zachował poprawionego grind drop ', ...
             num2str(i), ' dla ', labels{caseIndex}, '.']);
    end

    assert(ctx.legacyGrindVisibleDrops{1} ~= expected{1}, ...
        ['Surowa blizna grind-table zniknęła dla ', labels{caseIndex}, '.']);
    assert(isequal(ctx.legacyGrindRequestedIndices, 2:12), ...
        'PATCH 07 zmienił historyczne requested indices.');
    assert(isequal(ctx.legacyGrindResolvedIndices, [2:11 11]), ...
        'PATCH 07 zmienił historyczne resolved indices.');

    assert(any(strcmp(ctx.branchTrace, ...
        'DISCOVERY_07_GRIND_TABLE_INDEX')), ...
        'Brakuje śladu historycznego grind-table index.');
    assert(any(strcmp(ctx.branchTrace, ...
        'PATCH_07_SENTINEL_GRIND_ROW')), ...
        'Brakuje śladu PATCH 07.');

    legacyKey = matlab.lang.makeValidName( ...
        'discovery07.grindTableIndex.calls');
    patchKey = matlab.lang.makeValidName( ...
        'patch07.sentinelGrindRow.calls');
    assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
        'Licznik historycznego grind-table index jest niepoprawny.');
    assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
        'Licznik PATCH 07 jest niepoprawny.');
end

fprintf('STAGE_15_PATCH_07_GREEN\n');
end

function hidden = referenceHiddenDrops(counts, stones)
coeff = [ ...
    3 4 6 8; ...
    5 7 10 12; ...
    7 10 14 16; ...
    9 13 18 20; ...
    11 16 22 24; ...
    13 19 26 28; ...
    15 22 30 32];
grindStone = [1 2 3 4 5 1 2];
hidden = cell(1, 7);

for k = 1:7
    row = coeff(k, :);
    x = counts.action + ...
        pastafari.BigInt(row(1)) * counts.target + ...
        pastafari.BigInt(row(2)) * counts.distance + ...
        pastafari.BigInt(row(3)) * counts.connection + ...
        pastafari.BigInt(row(4)) * pastafari.BigInt(counts.direction);
    for kind = 1:5
        x = x + stones{k, kind};
    end
    x = saveReference(x);
    for grind = 1:7
        oldX = x;
        x = saveReference( ...
            oldX.square() + pastafari.BigInt(3) * oldX + ...
            stones{k, grindStone(grind)} + pastafari.BigInt(grind));
    end
    hidden{k} = x;
end
end

function visible = referenceVisibleDrops(counts, stones, hidden)
timeline = cell(1, 53);
for k = 1:7
    timeline{8 - k} = hidden{k};
end

visible = cell(1, 46);
grinds = [ ...
    3 5 7 11 1; ...
    5 7 11 13 2; ...
    7 11 13 17 3; ...
    11 13 17 19 4; ...
    13 17 19 23 5; ...
    17 19 23 29 1; ...
    19 23 29 31 2; ...
    23 29 31 37 3; ...
    29 31 37 41 4; ...
    31 37 41 43 5; ...
    37 41 43 47 1];

for i = 1:46
    p1 = timeline{i + 6};
    p3 = timeline{i + 4};
    p7 = timeline{i};

    x = saveReference( ...
        stones{i, 1} * counts.action + ...
        stones{i, 2} * counts.target + ...
        stones{i, 3} * counts.distance + ...
        stones{i, 4} * counts.connection + ...
        stones{i, 5} * pastafari.BigInt(counts.direction) + ...
        p1 + pastafari.BigInt(3) * p3 + ...
        pastafari.BigInt(5) * p7 + pastafari.BigInt(i));

    for grind = 1:11
        oldX = x;
        row = grinds(grind, :);
        x = saveReference( ...
            oldX.square() + pastafari.BigInt(row(1)) * oldX + ...
            pastafari.BigInt(row(2)) * p1 + ...
            pastafari.BigInt(row(3)) * p3 + ...
            pastafari.BigInt(row(4)) * p7 + ...
            stones{i, row(5)});
    end

    visible{i} = x;
    timeline{i + 7} = x;
end
end

function value = saveReference(x)
M = pastafari.BigInt('170141183460469231731687303715884105727');
value = pastafari.BigInt(1) + ...
    (pastafari.BigInt.coerce(x) - pastafari.BigInt(1)).regularMod(M);
end

function cleanupPaths(root, here)
rmpath(fullfile(root, 'src'));
rmpath(fullfile(here, 'oracle'));
end
