function run_stage35_tests()
% PATCH 17: sortuj tylko contiguous equal-length runs po opening gate.

% Niezmieniony regression Discovery 17 ma po PATCH 17 przejść na GREEN.
run_stage34_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

rawCandidates = { ...
    makeCandidate(1, 30, 3000, 400), ...
    makeCandidate(2, 50, 5000, 300), ...
    makeCandidate(3, 10, 1000, 400), ...
    makeCandidate(4, 20, 2000, 300), ...
    makeCandidate(5, 25, 2500, 400), ...
    makeCandidate(6, 1, 100, 500)};

legacyOrdered = ...
    pastafari.LegacyYear5000StableLengthSort.apply(rawCandidates);
legacyIds = candidateIds(legacyOrdered);
legacyLengths = candidateLengths(legacyOrdered);

assert(isequal(legacyIds, [2 4 1 3 5 6]), ...
    'Raw historyczny order jest nieoczekiwany.');
assert(isequal(legacyLengths, [300 300 400 400 400 500]), ...
    'Raw historyczny order nie jest niemalejący po długości.');

patched = pastafari.Year5000TieRunSortPatch.apply(legacyOrdered);
patchedIds = candidateIds(patched);
patchedLengths = candidateLengths(patched);

assert(isequal(patchedIds, [4 2 3 5 1 6]), ...
    'PATCH 17 nie ustawił normatywnego order.');
assert(isequal(patchedLengths, legacyLengths), ...
    ['PATCH 17 nie może przemieszczać kandydatów pomiędzy ', ...
     'różnymi length runs.']);

% Każdy run zachowuje dokładnie swoje membership.
assert(isequal(sort(candidateIds(legacyOrdered(1:2))), ...
               sort(candidateIds(patched(1:2)))), ...
    'PATCH 17 zmienił membership run length=300.');
assert(isequal(sort(candidateIds(legacyOrdered(3:5))), ...
               sort(candidateIds(patched(3:5)))), ...
    'PATCH 17 zmienił membership run length=400.');
assert(candidateIds(legacyOrdered(6)) == candidateIds(patched(6)), ...
    'Singleton run length=500 nie może zostać przemieszczony.');

% Opening gate rośnie tylko wewnątrz każdego equal-length run.
assert(isequal(candidateOpenDays(patched(1:2)), [2000 5000]), ...
    'Run length=300 ma błędny opening-gate order.');
assert(isequal(candidateOpenDays(patched(3:5)), [1000 2500 3000]), ...
    'Run length=400 ma błędny opening-gate order.');

% Produkcyjna trasa: raw scar musi pozostać, publikowany order jest patched.
ctx = pastafari.MonsterContext(0, 0);
[ctx, actual] = ...
    pastafari.Year5000OrderingCompatibilityRoute.call(ctx, rawCandidates);

assert(isequal(candidateIds(ctx.year5000InputCandidates), ...
    [1 2 3 4 5 6]), ...
    'Kontekst utracił input Year 5000.');
assert(isequal(candidateIds(ctx.legacyYear5000StableLengthOrder), ...
    legacyIds), ...
    'PATCH 17 zmienił raw stable-length scar.');
assert(isequal(candidateIds(ctx.year5000CandidateOrder), patchedIds), ...
    'Kontekst utracił patched tie-run order.');
assert(isequal(candidateIds(actual), patchedIds), ...
    'Publikowany Year 5000 order jest błędny.');

assert(any(strcmp(ctx.branchTrace, ...
    'DISCOVERY_17_YEAR_5000_TIE')), ...
    'Brakuje śladu historycznego Discovery 17.');
assert(any(strcmp(ctx.branchTrace, ...
    'PATCH_17_YEAR_5000_TIE_RUN_SORT')), ...
    'Brakuje śladu PATCH 17.');

legacyKey = matlab.lang.makeValidName( ...
    'discovery17.year5000Tie.calls');
patchKey = matlab.lang.makeValidName( ...
    'patch17.year5000TieRunSort.calls');
assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
    'Licznik raw Year 5000 tie jest niepoprawny.');
assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
    'Licznik PATCH 17 jest niepoprawny.');

% Już poprawny run pozostaje bez zmian.
alreadySorted = { ...
    makeCandidate(10, 1, 100, 300), ...
    makeCandidate(11, 2, 200, 300), ...
    makeCandidate(12, 3, 300, 400)};
alreadyPatched = ...
    pastafari.Year5000TieRunSortPatch.apply(alreadySorted);
assert(isequal(candidateIds(alreadyPatched), [10 11 12]), ...
    'Już poprawny tie run nie powinien być przemieszczony.');

% Równe opening gate pozostają stabilne względem wejścia.
sameOpening = { ...
    makeCandidate(20, 1, 1000, 300), ...
    makeCandidate(21, 2, 1000, 300), ...
    makeCandidate(22, 3, 500, 300)};
samePatched = ...
    pastafari.Year5000TieRunSortPatch.apply(sameOpening);
assert(isequal(candidateIds(samePatched), [22 20 21]), ...
    'Equal opening gates powinny zachować stabilność wejścia.');

% Patch ma odrzucać wejście, które nie przeszło length sort.
caught = false;
try
    pastafari.Year5000TieRunSortPatch.apply({ ...
        makeCandidate(30, 1, 100, 400), ...
        makeCandidate(31, 2, 200, 300)});
catch err
    caught = strcmp(err.identifier, ...
        'Pastafari:Years:TieRunInputNotLengthSorted');
end
assert(caught, ...
    'PATCH 17 powinien wymagać wejścia już posortowanego po długości.');

% Fizyczny legacy sorter pozostaje bez zmian.
legacyAgain = ...
    pastafari.LegacyYear5000StableLengthSort.apply(rawCandidates);
assert(isequal(candidateIds(legacyAgain), legacyIds), ...
    'LegacyYear5000StableLengthSort został zmieniony przez PATCH 17.');

fprintf('STAGE_35_PATCH_17_GREEN\n');
end

function candidate = makeCandidate(id, openIndex, openDay, lengthDays)
candidate = struct( ...
    'id', id, ...
    'openGateIndex', pastafari.BigInt(openIndex), ...
    'closeGateIndex', pastafari.BigInt(openIndex + 6), ...
    'openGateDay', pastafari.BigInt(openDay), ...
    'closeGateDay', pastafari.BigInt(openDay + lengthDays));
end

function values = candidateIds(candidates)
values = zeros(1, numel(candidates));
for k = 1:numel(candidates)
    values(k) = candidates{k}.id;
end
end

function values = candidateLengths(candidates)
values = zeros(1, numel(candidates));
for k = 1:numel(candidates)
    values(k) = ( ...
        pastafari.BigInt.coerce(candidates{k}.closeGateDay) - ...
        pastafari.BigInt.coerce(candidates{k}.openGateDay)).toDoubleExact();
end
end

function values = candidateOpenDays(candidates)
values = zeros(1, numel(candidates));
for k = 1:numel(candidates)
    values(k) = ...
        pastafari.BigInt.coerce(candidates{k}.openGateDay).toDoubleExact();
end
end

function cleanupPaths(root)
rmpath(fullfile(root, 'src'));
end
