function run_stage33_tests()
% PATCH 16: late max-5778 filter z zachowaniem raw legacy max-5781 scar.

% Niezmieniony regression Discovery 16 ma po PATCH 16 przejść na GREEN.
run_stage32_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

lengths = [252 5778 5779 5780 5781];
legacyCandidates = cell(1, numel(lengths));
for k = 1:numel(lengths)
    legacyCandidates{k} = makeCandidate(k, lengths(k));
end

[filtered, rejected] = ...
    pastafari.YearMax5778LateFilter.apply(legacyCandidates);

assert(isequal(candidateLengths(filtered), [252 5778]), ...
    'PATCH 16 powinien zachować dokładnie 252 i 5778.');
assert(isequal(candidateIds(filtered), [1 2]), ...
    'Late filter nie może zmieniać kolejności zaakceptowanych kandydatów.');
assert(isequal(candidateLengths(rejected), [5779 5780 5781]), ...
    'PATCH 16 powinien odrzucić dokładnie 5779, 5780 i 5781.');
assert(isequal(candidateIds(rejected), [3 4 5]), ...
    'Late filter nie może zmieniać kolejności odrzuconych kandydatów.');

boundary = {makeCandidate(10, 5778), makeCandidate(11, 5779)};
[boundaryAccepted, boundaryRejected] = ...
    pastafari.YearMax5778LateFilter.apply(boundary);
assert(isequal(candidateIds(boundaryAccepted), 10), ...
    'Dokładny boundary 5778 musi zostać zaakceptowany.');
assert(isequal(candidateIds(boundaryRejected), 11), ...
    'Pierwszy dzień ponad limit, 5779, musi zostać odrzucony.');

rawCandidates = { ...
    makeCandidate(20, 251), ...
    makeCandidate(21, 252), ...
    makeCandidate(22, 5778), ...
    makeCandidate(23, 5779), ...
    makeCandidate(24, 5780), ...
    makeCandidate(25, 5781), ...
    makeCandidate(26, 5782)};

ctx = pastafari.MonsterContext(0, 0);
[ctx, actual] = ...
    pastafari.YearCandidateCompatibilityRoute.call(ctx, rawCandidates);

assert(ctx.legacyYearMaxDays == pastafari.BigInt(5781), ...
    'PATCH 16 nie może zmienić historycznego max 5781.');
assert(isequal( ...
    candidateLengths(ctx.legacyYearCandidatesAccepted), ...
    [252 5778 5779 5780 5781]), ...
    'PATCH 16 usunął lub zmienił raw legacy candidate list.');
assert(isequal( ...
    toDoubleRow(ctx.legacyYearCandidateLengths), ...
    [252 5778 5779 5780 5781]), ...
    'PATCH 16 zmienił raw legacy length trace.');
assert(isequal(candidateLengths(actual), [252 5778]), ...
    'Publikowana lista po PATCH 16 ma zawierać wyłącznie <=5778.');
assert(isequal(candidateLengths(ctx.yearCandidatesCandidate), [252 5778]), ...
    'Kontekst utracił late-filtered candidate list.');

assert(any(strcmp(ctx.branchTrace, ...
    'DISCOVERY_16_LEGACY_YEAR_MAX_5781')), ...
    'Brakuje śladu historycznego Discovery 16.');
assert(any(strcmp(ctx.branchTrace, ...
    'PATCH_16_LATE_5778_FILTER')), ...
    'Brakuje śladu PATCH 16.');

legacyKey = matlab.lang.makeValidName( ...
    'discovery16.legacyYearMax5781.calls');
patchKey = matlab.lang.makeValidName( ...
    'patch16.late5778Filter.calls');
assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
    'Licznik raw legacy max-5781 jest niepoprawny.');
assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
    'Licznik PATCH 16 jest niepoprawny.');

[legacyAgain, legacyAgainLengths] = ...
    pastafari.LegacyYearMax5781Filter.apply(rawCandidates);
assert(isequal(candidateLengths(legacyAgain), ...
    [252 5778 5779 5780 5781]), ...
    'LegacyYearMax5781Filter został zmieniony przez PATCH 16.');
assert(isequal(toDoubleRow(legacyAgainLengths), ...
    [252 5778 5779 5780 5781]), ...
    'Legacy max-5781 length trace został zmieniony przez PATCH 16.');

fprintf('STAGE_33_PATCH_16_GREEN\n');
end

function candidate = makeCandidate(id, lengthDays)
candidate = struct( ...
    'id', id, ...
    'openGateIndex', pastafari.BigInt(0), ...
    'closeGateIndex', pastafari.BigInt(6), ...
    'openGateDay', pastafari.BigInt(100000 + id * 10000), ...
    'closeGateDay', ...
        pastafari.BigInt(100000 + id * 10000 + lengthDays));
end

function values = candidateLengths(candidates)
values = zeros(1, numel(candidates));
for k = 1:numel(candidates)
    values(k) = ( ...
        pastafari.BigInt.coerce(candidates{k}.closeGateDay) - ...
        pastafari.BigInt.coerce(candidates{k}.openGateDay)).toDoubleExact();
end
end

function values = candidateIds(candidates)
values = zeros(1, numel(candidates));
for k = 1:numel(candidates)
    values(k) = candidates{k}.id;
end
end

function values = toDoubleRow(items)
values = zeros(1, numel(items));
for k = 1:numel(items)
    values(k) = pastafari.BigInt.coerce(items{k}).toDoubleExact();
end
end

function cleanupPaths(root)
rmpath(fullfile(root, 'src'));
end
