function run_stage06_tests()
% DISCOVERY 03: historyczny oldDistance jest różnicą poprawionych tagów dni.
% Ten sam regression ma stać się zielony po PATCH 03 w etapie 7.

% Wszystkie wcześniejsze etapy muszą pozostać zielone.
run_stage05_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(here, 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root, here)); %#ok<NASGU>

foundation = pastafari.BigInt('-15055671');

cases = { ...
    foundation,     foundation; ...
    foundation,     foundation + 3; ...
    foundation - 1, foundation; ...
    foundation - 3, foundation + 3; ...
    foundation,     foundation + 1};
labels = { ...
    'SAME_DAY', ...
    'FOUNDATION_TO_PLUS_3', ...
    'MINUS_1_TO_FOUNDATION', ...
    'CROSS_MINUS_3_PLUS_3', ...
    'FOUNDATION_TO_PLUS_1'};

legacyExpected = { ...
    pastafari.BigInt(0), ...
    pastafari.BigInt(6), ...
    pastafari.BigInt(1), ...
    pastafari.BigInt(1), ...
    pastafari.BigInt(2)};
normativeDistanceExpected = { ...
    pastafari.BigInt(1), ...
    pastafari.BigInt(4), ...
    pastafari.BigInt(2), ...
    pastafari.BigInt(7), ...
    pastafari.BigInt(2)};

divergent = false(1, size(cases, 1));

for k = 1:size(cases, 1)
    c = cases{k, 1};
    t = cases{k, 2};

    rawLegacy = pastafari.LegacyDistanceAdapter.oldDistance(c, t);
    assert(rawLegacy == legacyExpected{k}, ...
        ['Historyczny oldDistance ma nieoczekiwany wynik dla przypadku ', labels{k}, '.']);

    ctx = pastafari.MonsterContext(c, t);
    [ctx, counts] = pastafari.WorkCountsCompatibilityRoute.call(ctx, c, t);
    normative = normative_oracle('workCounts', c, t);

    assert(normative.distance == normativeDistanceExpected{k}, ...
        ['Fixture normatywnego dystansu jest niepoprawny dla przypadku ', labels{k}, '.']);

    % Discovery 03 ma izolować wyłącznie błąd distance.
    assert(counts.action == normative.action, ...
        ['Action jest niepoprawne dla przypadku ', labels{k}, '.']);
    assert(counts.target == normative.target, ...
        ['Target jest niepoprawne dla przypadku ', labels{k}, '.']);
    assert(counts.connection == normative.connection, ...
        ['Connection jest niepoprawne dla przypadku ', labels{k}, '.']);
    assert(counts.direction == normative.direction, ...
        ['Direction jest niepoprawne dla przypadku ', labels{k}, '.']);

    assert(ctx.legacyDistanceValue == rawLegacy, ...
        ['Kontekst nie zachował surowego oldDistance dla przypadku ', labels{k}, '.']);
    assert(ctx.distanceCandidate == counts.distance, ...
        ['Kontekst nie zachował publikowanego distance dla przypadku ', labels{k}, '.']);
    assert(any(strcmp(ctx.branchTrace, 'DISCOVERY_03_OLD_DISTANCE')), ...
        ['Brakuje śladu Discovery 03 dla przypadku ', labels{k}, '.']);

    metricKey = matlab.lang.makeValidName('discovery03.oldDistance.calls');
    assert(isfield(ctx.metrics, metricKey) && ctx.metrics.(metricKey) == 1, ...
        ['Licznik oldDistance jest niepoprawny dla przypadku ', labels{k}, '.']);

    divergent(k) = counts.distance ~= normative.distance;

    fprintf(['STAGE06 DISCOVERY03 CASE=%s LEGACY=%s ROUTE=%s EXPECTED=%s ', ...
        'DIRECTION=%d CONNECTION=%s CLASSIFICATION=%s\n'], ...
        labels{k}, char(rawLegacy), char(counts.distance), ...
        char(normative.distance), counts.direction, char(counts.connection), ...
        classification(divergent(k)));
end

if any(divergent)
    assert(isequal(divergent, [true, true, true, true, false]), ...
        ['Discovery 03 wykazało nieoczekiwany wzorzec rozbieżności ', ...
         'dla dystansu opartego na tagach dni.']);
end

% Publiczna ścieżka nadal zatrzymuje się na kontrolowanej granicy po
% przejściu przez wszystkie dotychczasowe warstwy.
caught = false;
try
    calendarDateSpaghetti(foundation - 3, foundation + 3);
catch err
    caught = strcmp(err.identifier, 'Pastafari:Bootstrap:NotImplementedYet');
end
assert(caught, ...
    'Publiczna trasa nie zachowała kontrolowanej granicy etapu 6.');

if any(divergent)
    fprintf('STAGE_06_DISCOVERY_03_EXPECTED_RED\n');
    error('Pastafari:Discovery03:OldDistanceDivergence', ...
        ['Oczekiwana rozbieżność Discovery 03: distance pochodzi z różnicy ', ...
         'tagów dni zamiast z chronologicznej różnicy dni powiększonej o 1.']);
end

fprintf('STAGE_06_DISCOVERY_03_REGRESSION_GREEN\n');
end

function text = classification(isDivergent)
if isDivergent
    text = 'EXPECTED_RED';
else
    text = 'MATCH';
end
end

function cleanupPaths(root, here)
rmpath(fullfile(root, 'src'));
rmpath(fullfile(here, 'oracle'));
end
