function run_stage17_tests()
% PATCH 08: one-based rank detour nad niezmienionym legacy unrank0.

% Poprawiona regresja Discovery 08 musi po PATCH 08 stać się zielona.
run_stage16_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(here, 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root, here)); %#ok<NASGU>

inputs = { ...
    pastafari.BigInt(1), ...
    pastafari.BigInt(2), ...
    pastafari.BigInt(120), ...
    pastafari.BigInt(121), ...
    pastafari.BigInt(719), ...
    pastafari.BigInt(720), ...
    pastafari.BigInt(721), ...
    pastafari.BigInt(1440)};

for k = 1:numel(inputs)
    v = inputs{k};
    [rank1, rank0] = pastafari.OneBasedRankDetourPatch.apply(v);

    expectedRank1 = ...
        (v - pastafari.BigInt(1)).regularMod(pastafari.BigInt(720)) + ...
        pastafari.BigInt(1);
    assert(rank1 == expectedRank1, ...
        ['PATCH 08 wyliczył błędną rangę 1-based dla wejścia ', char(v), '.']);
    assert(rank0 == rank1 - pastafari.BigInt(1), ...
        ['PATCH 08 wyliczył błędną rangę zero-based dla wejścia ', char(v), '.']);

    expected = normative_oracle('permutation', rank1);

    ctx = pastafari.MonsterContext(v, v);
    [ctx, actual] = pastafari.PermutationCompatibilityRoute.call(ctx, v);

    assert(isequal(actual, expected), ...
        ['PATCH 08 zwrócił błędną permutację dla wejścia ', char(v), '.']);
    assert(ctx.permutationRank1Candidate == rank1, ...
        ['Kontekst utracił rangę 1-based dla wejścia ', char(v), '.']);
    assert(ctx.permutationDetourRank0 == rank0, ...
        ['Kontekst utracił detour rank0 dla wejścia ', char(v), '.']);
    assert(isequal(ctx.permutationOrderCandidate, expected), ...
        ['Kontekst utracił publikowaną permutację dla wejścia ', char(v), '.']);

    rawRank0 = v.regularMod(pastafari.BigInt(720));
    rawOrder = pastafari.LegacyPermutationUnrank0.unrank0(rawRank0, 1:6);
    assert(ctx.legacyPermutationRank0 == rawRank0, ...
        ['PATCH 08 zmienił surową rangę legacy dla wejścia ', char(v), '.']);
    assert(isequal(ctx.legacyPermutationOrder, rawOrder), ...
        ['PATCH 08 zmienił surowy order legacy dla wejścia ', char(v), '.']);

    assert(any(strcmp(ctx.branchTrace, ...
        'DISCOVERY_08_OLD_PERMUTATION_UNRANK0')), ...
        'Brakuje śladu historycznego unrank0.');
    assert(any(strcmp(ctx.branchTrace, ...
        'PATCH_08_ONE_BASED_RANK_DETOUR')), ...
        'Brakuje śladu PATCH 08.');

    legacyKey = matlab.lang.makeValidName( ...
        'discovery08.oldPermutationUnrank0.calls');
    patchKey = matlab.lang.makeValidName( ...
        'patch08.oneBasedRankDetour.calls');
    assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
        'Licznik historycznego unrank0 jest niepoprawny.');
    assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
        'Licznik PATCH 08 jest niepoprawny.');
end

% Dwie granice, które ujawniły Discovery 08, muszą mieć dokładne wyniki.
ctx1 = pastafari.MonsterContext(pastafari.BigInt(1), pastafari.BigInt(1));
[~, order1] = pastafari.PermutationCompatibilityRoute.call( ...
    ctx1, pastafari.BigInt(1));
assert(isequal(order1, [1 2 3 4 5 6]), ...
    'PATCH 08 nie przywrócił pierwszej permutacji dla rangi 1.');

ctx720 = pastafari.MonsterContext(pastafari.BigInt(720), pastafari.BigInt(720));
[~, order720] = pastafari.PermutationCompatibilityRoute.call( ...
    ctx720, pastafari.BigInt(720));
assert(isequal(order720, [6 5 4 3 2 1]), ...
    'PATCH 08 nie przywrócił ostatniej permutacji dla rangi 720.');

fprintf('STAGE_17_PATCH_08_GREEN\n');
end

function cleanupPaths(root, here)
rmpath(fullfile(root, 'src'));
rmpath(fullfile(here, 'oracle'));
end
