function run_stage43_tests()
% PATCH 21: raw all-positive ghost zostaje, semantic family jest dokładnie
% filtrowanym leksykograficznym podciągiem z wymaganym internal boundary.

run_stage42_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

gapCount = pastafari.BigInt(10);
cutletCount = pastafari.BigInt(8);
offset = pastafari.BigInt(4);
stream = struct( ...
    'first', pastafari.BigInt(87), ...
    'directionStep', 1);

rawExpected = [1 1 1 3 1 1 1 1];
semanticExpected = [1 1 1 1 1 1 3 1];

descriptor = ...
    pastafari.FilteredLegacyCutletPartitionFamily.describe( ...
        gapCount, cutletCount, offset);
assert(strcmp(descriptor.familyName, ...
    'FILTERED_LEGACY_PREFIX_BOUNDARY'), ...
    'PATCH 21 ma nieoczekiwany typ rodziny.');
assert(descriptor.count == pastafari.BigInt(28), ...
    'PATCH 21 powinien mieć dokładnie 28 filtrowanych kompozycji.');

referenceFiltered = {};
for r = 1:36
    candidate = ...
        pastafari.LegacyAllPositiveCutletPartitionFamily.unrank1( ...
            gapCount, cutletCount, pastafari.BigInt(r));
    if hasInternalBoundary(candidate, 4)
        referenceFiltered{end + 1} = candidate; %#ok<AGROW>
    end
end
assert(numel(referenceFiltered) == 28, ...
    'Referencyjna filtrowana subsekwencja ma błędny count.');

for r = 1:28
    actual = ...
        pastafari.FilteredLegacyCutletPartitionFamily.unrank1( ...
            gapCount, cutletCount, offset, pastafari.BigInt(r));
    assert(isequal(actual, referenceFiltered{r}), ...
        ['Filtered unrank utracił legacy lexicographic order przy rank ', ...
         num2str(r), '.']);
    assert(hasInternalBoundary(actual, 4), ...
        'Filtered unrank zwrócił kompozycję bez wymaganej granicy.');
end

assert(isequal(referenceFiltered{3}, semanticExpected), ...
    'Główny filtered rank 3 ma nieoczekiwaną kompozycję.');

smallCount = ...
    pastafari.FilteredLegacyCutletPartitionFamily.count( ...
        pastafari.BigInt(10), pastafari.BigInt(3), pastafari.BigInt(4));
assert(smallCount == pastafari.BigInt(8), ...
    'Dodatkowa filtrowana rodzina G=10,K=3 powinna mieć count 8.');

smallFirst = ...
    pastafari.FilteredLegacyCutletPartitionFamily.unrank1( ...
        pastafari.BigInt(10), pastafari.BigInt(3), ...
        pastafari.BigInt(4), pastafari.BigInt(1));
smallLast = ...
    pastafari.FilteredLegacyCutletPartitionFamily.unrank1( ...
        pastafari.BigInt(10), pastafari.BigInt(3), ...
        pastafari.BigInt(4), pastafari.BigInt(8));
assert(isequal(smallFirst, [1 3 6]), ...
    'Dodatkowy filtered rank 1 powinien wynosić [1 3 6].');
assert(isequal(smallLast, [4 5 1]), ...
    'Dodatkowy filtered rank 8 powinien wynosić [4 5 1].');

ctx = pastafari.MonsterContext(0, 0);
[ctx, actual] = ...
    pastafari.CutletPartitionCompatibilityRoute.call( ...
        ctx, stream, gapCount, cutletCount, offset);

assert(ctx.legacyPositiveCompositions.count == pastafari.BigInt(36), ...
    'PATCH 21 zmienił raw legacy family count.');
assert(ctx.legacyCutletPartitionFamilyCount == pastafari.BigInt(36), ...
    'PATCH 21 utracił raw family count.');
assert(ctx.legacyCutletPartitionRank == pastafari.BigInt(15), ...
    'PATCH 21 zmienił raw rank 15.');
assert(isequal(ctx.legacyCutletPartition, rawExpected), ...
    'PATCH 21 zmienił raw legacy partition.');
assert(~hasInternalBoundary(ctx.legacyCutletPartition, 4), ...
    'Raw scar nie powinien nagle zawierać wymaganej granicy.');

assert(isequal(actual, semanticExpected), ...
    'Publikowana partition po PATCH 21 jest błędna.');
assert(isequal(ctx.cutletPartitionCandidate, semanticExpected), ...
    'Kontekst utracił semantic filtered partition.');
assert(hasInternalBoundary(actual, 4), ...
    'Semantic partition musi zawierać internal gate boundary.');
assert(ctx.generalSelectionCandidate == pastafari.BigInt(3), ...
    'Ostatni semantic selection powinien publikować rank 3.');

assert(any(strcmp(ctx.branchTrace, ...
    'DISCOVERY_21_UNFILTERED_CUTLET_PARTITIONS')), ...
    'Brakuje śladu historycznego Discovery 21.');
assert(any(strcmp(ctx.branchTrace, ...
    'PATCH_21_FILTERED_PARTITION_FAMILY')), ...
    'Brakuje śladu PATCH 21.');

legacyKey = matlab.lang.makeValidName( ...
    'discovery21.unfilteredCutletPartitions.calls');
patchKey = matlab.lang.makeValidName( ...
    'patch21.filteredPartitionFamily.calls');
assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
    'Licznik raw unfiltered family jest niepoprawny.');
assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
    'Licznik PATCH 21 jest niepoprawny.');

noGateRawCtx = pastafari.MonsterContext(0, 0);
[noGateRawCtx, noGateRawRank, noGateRawPartition, ...
    noGateRawCount, noGateRawDescriptor] = ...
    pastafari.LegacyCutletPartitionAdapter.callWithRing( ...
        noGateRawCtx, stream, gapCount, cutletCount);

noGatePatchCtx = pastafari.MonsterContext(0, 0);
[noGatePatchCtx, reusedRank, reusedPartition, reusedCount, ...
    reusedDescriptor, reusedLegacy] = ...
    pastafari.CutletPartitionGatePatchWrapper.callWithRing( ...
        noGatePatchCtx, stream, gapCount, cutletCount, [], ...
        noGateRawRank, noGateRawPartition, noGateRawCount, ...
        noGateRawDescriptor); %#ok<ASGLU>

assert(reusedLegacy, ...
    'Brak internal gate powinien reuse raw legacy selection.');
assert(reusedRank == noGateRawRank, ...
    'No-gate reuse zmienił raw rank.');
assert(reusedCount == noGateRawCount, ...
    'No-gate reuse zmienił raw family count.');
assert(isequal(reusedPartition, noGateRawPartition), ...
    'No-gate reuse zmienił raw partition.');
assert(strcmp(reusedDescriptor.familyName, ...
    noGateRawDescriptor.familyName), ...
    'No-gate reuse zmienił raw descriptor.');

noGateRouteCtx = pastafari.MonsterContext(0, 0);
[noGateRouteCtx, noGateActual] = ...
    pastafari.CutletPartitionCompatibilityRoute.call( ...
        noGateRouteCtx, stream, gapCount, cutletCount, []);
assert(isequal(noGateActual, rawExpected), ...
    'Brak internal gate powinien publikować raw legacy partition.');
assert(noGateRouteCtx.legacyCutletPartitionRank == pastafari.BigInt(15), ...
    'No-gate route utracił raw rank.');

legacyAgain = ...
    pastafari.LegacyAllPositiveCutletPartitionFamily.unrank1( ...
        gapCount, cutletCount, pastafari.BigInt(15));
assert(isequal(legacyAgain, rawExpected), ...
    'LegacyAllPositiveCutletPartitionFamily został zmieniony przez PATCH 21.');

adapterAgainCtx = pastafari.MonsterContext(0, 0);
[adapterAgainCtx, adapterAgainRank, adapterAgainPartition, ...
    adapterAgainCount, ~] = ...
    pastafari.LegacyCutletPartitionAdapter.callWithRing( ...
        adapterAgainCtx, stream, gapCount, cutletCount); %#ok<ASGLU>
assert(adapterAgainCount == pastafari.BigInt(36) && ...
       adapterAgainRank == pastafari.BigInt(15) && ...
       isequal(adapterAgainPartition, rawExpected), ...
    'LegacyCutletPartitionAdapter został zmieniony przez PATCH 21.');

fprintf('STAGE_43_PATCH_21_GREEN\n');
end

function tf = hasInternalBoundary(partition, offset)
running = 0;
tf = false;
for k = 1:(numel(partition) - 1)
    running = running + partition(k);
    if running == offset
        tf = true;
        return
    end
end
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'src'));
end
