function run_stage45_tests()
% PATCH 22: legacy repeated candidate pozostaje, publikowane nazwy są
% partial permutations bez powtórzeń dla kotletów i miesięcy.

% Niezmieniony regression Discovery 22 ma po PATCH 22 przejść na GREEN.
run_stage44_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

% 1. Brute-force mały oracle: N=5,K=3, dokładny count i lexicographic unrank.
smallCount = pastafari.partialPermutationNameRowCount( ...
    pastafari.BigInt(5), pastafari.BigInt(3));
assert(smallCount == pastafari.BigInt(60), ...
    '5P3 powinno wynosić dokładnie 60.');

smallReference = bruteDistinctRows(5, 3);
assert(size(smallReference, 1) == 60, ...
    'Brute-force reference powinien mieć 60 wierszy.');

for r = 1:60
    actual = pastafari.partialPermutationNameRowUnrank( ...
        pastafari.BigInt(5), pastafari.BigInt(3), pastafari.BigInt(r));
    assert(isequal(actual, smallReference(r, :)), ...
        ['Partial-permutation unrank utracił lexicographic order przy rank ', ...
         num2str(r), '.']);
    assert(numel(unique(actual)) == 3, ...
        'Partial-permutation unrank zwrócił powtórzenie.');
end

% 2. Obie gałęzie wrappera: equal bad/correct oraz rzeczywisty detour.
singleStream = struct( ...
    'first', pastafari.BigInt(5), ...
    'directionStep', 1);
singleCtx = pastafari.MonsterContext(0, 0);
[singleCtx, singleRawRank, singleRaw, singleRawCount, ~] = ...
    pastafari.LegacyRepeatedNameGenerator.callWithRing( ...
        singleCtx, singleStream, pastafari.BigInt(17), pastafari.BigInt(1)); %#ok<ASGLU>
[singleCtx, singleDistinctRank, singleActual, singleDistinctCount, reused] = ...
    pastafari.RepeatedNamePatchWrapper.callWithRing( ...
        singleCtx, singleStream, pastafari.BigInt(17), pastafari.BigInt(1), ...
        singleRaw); %#ok<ASGLU>
assert(reused, ...
    'K=1 powinno reuse legacy candidate, gdy bad==correct.');
assert(singleRawRank == singleDistinctRank && ...
       singleRawCount == singleDistinctCount && ...
       isequal(singleActual, singleRaw), ...
    'Equal branch wrappera zmienił poprawny legacy candidate.');

% 3. Cutlet route: raw scar z Stage 44 zostaje, semantic candidate distinct.
structureSauce = syntheticSauce();
cutletCount = pastafari.BigInt(6);
cutletCtx = pastafari.MonsterContext(0, 0);
[cutletCtx, cutletNames] = ...
    pastafari.CutletNameCompatibilityRoute.call( ...
        cutletCtx, structureSauce, cutletCount);

expectedCutletRaw = [1 1 13 9 8 14];
expectedCutletDistinct = [1 3 16 4 11 13];

assert(cutletCtx.cutletNameStreamFirst == pastafari.BigInt(61401), ...
    'Cutlet bowl-5/seal-22 first powinien nadal wynosić 61401.');
assert(cutletCtx.legacyCutletNameFamilyCount == ...
    pastafari.BigInt(24137569), ...
    'Raw cutlet family powinno nadal być 17^6.');
assert(cutletCtx.legacyCutletNameRank == pastafari.BigInt(61401), ...
    'Raw cutlet rank powinien nadal wynosić 61401.');
assert(isequal(cutletCtx.legacyNameCandidateIndices, expectedCutletRaw), ...
    'PATCH 22 zmienił raw repeated cutlet candidate.');
assert(hasRepeat(cutletCtx.legacyNameCandidateIndices), ...
    'Raw cutlet scar powinien nadal zawierać repeat.');

assert(cutletCtx.distinctCutletNameFamilyCount == ...
    pastafari.BigInt(8910720), ...
    'Distinct cutlet family powinno wynosić 17P6=8910720.');
assert(cutletCtx.distinctCutletNameRank == pastafari.BigInt(61401), ...
    'Distinct cutlet rank powinien wynosić 61401.');
assert(isequal(cutletNames, expectedCutletDistinct), ...
    'Publikowane cutlet names są błędne.');
assert(isequal(cutletCtx.cutletNameIndicesCandidate, ...
    expectedCutletDistinct), ...
    'Kontekst utracił distinct cutlet candidate.');
assert(~hasRepeat(cutletNames), ...
    'Publikowane cutlet names muszą być różne.');

% 4. Month route: 47-name catalog, bowl 5 / seal 33, również bez repeats.
monthCount = pastafari.BigInt(6);
monthCtx = pastafari.MonsterContext(0, 0);
[monthCtx, monthNames] = ...
    pastafari.MonthNameCompatibilityRoute.call( ...
        monthCtx, structureSauce, monthCount);

expectedMonthRaw = [1 1 1 31 9 35];
expectedMonthDistinct = [1 2 3 40 44 30];

assert(monthCtx.monthNameStreamFirst == pastafari.BigInt(66681), ...
    'Month bowl-5/seal-33 first powinien wynosić 66681.');
assert(monthCtx.legacyMonthNameFamilyCount == ...
    pastafari.BigInt('10779215329'), ...
    'Raw month family powinno nadal być 47^6.');
assert(monthCtx.legacyMonthNameRank == pastafari.BigInt(66681), ...
    'Raw month rank powinien wynosić 66681.');
assert(isequal(monthCtx.legacyMonthNameCandidateIndices, expectedMonthRaw), ...
    'PATCH 22 zmienił raw repeated month candidate.');
assert(hasRepeat(monthCtx.legacyMonthNameCandidateIndices), ...
    'Raw month scar powinien nadal zawierać repeat.');

assert(monthCtx.distinctMonthNameFamilyCount == ...
    pastafari.BigInt('7731052560'), ...
    'Distinct month family powinno wynosić 47P6=7731052560.');
assert(monthCtx.distinctMonthNameRank == pastafari.BigInt(66681), ...
    'Distinct month rank powinien wynosić 66681.');
assert(isequal(monthNames, expectedMonthDistinct), ...
    'Publikowane month names są błędne.');
assert(isequal(monthCtx.monthNameIndicesCandidate, expectedMonthDistinct), ...
    'Kontekst utracił distinct month candidate.');
assert(~hasRepeat(monthNames), ...
    'Publikowane month names muszą być różne.');

% 5. Pełny month-name katalog pozostaje reprezentowalny bez materializacji.
fullMonthCount = pastafari.partialPermutationNameRowCount( ...
    pastafari.BigInt(47), pastafari.BigInt(47));
M = pastafari.BigInt('170141183460469231731687303715884105727');
assert(fullMonthCount > M, ...
    '47! powinno wejść w wide-selection domain.');
firstFullRow = pastafari.partialPermutationNameRowUnrank( ...
    pastafari.BigInt(47), pastafari.BigInt(47), pastafari.BigInt(1));
assert(isequal(firstFullRow, 1:47), ...
    'Rank 1 dla 47P47 powinien być identity row.');

% 6. Trace/metrics: patch i raw scar są równocześnie obserwowalne.
assert(any(strcmp(cutletCtx.branchTrace, ...
    'DISCOVERY_22_REPEATED_NAMES')), ...
    'Brakuje raw Discovery 22 trace dla cutlets.');
assert(any(strcmp(cutletCtx.branchTrace, ...
    'PATCH_22_DISTINCT_NAME_DETOUR')), ...
    'Brakuje PATCH 22 trace dla cutlets.');

legacyKey = matlab.lang.makeValidName( ...
    'discovery22.repeatedNames.calls');
patchKey = matlab.lang.makeValidName( ...
    'patch22.distinctNameDetour.calls');
assert(isfield(cutletCtx.metrics, legacyKey) && ...
       cutletCtx.metrics.(legacyKey) == 1, ...
    'Raw repeated-name metric dla cutlets jest błędny.');
assert(isfield(cutletCtx.metrics, patchKey) && ...
       cutletCtx.metrics.(patchKey) == 1, ...
    'PATCH 22 metric dla cutlets jest błędny.');
assert(isfield(monthCtx.metrics, legacyKey) && ...
       monthCtx.metrics.(legacyKey) == 1, ...
    'Raw repeated-name metric dla months jest błędny.');
assert(isfield(monthCtx.metrics, patchKey) && ...
       monthCtx.metrics.(patchKey) == 1, ...
    'PATCH 22 metric dla months jest błędny.');

% 7. Fizyczny legacy generator pozostaje bez zmian.
legacyAgainCtx = pastafari.MonsterContext(0, 0);
legacyStream = struct( ...
    'first', pastafari.BigInt(61401), ...
    'directionStep', 1);
[legacyAgainCtx, legacyRank, legacyAgain, legacyCount, ~] = ...
    pastafari.LegacyRepeatedNameGenerator.callWithRing( ...
        legacyAgainCtx, legacyStream, ...
        pastafari.BigInt(17), pastafari.BigInt(6)); %#ok<ASGLU>
assert(legacyCount == pastafari.BigInt(24137569) && ...
       legacyRank == pastafari.BigInt(61401) && ...
       isequal(legacyAgain, expectedCutletRaw), ...
    'LegacyRepeatedNameGenerator został zmieniony przez PATCH 22.');

fprintf('STAGE_45_PATCH_22_GREEN\n');
end

function sauce = syntheticSauce()
sauce = struct( ...
    'bowls', {{ ...
        pastafari.BigInt(17), pastafari.BigInt(19), ...
        pastafari.BigInt(23), pastafari.BigInt(29), ...
        pastafari.BigInt(31), pastafari.BigInt(37)}}, ...
    'orderAt46Latch', [1 2 3 4 5 6]);
end

function rows = bruteDistinctRows(masterCount, k)
rows = [];
if k ~= 3
    error('Pastafari:Stage45:BruteFixture', ...
        'Ten mały brute oracle jest celowo zdefiniowany dla K=3.');
end

for a = 1:masterCount
    for b = 1:masterCount
        if b == a
            continue
        end
        for c = 1:masterCount
            if c == a || c == b
                continue
            end
            rows(end + 1, :) = [a b c]; %#ok<AGROW>
        end
    end
end
end

function tf = hasRepeat(indices)
tf = numel(unique(indices)) < numel(indices);
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'src'));
end
