function run_stage47_tests()
% PATCH 23: VirtualLegacyList ma exact count i 1-based lexicographic
% itemAt1 bez materializacji pełnej rodziny.

run_stage46_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

smallCases = [12 2; 15 3; 20 4];

for k = 1:size(smallCases, 1)
    total = smallCases(k, 1);
    months = smallCases(k, 2);

    [legacyWays, ~] = ...
        pastafari.LegacyAllMonthLengthWaysAPI.listAllWays( ...
            pastafari.BigInt(total), pastafari.BigInt(months));
    virtual = pastafari.VirtualLegacyList( ...
        pastafari.BigInt(total), pastafari.BigInt(months));

    assert(virtual.count() == pastafari.BigInt(numel(legacyWays)), ...
        'Virtual count różni się od concrete legacy count.');

    for r = 1:numel(legacyWays)
        actual = virtual.itemAt1(pastafari.BigInt(r));
        assert(isequal(actual, legacyWays{r}), ...
            ['Virtual itemAt1 utracił legacy order przy rank ', ...
             num2str(r), '.']);
    end
end

minimal = pastafari.VirtualLegacyList( ...
    pastafari.BigInt(12), pastafari.BigInt(2));
assert(minimal.count() == pastafari.BigInt(5), ...
    'Virtual 12/2 powinno mieć count 5.');
assert(isequal(minimal.itemAt1(pastafari.BigInt(1)), [4 8]), ...
    'Virtual rank 1 dla 12/2 powinien być [4 8].');
assert(isequal(minimal.itemAt1(pastafari.BigInt(5)), [8 4]), ...
    'Virtual rank 5 dla 12/2 powinien być [8 4].');

caughtZeroRank = false;
try
    minimal.itemAt1(pastafari.BigInt(0));
catch err
    caughtZeroRank = strcmp(err.identifier, ...
        'Pastafari:MonthLengths:VirtualRank');
end
assert(caughtZeroRank, 'Virtual itemAt1 musi odrzucać rank 0.');

hugeCases = { ...
    struct('total', 300, 'months', 10, ...
        'count', '16972992395495488'), ...
    struct('total', 400, 'months', 10, ...
        'count', '230112572610023588'), ...
    struct('total', 1000, 'months', 20, ...
        'count', ...
            '219529195724680298522930699726339455920')};

for k = 1:numel(hugeCases)
    c = hugeCases{k};
    virtual = pastafari.VirtualLegacyList( ...
        pastafari.BigInt(c.total), pastafari.BigInt(c.months));

    assert(virtual.count() == pastafari.BigInt(c.count), ...
        ['Production exact DP count jest błędny dla huge case ', ...
         num2str(k), '.']);

    firstRow = virtual.itemAt1(pastafari.BigInt(1));
    assert(numel(firstRow) == c.months, ...
        'Huge rank 1 ma błędną liczbę miesięcy.');
    assert(all(firstRow >= 4) && all(firstRow <= 123), ...
        'Huge rank 1 narusza bounds 4..123.');
    assert(sum(firstRow) == c.total, ...
        'Huge rank 1 ma błędną sumę.');
end

structureSauce = syntheticSauce();
ctx = pastafari.MonsterContext(0, 0);
[ctx, actual] = ...
    pastafari.MonthLengthCompatibilityRoute.call( ...
        ctx, structureSauce, pastafari.BigInt(300), ...
        pastafari.BigInt(10));

expectedRank = pastafari.BigInt(60447);
expectedRow = [4 4 4 4 4 4 15 68 114 79];

assert(ctx.legacyMonthLengthMaterializationAttempted, ...
    'PATCH 23 utracił legacy materialization attempt.');
assert(ctx.legacyMonthLengthMaterializationBlocked, ...
    'PATCH 23 musi zachować blocked legacy scar dla 300/10.');
assert(strcmp(ctx.legacyMonthLengthMaterializationError, ...
    'Pastafari:MonthLengths:LegacyMaterializationTooLarge'), ...
    'PATCH 23 zmienił legacy blocked error.');
assert(ctx.legacyMonthLengthLowerBound == ...
    pastafari.BigInt('10604499373'), ...
    'PATCH 23 zmienił legacy lower bound.');
assert(isempty(ctx.legacyMonthLengthConcreteWays), ...
    'Huge PATCH 23 route nie może materializować concrete ways.');
assert(isempty(ctx.legacyMonthLengthRank), ...
    'Blocked Stage 46 scar nie miał raw rank i tak ma pozostać.');

assert(ctx.monthLengthStreamFirst == expectedRank, ...
    'Bowl 3 / seal 31 synthetic witness powinien mieć first=60447.');
assert(ctx.generalSelectionCandidate == expectedRank, ...
    'Virtual family selection powinien wybrać rank 60447.');
assert(isequal(actual, expectedRow), ...
    'Virtual route 300/10 ma nieoczekiwany selected row.');
assert(isequal(ctx.monthLengthsCandidate, expectedRow), ...
    'Kontekst utracił virtual selected row.');
assert(all(actual >= 4) && all(actual <= 123) && sum(actual) == 300, ...
    'Virtual selected row narusza month-length invariants.');

virtual300 = pastafari.VirtualLegacyList( ...
    pastafari.BigInt(300), pastafari.BigInt(10));
assert(virtual300.count() == ...
    pastafari.BigInt('16972992395495488'), ...
    'Virtual 300/10 count jest błędny.');
assert(isequal(virtual300.itemAt1(expectedRank), expectedRow), ...
    'Direct VirtualLegacyList nie zgadza się z route witness.');

smallCtx = pastafari.MonsterContext(0, 0);
[smallCtx, smallActual] = ...
    pastafari.MonthLengthCompatibilityRoute.call( ...
        smallCtx, structureSauce, ...
        pastafari.BigInt(12), pastafari.BigInt(2));

assert(~smallCtx.legacyMonthLengthMaterializationBlocked, ...
    'Mały route nie powinien być blocked.');
assert(numel(smallCtx.legacyMonthLengthConcreteWays) == 5, ...
    'Mały route powinien zachować pięć concrete ways.');
assert(smallCtx.legacyMonthLengthRank == pastafari.BigInt(2), ...
    'Bowl 3 / seal 31 powinien wybrać raw rank 2 z rodziny 12/2.');
assert(isequal(smallActual, [5 7]), ...
    'Mały virtual route powinien zachować exact legacy result [5 7].');

assert(any(strcmp(ctx.branchTrace, ...
    'DISCOVERY_23_MATERIALIZED_MONTH_LENGTHS')), ...
    'Brakuje raw Discovery 23 trace.');
assert(any(strcmp(ctx.branchTrace, ...
    'PATCH_23_VIRTUAL_LEGACY_LIST')), ...
    'Brakuje PATCH 23 trace.');

legacyKey = matlab.lang.makeValidName( ...
    'discovery23.materializedMonthLengths.calls');
patchKey = matlab.lang.makeValidName( ...
    'patch23.virtualLegacyList.calls');

assert(isfield(ctx.metrics, legacyKey) && ...
       ctx.metrics.(legacyKey) == 1, ...
    'Raw Discovery 23 metric jest błędny.');
assert(isfield(ctx.metrics, patchKey) && ...
       ctx.metrics.(patchKey) == 1, ...
    'PATCH 23 metric jest błędny.');

caughtLegacy = false;
try
    pastafari.LegacyAllMonthLengthWaysAPI.listAllWays( ...
        pastafari.BigInt(300), pastafari.BigInt(10));
catch err
    caughtLegacy = strcmp(err.identifier, ...
        'Pastafari:MonthLengths:LegacyMaterializationTooLarge');
end
assert(caughtLegacy, ...
    'PATCH 23 nie może przekierować fizycznego legacy list_all_ways.');

fprintf('STAGE_47_PATCH_23_GREEN\n');
end

function sauce = syntheticSauce()
sauce = struct( ...
    'bowls', {{ ...
        pastafari.BigInt(17), pastafari.BigInt(19), ...
        pastafari.BigInt(23), pastafari.BigInt(29), ...
        pastafari.BigInt(31), pastafari.BigInt(37)}}, ...
    'orderAt46Latch', [1 2 3 4 5 6]);
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'src'));
end
