function run_stage39_tests()
% PATCH 19: guarded reuse z niezmienionym fizycznym key year.number.

% Niezmieniony regression Discovery 19 ma po PATCH 19 przejść na GREEN.
run_stage38_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
cleanup = onCleanup(@() cleanupPaths(root)); %#ok<NASGU>

% 1. Fingerprint mismatch: raw hit A ma pozostać widoczny, semantic=B.
pastafari.LegacyYearNumberStructureCache.clear();
year = makeYear(5000, 1000, 1400);
cDayA = pastafari.BigInt(111);
cDayB = pastafari.BigInt(222);

ctxA = pastafari.MonsterContext(cDayA, 0);
[ctxA, actualA] = ...
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxA, year, cDayA, @() structureValue('A', cDayA, year));
assert(strcmp(actualA.marker, 'A'), ...
    'Cold fill A jest błędny.');

ctxB = pastafari.MonsterContext(cDayB, 0);
[ctxB, actualB] = ...
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxB, year, cDayB, @() structureValue('B', cDayB, year));

assert(strcmp(actualB.marker, 'B'), ...
    'Fingerprint mismatch powinien recompute B.');
assert(ctxB.legacyYearCacheHit, ...
    'Raw historyczny hit musi pozostać widoczny.');
assert(ctxB.legacyYearCacheEntryCalculationDayFingerprint == cDayA, ...
    'Raw historyczny fingerprint A musi pozostać widoczny.');
assert(strcmp(ctxB.legacyYearCacheRawValue.marker, 'A'), ...
    'Raw stale value A musi pozostać widoczny.');
assert(~ctxB.legacyYearCacheProducerExecuted, ...
    ['Raw Stage 38 scar przy hit powinien nadal mówić, że legacy ', ...
     'nie uruchomiło producenta.']);

[afterB, hitAfterB, entryAfterB] = ...
    pastafari.LegacyYearNumberStructureCache.getRaw(year);
assert(hitAfterB && strcmp(afterB.marker, 'B'), ...
    'Po guard mismatch ten sam key powinien zostać nadpisany B.');
assert(entryAfterB.calculationDayFingerprint == cDayB, ...
    'Overwrite ma mieć nowy calculationDay fingerprint.');
assert(entryAfterB.openGate == year.openGateDay && ...
       entryAfterB.closeGate == year.closeGateDay, ...
    'Overwrite ma mieć bieżące gate days.');

% 2. Prawidłowy warm guarded hit nie może uruchomić producenta.
ctxWarm = pastafari.MonsterContext(cDayB, 0);
[ctxWarm, warmB] = ...
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxWarm, year, cDayB, @producerMustNotRun);

assert(strcmp(warmB.marker, 'B'), ...
    'Guarded warm hit powinien ponownie użyć B.');
assert(ctxWarm.legacyYearCacheHit, ...
    'Warm guarded hit powinien nadal być raw hit.');
assert(~ctxWarm.legacyYearCacheProducerExecuted, ...
    'Warm guarded hit nie może uruchamiać legacy producenta.');

% 3. Open-gate mismatch przy tym samym year.number i fingerprint.
pastafari.LegacyYearNumberStructureCache.clear();
baseYear = makeYear(6000, 2000, 2400);
openChangedYear = makeYear(6000, 1999, 2400);
cDay = pastafari.BigInt(333);

ctxBase = pastafari.MonsterContext(cDay, 0);
[ctxBase, ~] = pastafari.YearStructureCacheCompatibilityRoute.call( ...
    ctxBase, baseYear, cDay, ...
    @() structureValue('OPEN_BASE', cDay, baseYear));

ctxOpen = pastafari.MonsterContext(cDay, 0);
[ctxOpen, openValue] = ...
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxOpen, openChangedYear, cDay, ...
        @() structureValue('OPEN_NEW', cDay, openChangedYear));

assert(strcmp(openValue.marker, 'OPEN_NEW'), ...
    'Open-gate mismatch powinien wymusić recompute.');
assert(ctxOpen.legacyYearCacheHit, ...
    'Open-gate mismatch musi nadal widzieć raw year-number hit.');
assert(ctxOpen.legacyYearCacheEntryOpenGate == baseYear.openGateDay, ...
    'Raw scar powinien zachować stary open gate.');

% 4. Close-gate mismatch przy tym samym year.number i fingerprint.
pastafari.LegacyYearNumberStructureCache.clear();
closeBaseYear = makeYear(7000, 3000, 3400);
closeChangedYear = makeYear(7000, 3000, 3401);

ctxCloseBase = pastafari.MonsterContext(cDay, 0);
[ctxCloseBase, ~] = pastafari.YearStructureCacheCompatibilityRoute.call( ...
    ctxCloseBase, closeBaseYear, cDay, ...
    @() structureValue('CLOSE_BASE', cDay, closeBaseYear));

ctxClose = pastafari.MonsterContext(cDay, 0);
[ctxClose, closeValue] = ...
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxClose, closeChangedYear, cDay, ...
        @() structureValue('CLOSE_NEW', cDay, closeChangedYear));

assert(strcmp(closeValue.marker, 'CLOSE_NEW'), ...
    'Close-gate mismatch powinien wymusić recompute.');
assert(ctxClose.legacyYearCacheHit, ...
    'Close-gate mismatch musi nadal widzieć raw year-number hit.');
assert(ctxClose.legacyYearCacheEntryCloseGate == closeBaseYear.closeGateDay, ...
    'Raw scar powinien zachować stary close gate.');

% 5. Transactional overwrite: jeżeli producent zgłasza błąd,
% poprzedni entry nie może zostać usunięty ani nadpisany.
pastafari.LegacyYearNumberStructureCache.clear();
txnYear = makeYear(8000, 4000, 4400);
txnChanged = makeYear(8000, 4001, 4400);
txnDay = pastafari.BigInt(444);

ctxTxn = pastafari.MonsterContext(txnDay, 0);
[ctxTxn, ~] = pastafari.YearStructureCacheCompatibilityRoute.call( ...
    ctxTxn, txnYear, txnDay, ...
    @() structureValue('TXN_OLD', txnDay, txnYear));

caughtProducer = false;
try
    ctxFail = pastafari.MonsterContext(txnDay, 0);
    pastafari.YearStructureCacheCompatibilityRoute.call( ...
        ctxFail, txnChanged, txnDay, @failingProducer);
catch err
    caughtProducer = strcmp(err.identifier, ...
        'Pastafari:Stage39:ProducerFailure');
end
assert(caughtProducer, ...
    'Fixture powinien propagować błąd producenta.');

[afterFailure, hitAfterFailure, entryAfterFailure] = ...
    pastafari.LegacyYearNumberStructureCache.getRaw(txnYear);
assert(hitAfterFailure && strcmp(afterFailure.marker, 'TXN_OLD'), ...
    'Producer failure nie może usunąć starego entry.');
assert(entryAfterFailure.openGate == txnYear.openGateDay && ...
       entryAfterFailure.closeGate == txnYear.closeGateDay, ...
    'Producer failure nie może częściowo nadpisać guard fields.');

% 6. Fizyczny key pozostaje historycznie zły: samo year.number.
% Zmienione gates nadal powodują raw hit do starego entry przed guardem.
[~, rawStillHits, rawStillEntry] = ...
    pastafari.LegacyYearNumberStructureCache.getRaw(txnChanged);
assert(rawStillHits, ...
    'PATCH 19 nie może zmieniać fizycznego key cache.');
assert(rawStillEntry.openGate == txnYear.openGateDay, ...
    'Raw cache nadal powinien trafiać po samym year.number.');

% Trace/metric PATCH 19.
assert(any(strcmp(ctxB.branchTrace, ...
    'DISCOVERY_19_BAD_YEAR_CACHE_KEY')), ...
    'Brakuje śladu historycznego Discovery 19.');
assert(any(strcmp(ctxB.branchTrace, ...
    'PATCH_19_GUARDED_YEAR_CACHE')), ...
    'Brakuje śladu PATCH 19.');

legacyKey = matlab.lang.makeValidName( ...
    'discovery19.badYearCacheKey.calls');
patchKey = matlab.lang.makeValidName( ...
    'patch19.guardedYearCache.calls');
assert(isfield(ctxB.metrics, legacyKey) && ctxB.metrics.(legacyKey) == 1, ...
    'Licznik raw bad-year-cache-key jest niepoprawny.');
assert(isfield(ctxB.metrics, patchKey) && ctxB.metrics.(patchKey) == 1, ...
    'Licznik PATCH 19 jest niepoprawny.');

fprintf('STAGE_39_PATCH_19_GREEN\n');
end

function year = makeYear(number, openDay, closeDay)
year = struct( ...
    'number', pastafari.BigInt(number), ...
    'openGateDay', pastafari.BigInt(openDay), ...
    'closeGateDay', pastafari.BigInt(closeDay));
end

function value = structureValue(marker, cDay, year)
value = struct( ...
    'marker', marker, ...
    'calculationDay', pastafari.BigInt.coerce(cDay), ...
    'openGateDay', pastafari.BigInt.coerce(year.openGateDay), ...
    'closeGateDay', pastafari.BigInt.coerce(year.closeGateDay));
end

function value = producerMustNotRun()
error('Pastafari:Stage39:UnexpectedProducer', ...
    'Guarded warm hit nie powinien uruchamiać producenta.');
value = []; %#ok<NASGU>
end

function value = failingProducer()
error('Pastafari:Stage39:ProducerFailure', ...
    'Kontrolowany błąd producenta przed transactional overwrite.');
value = []; %#ok<NASGU>
end

function cleanupPaths(root)
pastafari.LegacyYearNumberStructureCache.clear();
rmpath(fullfile(root, 'src'));
end
