function run_stage13_tests()
% PATCH 06: logiczne sloty 0..-6 są mapowane na hidden 1..7.

% Niezmieniony regression Discovery 06 musi po PATCH 06 stać się zielony.
run_stage12_tests();

here = fileparts(mfilename('fullpath'));
root = fileparts(here);
addpath(fullfile(root, 'src'));
addpath(fullfile(here, 'oracle'));
cleanup = onCleanup(@() cleanupPaths(root, here)); %#ok<NASGU>

foundation = pastafari.BigInt('-15055671');
cases = { ...
    foundation, foundation; ...
    foundation - 3, foundation + 4; ...
    foundation + 12, foundation - 5};
labels = {'FOUNDATION_SAME', 'CROSS_FOUNDATION', 'BACKWARD_WIDE'};

for caseIndex = 1:size(cases, 1)
    c = cases{caseIndex, 1};
    t = cases{caseIndex, 2};

    counts = normative_oracle('workCounts', c, t);
    stones = normative_oracle('stones');
    hidden = referenceHiddenDrops(counts, stones);
    expected = referenceVisibleDrops(counts, stones, hidden);

    % Każdy z siedmiu historycznych slotów ma wskazywać dokładnie
    % odpowiadające mu hidden: 0->1, -1->2, ..., -6->7.
    for slot = 0:-1:-6
        hiddenIndex = 1 - slot;
        actualHidden = pastafari.PriorPatch.resolveMissing(slot, hidden);
        assert(actualHidden == hidden{hiddenIndex}, ...
            ['priorPatch błędnie mapuje slot ', num2str(slot), ...
             ' dla ', labels{caseIndex}, '.']);
    end

    % Sama historyczna funkcja nadal nie zna slotów nie-dodatnich.
    probe = {pastafari.BigInt(123)};
    [~, found0, slot0] = ...
        pastafari.LegacyPriorAdapter.legacyPrior(probe, 1, 1);
    [~, foundNeg6, slotNeg6] = ...
        pastafari.LegacyPriorAdapter.legacyPrior(probe, 1, 7);
    assert(~found0 && slot0 == 0, ...
        'PATCH 06 nie może modyfikować legacyPrior dla slotu 0.');
    assert(~foundNeg6 && slotNeg6 == -6, ...
        'PATCH 06 nie może modyfikować legacyPrior dla slotu -6.');

    ctx = pastafari.MonsterContext(c, t);
    [ctx, actual] = pastafari.VisibleDropCompatibilityRoute.call( ...
        ctx, counts, stones, hidden);

    % Publikowana ścieżka musi być zgodna z oracle dla wszystkich 46 kropli.
    for i = 1:46
        assert(actual{i} == expected{i}, ...
            ['PATCH 06 rozchodzi się z oracle dla ', ...
             labels{caseIndex}, ', drop ', num2str(i), '.']);
        assert(ctx.visibleDropsCandidate{i} == expected{i}, ...
            ['Kontekst nie zachował poprawionego drop ', num2str(i), ...
             ' dla ', labels{caseIndex}, '.']);
    end

    % Surowa historyczna ścieżka nadal musi zachowywać defekt w pierwszych
    % siedmiu kroplach, czyli patch jest detourem, a nie przepisywaniem historii.
    for i = 1:7
        assert(ctx.legacyVisibleDrops{i} ~= expected{i}, ...
            ['Historyczna blizna legacyPrior zniknęła dla ', ...
             labels{caseIndex}, ', drop ', num2str(i), '.']);
    end

    expectedMissing = logical([ ...
        1 1 1; ...
        0 1 1; ...
        0 1 1; ...
        0 0 1; ...
        0 0 1; ...
        0 0 1; ...
        0 0 1; ...
        0 0 0]);
    assert(isequal(ctx.legacyPriorMissingMatrix(1:8, :), expectedMissing), ...
        ['PATCH 06 zmienił historyczną macierz braków dla ', ...
         labels{caseIndex}, '.']);

    assert(any(strcmp(ctx.branchTrace, 'DISCOVERY_06_LEGACY_PRIOR')), ...
        'Brakuje śladu historycznego legacyPrior.');
    assert(any(strcmp(ctx.branchTrace, 'PATCH_06_PRIOR_PATCH')), ...
        'Brakuje śladu PATCH 06.');

    legacyKey = matlab.lang.makeValidName('discovery06.legacyPrior.calls');
    patchKey = matlab.lang.makeValidName('patch06.priorPatch.calls');
    assert(isfield(ctx.metrics, legacyKey) && ctx.metrics.(legacyKey) == 1, ...
        'Licznik legacyPrior jest niepoprawny.');
    assert(isfield(ctx.metrics, patchKey) && ctx.metrics.(patchKey) == 1, ...
        'Licznik priorPatch jest niepoprawny.');
end

fprintf('STAGE_13_PATCH_06_GREEN\n');
end

function hidden = referenceHiddenDrops(counts, stones)
coeff = [ ...
    3 4 6 8; ...
    5 7 10 12; ...
    7 10 14 16; ...
    9 13 18 20; ...
    11 16 22 24; ...
    13 19 26 28; ...
    15 22 30 32];
grindStone = [1 2 3 4 5 1 2];
hidden = cell(1, 7);

for k = 1:7
    row = coeff(k, :);
    x = counts.action + ...
        pastafari.BigInt(row(1)) * counts.target + ...
        pastafari.BigInt(row(2)) * counts.distance + ...
        pastafari.BigInt(row(3)) * counts.connection + ...
        pastafari.BigInt(row(4)) * pastafari.BigInt(counts.direction);

    for kind = 1:5
        x = x + stones{k, kind};
    end
    x = saveReference(x);

    for grind = 1:7
        oldX = x;
        x = saveReference( ...
            oldX.square() + pastafari.BigInt(3) * oldX + ...
            stones{k, grindStone(grind)} + pastafari.BigInt(grind));
    end
    hidden{k} = x;
end
end

function visible = referenceVisibleDrops(counts, stones, hidden)
timeline = cell(1, 53);
for k = 1:7
    timeline{8 - k} = hidden{k};
end

visible = cell(1, 46);
grinds = [ ...
    3 5 7 11 1; ...
    5 7 11 13 2; ...
    7 11 13 17 3; ...
    11 13 17 19 4; ...
    13 17 19 23 5; ...
    17 19 23 29 1; ...
    19 23 29 31 2; ...
    23 29 31 37 3; ...
    29 31 37 41 4; ...
    31 37 41 43 5; ...
    37 41 43 47 1];

for i = 1:46
    p1 = timeline{i + 6};
    p3 = timeline{i + 4};
    p7 = timeline{i};

    x = saveReference( ...
        stones{i, 1} * counts.action + ...
        stones{i, 2} * counts.target + ...
        stones{i, 3} * counts.distance + ...
        stones{i, 4} * counts.connection + ...
        stones{i, 5} * pastafari.BigInt(counts.direction) + ...
        p1 + pastafari.BigInt(3) * p3 + ...
        pastafari.BigInt(5) * p7 + pastafari.BigInt(i));

    for grind = 1:11
        oldX = x;
        row = grinds(grind, :);
        x = saveReference( ...
            oldX.square() + pastafari.BigInt(row(1)) * oldX + ...
            pastafari.BigInt(row(2)) * p1 + ...
            pastafari.BigInt(row(3)) * p3 + ...
            pastafari.BigInt(row(4)) * p7 + ...
            stones{i, row(5)});
    end

    visible{i} = x;
    timeline{i + 7} = x;
end
end

function value = saveReference(x)
M = pastafari.BigInt('170141183460469231731687303715884105727');
value = pastafari.BigInt(1) + ...
    (pastafari.BigInt.coerce(x) - pastafari.BigInt(1)).regularMod(M);
end

function cleanupPaths(root, here)
rmpath(fullfile(root, 'src'));
rmpath(fullfile(here, 'oracle'));
end
