// HISTORICAL FILENAME: this test formerly certified the incorrect raw-bowl-sum
// post-stir mutant.  It now certifies the canonical saved-sum semantics while
// retaining the path name so Stage 56 tooling/ABI need not be renamed.
#include "pastafari/monster.hpp"
#include "pastafari/source_language_catalog.hpp"
#include "reference/normative_reference.hpp"

#include <array>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>

using pastafari::BaseMetricsShell;
using pastafari::BaseMonsterContext;
using pastafari::BaseValidationManager;
using pastafari::BowlState;
using pastafari::FinalIntegrationHandler;
using pastafari::FinalStructureCacheEntry;
using pastafari::Integer;
using pastafari::PermutationOrder;
using pastafari::SpaghettiDateFive;
using pastafari::Stage56PostStirDetourWitness;
using pastafari::Stage56RawBowlSumSauceResult;
using pastafari::reference::SauceResult;

namespace {

void require(bool condition, const std::string& message) {
    if (!condition) throw std::runtime_error(message);
}

int cutletIndex(const std::string& text) {
    for (const auto& entry : pastafari::CUTLET_SOURCE_CATALOG) {
        if (entry.text == text) return static_cast<int>(entry.canonicalIndex);
    }
    return -1;
}

int monthIndex(const std::string& text) {
    for (const auto& entry : pastafari::MONTH_SOURCE_CATALOG) {
        if (entry.text == text) return static_cast<int>(entry.canonicalIndex);
    }
    return -1;
}

using CanonicalFive = std::tuple<Integer,int,Integer,int,Integer>;

CanonicalFive canonical(const SpaghettiDateFive& d) {
    return {d.yearNumber, cutletIndex(d.cutletName), d.dayInCutlet,
            monthIndex(d.monthName), d.dayInMonth};
}

BowlState independentCanonicalSavedSumPostStir(
    const BowlState& old,
    int stir,
    Integer& rawOut,
    Integer& savedOut,
    PermutationOrder& orderOut) {
    Integer raw = 0;
    for (const Integer& bowl : old) raw += bowl;
    const Integer saved = pastafari::savePatch(raw + 149 * stir);
    const int oneBased =
        (pastafari::regularMod(saved - 1, Integer{720}) + 1).convert_to<int>();
    const PermutationOrder order = pastafari::oldPermutationUnrank0(oneBased - 1);
    BowlState next = old;
    for (int position = 1; position <= 6; ++position) {
        const std::size_t pos = static_cast<std::size_t>(position - 1);
        const std::size_t prevPos = static_cast<std::size_t>((position + 4) % 6);
        const std::size_t nextPos = static_cast<std::size_t>(position % 6);
        const int id = order[pos];
        const int prev = order[prevPos];
        const int following = order[nextPos];
        const Integer u = old[static_cast<std::size_t>(id - 1)]
                        + 3 * old[static_cast<std::size_t>(prev - 1)]
                        + 5 * old[static_cast<std::size_t>(following - 1)]
                        + saved
                        + stir
                        + position * position;
        next[static_cast<std::size_t>(id - 1)] = pastafari::savePatch(
            u * u
            + 7 * old[static_cast<std::size_t>(prev - 1)]
                * old[static_cast<std::size_t>(following - 1)]);
    }
    rawOut = raw;
    savedOut = saved;
    orderOut = order;
    return next;
}

BowlState independentRawSumMutantPostStir(
    const BowlState& old,
    int stir) {
    Integer raw = 0;
    for (const Integer& bowl : old) raw += bowl;
    const Integer saved = pastafari::savePatch(raw + 149 * stir);
    const int oneBased =
        (pastafari::regularMod(saved - 1, Integer{720}) + 1).convert_to<int>();
    const PermutationOrder order = pastafari::oldPermutationUnrank0(oneBased - 1);
    BowlState next = old;
    for (int position = 1; position <= 6; ++position) {
        const std::size_t pos = static_cast<std::size_t>(position - 1);
        const std::size_t prevPos = static_cast<std::size_t>((position + 4) % 6);
        const std::size_t nextPos = static_cast<std::size_t>(position % 6);
        const int id = order[pos];
        const int prev = order[prevPos];
        const int following = order[nextPos];
        const Integer u = old[static_cast<std::size_t>(id - 1)]
                        + 3 * old[static_cast<std::size_t>(prev - 1)]
                        + 5 * old[static_cast<std::size_t>(following - 1)]
                        + raw
                        + stir
                        + position * position;
        next[static_cast<std::size_t>(id - 1)] = pastafari::savePatch(
            u * u
            + 7 * old[static_cast<std::size_t>(prev - 1)]
                * old[static_cast<std::size_t>(following - 1)]);
    }
    return next;
}

void requireReferenceCommitWitnessConstants(
    const Integer&,
    const Integer&,
    const Stage56RawBowlSumSauceResult&) {
    // Intentional no-op.  The prior constants in this historical test file were
    // generated by the now-superseded raw-sum mutant and therefore must not be
    // accepted as canonical evidence.  The comparison below is against the
    // independent saved-sum normative reference instead.
}

void requireSauceAgainstIndependentOracle(const Integer& c, const Integer& t) {
    const Stage56RawBowlSumSauceResult prod =
        pastafari::sauceWithStage56RawBowlSumDetour(c, t);
    requireReferenceCommitWitnessConstants(c, t, prod);
    const SauceResult ref = pastafari::reference::sauce(c, t);
    for (std::size_t i = 0; i < 6; ++i) {
        require(prod.semanticSauce.finalBowls[i] == ref.bowls[i],
                "Gradus 56 final bowls contra oracle localem discrepant");
        require(prod.semanticSauce.orderAt46Latch[i] == ref.orderAtDrop46[i],
                "Gradus 56 drop-46 order contra oracle localem discrepat");
    }
    require(prod.legacyScarCallCount == 12,
            "cicatrix legacy post-commotionis non exacte duodecies cucurrit");
    require(prod.appliedCount == 12 && prod.applied,
            "via compatibilitatis saved-sum non exacte duodecies applicata est");

    const auto counts = pastafari::reference::workCounts(c, t);
    const auto stones = pastafari::reference::buildStones();
    const auto hidden = pastafari::reference::buildHiddenDrops(counts, stones);
    const auto visible = pastafari::reference::buildVisibleDrops(counts, stones, hidden);
    auto afterDrops = pastafari::reference::applyVisibleDropsToBowls(
        pastafari::reference::initialBowls(counts), visible, stones);
    BowlState expected{};
    for (std::size_t i = 0; i < 6; ++i) expected[i] = afterDrops.first[i];

    for (int stir = 1; stir <= 12; ++stir) {
        Integer raw{};
        Integer saved{};
        PermutationOrder order{};
        expected = independentCanonicalSavedSumPostStir(expected, stir, raw, saved, order);
        const Stage56PostStirDetourWitness& witness =
            prod.stirWitnesses.at(static_cast<std::size_t>(stir - 1));
        require(witness.stirIndex == stir && witness.applied,
                "index vel applied flag testis post-commotionis invalidus est");
        require(witness.rawBowlSum == raw && witness.savedOrderNumber == saved,
                "raw bowl sum vel saved order number contra computationem independentem discrepat");
        require(witness.correctedOrder == order && witness.legacyOrder == order,
                "guard permutationis Gradus 56 discrepat");
        require(witness.correctedResult == expected,
                "una ex duodecim post-commotionibus contra formulam saved-sum independentem discrepat");
        require(witness.oldResult == witness.correctedResult,
                "cicatrix ABI Gradus 56 non debet mutantem raw-sum in productione retinere");
    }
}

void requireStaticScar() {
    std::ifstream in("src/monster.cpp");
    require(static_cast<bool>(in), "src/monster.cpp ad audit staticum aperiri non potest");
    std::ostringstream buffer;
    buffer << in.rdbuf();
    const std::string source = buffer.str();
    const std::string beginToken =
        "Patch11LatchedOrderSauceResult sauceWithOrderAt46Latch(";
    const std::string endToken =
        "Patch11LatchedOrderSauceResult sauceWithScars(";
    const std::size_t begin = source.find(beginToken);
    const std::size_t end = source.find(endToken, begin);
    require(begin != std::string::npos && end != std::string::npos && end > begin,
            "cicatrix sauceWithOrderAt46Latch physice non inventa est");
    const std::string scar = source.substr(begin, end - begin);
    require(scar.find("savedBowlSum = savePatch(savedBowlSum + 149 * stir);") != std::string::npos,
            "formula orderNumber legacy physice deleta est");
    require(scar.find("+ savedBowlSum") != std::string::npos,
            "operandum savedOrderNumber legacy intra u physice deleta est");
}

void runCorrectedContext(BaseMonsterContext& ctx,
                         const Integer& c,
                         const Integer& t,
                         std::map<Integer, FinalStructureCacheEntry>& cache) {
    ctx.calculationDay = c;
    ctx.targetDay = t;
    ctx.phase = "ENTRY";
    ctx.status = "NEW";
    ctx.mode = "AUTHORITATIVE_SPAGHETTI_GRADUS_56_PROBA";
    ctx.retryBudget = 3;
    ctx.stage56CorrectiveRequested = true;
    const FinalIntegrationHandler handler;
    const BaseValidationManager validator;
    const BaseMetricsShell metrics;
    handler.handle(ctx, cache, validator, metrics);
}

void requireContextOwnership() {
    BaseMonsterContext a;
    BaseMonsterContext b;
    std::map<Integer, FinalStructureCacheEntry> cacheA;
    std::map<Integer, FinalStructureCacheEntry> cacheB;
    const Integer f = pastafari::FOUNDATION_DAY_OLD;
    runCorrectedContext(a, f, f, cacheA);
    const auto aOld = a.stage56PostStirOldResult;
    const auto aCorrected = a.stage56PostStirCorrectedResult;
    const Integer aRaw = a.stage56RawBowlSum;
    const Integer aSaved = a.stage56SavedOrderNumber;
    const int aStir = a.stage56StirIndex;
    const std::size_t aCount = a.stage56AppliedCount;

    runCorrectedContext(b, Integer{-15048173}, Integer{-15048173}, cacheB);
    require(a.stage56PostStirOldResult == aOld &&
            a.stage56PostStirCorrectedResult == aCorrected &&
            a.stage56RawBowlSum == aRaw &&
            a.stage56SavedOrderNumber == aSaved &&
            a.stage56StirIndex == aStir &&
            a.stage56AppliedCount == aCount,
            "contextus secundus statum Gradus 56 contextus primi contaminavit");
    require(a.stage56AppliedFlag && b.stage56AppliedFlag &&
            a.stage56LegacyScarCallCount == 12 && b.stage56LegacyScarCallCount == 12 &&
            a.stage56AppliedCount == 12 && b.stage56AppliedCount == 12,
            "status Gradus 56 inter contextus non proprie possessus est");
    require(a.stage56PostStirCorrectedResult != b.stage56PostStirCorrectedResult,
            "duo contextus discriminantes statum eundem casu retinuerunt");
}

void requireExternalWitnessesAndNearFoundation() {
    // Keep the core test compact: the dedicated E2E worker exercises the full
    // saved-sum witness table.  Here one absolute public-API witness makes sure
    // the corrected sauce reaches the five-field result.
    const SpaghettiDateFive foundation = pastafari::calendarDateSpaghetti(
        pastafari::FOUNDATION_DAY_OLD, pastafari::FOUNDATION_DAY_OLD);
    const CanonicalFive expectedFoundation{
        Integer{5000}, 10, Integer{503}, 20, Integer{56}
    };
    require(canonical(foundation) == expectedFoundation,
            "Foundation absolute saved-sum witness discrepat");
}

} // namespace

int main() {
    try {
        std::cerr << "GRADUS56_FASE=DISCRIMINATOR\n";
        const BowlState discriminator{{Integer{1},Integer{2},Integer{3},Integer{4},Integer{5},Integer{6}}};
        const Stage56PostStirDetourWitness d =
            pastafari::stage56RawBowlSumPostStirDetour(discriminator, 1);
        require(d.rawBowlSum != d.savedOrderNumber,
                "discriminator rawBowlSum != SAVE(rawBowlSum+149*stir) non distinxit");
        require(d.oldResult == d.correctedResult,
                "productione Stage56 mutantem raw-sum adhuc retinet");
        Integer raw{};
        Integer saved{};
        PermutationOrder order{};
        const BowlState independent = independentCanonicalSavedSumPostStir(
            discriminator, 1, raw, saved, order);
        const BowlState mutant = independentRawSumMutantPostStir(discriminator, 1);
        require(independent != mutant,
                "discriminator canonicalem saved-sum a mutante raw-sum non distinxit");
        require(d.correctedResult == independent && d.correctedResult != mutant &&
                d.rawBowlSum == raw && d.savedOrderNumber == saved &&
                d.correctedOrder == order && d.legacyOrder == order,
                "via productionis discriminatoris non est formula canonica saved-sum");

        std::cerr << "GRADUS56_FASE=SAUCE_FOUNDATION\n";
        requireSauceAgainstIndependentOracle(
            pastafari::FOUNDATION_DAY_OLD,
            pastafari::FOUNDATION_DAY_OLD);
        std::cerr << "GRADUS56_FASE=SAUCE_WITNESS\n";
        requireSauceAgainstIndependentOracle(
            Integer{-15048173},
            Integer{-15048173});
        std::cerr << "GRADUS56_FASE=STATIC\n";
        requireStaticScar();
        std::cerr << "GRADUS56_FASE=CONTEXTS\n";
        requireContextOwnership();
        std::cerr << "GRADUS56_FASE=E2E_SAVED_SUM\n";
        requireExternalWitnessesAndNearFoundation();
        std::cerr << "GRADUS56_FASE=FINIS\n";

        std::cout
            << "GRADUS_56_CORRECTIO_CANONICA_SAVED_SUM_TRANSIIT: discriminator saved-sum/raw-mutant, cicatrix ABI 12/12, "
               "saved-sum 12/12, oracle C++ localis et duo contextus probati sunt; "
               "E2E processibus separatis exercetur\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "GRADUS_56_CORRECTIO_CANONICA_SAVED_SUM_DEFECIT: " << error.what() << "\n";
        return 1;
    }
}
