#include "pastafari/monster.hpp"
#include "reference/normative_reference.hpp"
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>
using pastafari::BaseMonsterManager; using pastafari::Integer; using pastafari::LegacyYearAnchor; using pastafari::reference::NormativeOracle; using pastafari::reference::Year;
static void require(bool c,const std::string& m){if(!c) throw std::runtime_error(m);}
int main(){try{NormativeOracle oracle; const Integer c0=pastafari::reference::FOUNDATION_DAY; const Year y5000=oracle.year5000(c0); const Year y5001=oracle.nextYear(c0,y5000); const LegacyYearAnchor anchor{y5000.number,y5000.openGateDay+1,y5000.closeGateDay}; const Integer targetDay=y5001.openGateDay+1; BaseMonsterManager manager; manager.clearLegacyYearNumberCacheDiagnostic(); const auto primum=manager.executeLegacyYearNumberCache(anchor,targetDay,c0); require(primum.ready&&!primum.cacheHit,"prima invocatio cache anni MISS esse debet"); require(primum.cacheKeyYearNumber==5001,"clavis witness anni non est 5001"); require(primum.cachedEntry.calculationDayFingerprint==c0&&primum.cachedEntry.openGate==primum.requestEntry.openGate&&primum.cachedEntry.closeGate==primum.requestEntry.closeGate,"value cache legacy campos guardiae non servat"); const std::vector<Integer> days{c0+1,c0+2,c0+3}; int discrepantiae=0; for(const Integer& c:days){const auto r=manager.executeLegacyYearNumberCache(anchor,targetDay,c); require(r.ready,"invocatio cache anni parata esse debet"); require(r.cacheKeyYearNumber==5001,"year.number witness mutatus est"); require(r.requestEntry.calculationDayFingerprint==c,"fingerprint request falsus est"); if(r.cacheHit) require(r.cachedEntry.calculationDayFingerprint==c0,"HIT legacy entry primam servare debet"); const bool stale=r.outputValue.openGateDay!=r.requestEntry.value.openGateDay||r.outputValue.closeGateDay!=r.requestEntry.value.closeGateDay; if(stale){++discrepantiae; std::cout<<"DISCREPANTIA_CACHE_ANNI cDay="<<c<<" key="<<r.cacheKeyYearNumber<<" fingerprint_servatus="<<r.cachedEntry.calculationDayFingerprint<<" fingerprint_request="<<r.requestEntry.calculationDayFingerprint<<" close_servatus="<<r.outputValue.closeGateDay<<" close_request="<<r.requestEntry.value.closeGateDay<<"\n";}}
if(discrepantiae==0){std::cout<<"REGRESSIO_DISCOVERY_19_TRANSIIT\n";return 0;} if(discrepantiae==3){std::cout<<"REGRESSIO_DISCOVERY_19_DEFECIT: 3 HIT stale ex clave year.number sola inventa sunt\n";return 1;} std::cerr<<"REGRESSIO_DISCOVERY_19_ERROR: discrepantiae inexpectatae="<<discrepantiae<<"\n";return 2;}catch(const std::exception& e){std::cerr<<"REGRESSIO_DISCOVERY_19_ERROR: "<<e.what()<<"\n";return 3;}}
