classdef GateQuestionEngine
    % Wspólna, semantycznie neutralna maszyna pytania o długość przerwy bramy.
    % Otrzymuje już konkretny target day; sama nie interpretuje znaku indeksu.
    methods (Static)
        function gap = gapForQuestionDay(questionDay)
            pastafari.ValidationManager.requireExactIntegerInput(questionDay);

            foundation = pastafari.BigInt('-15055671');
            target = pastafari.BigInt.coerce(questionDay);
            inner = pastafari.MonsterContext(foundation, target);

            [inner, counts] = pastafari.WorkCountsCompatibilityRoute.call( ...
                inner, foundation, target);
            [inner, stones] = pastafari.StoneTableCompatibilityRoute.call(inner);
            [inner, hidden] = pastafari.HiddenCompatibilityRoute.call( ...
                inner, counts, stones);
            [inner, priorVisible] = ...
                pastafari.VisibleDropCompatibilityRoute.call( ...
                    inner, counts, stones, hidden);
            [inner, visible] = pastafari.GrindTableCompatibilityRoute.call( ...
                inner, counts, stones, hidden, priorVisible);
            [inner, preInPlaceBowls] = ...
                pastafari.BowlPourCompatibilityRoute.call( ...
                    inner, counts, stones, visible);
            [inner, bowlsAfterDrop46] = ...
                pastafari.BowlStirCompatibilityRoute.call( ...
                    inner, counts, stones, visible, preInPlaceBowls);
            [inner, finalBowls, orderAt46] = ...
                pastafari.OrderAt46CompatibilityRoute.call( ...
                    inner, visible, bowlsAfterDrop46);

            queriedBowlId = 1;
            nextBowlId = pastafari.LatchedSuccessorPatch.apply( ...
                orderAt46, queriedBowlId);
            stream = pastafari.AnswerRingStreamFactory.fromSauce( ...
                finalBowls, queriedBowlId, nextBowlId, 1);

            [inner, chosen] = ...
                pastafari.GeneralSelectionCompatibilityRoute.call( ...
                    inner, stream, pastafari.BigInt(922)); %#ok<ASGLU>

            gap = pastafari.BigInt(41) + chosen;
        end
    end
end
