classdef LegacyAllMonthLengthWaysAPI
    % Historyczne API Discovery 23: konkretna lista wszystkich długości.
    methods (Static)
        function cap = safeCap()
            cap = pastafari.BigInt(100000);
        end

        function descriptor = probeAllWays(totalDays, monthCount)
            proof = pastafari.proveLegacyMonthLengthFamilyLowerBound( ...
                totalDays, monthCount);
            cap = pastafari.LegacyAllMonthLengthWaysAPI.safeCap();

            descriptor = struct( ...
                'familyName', 'ALL_WAYS_CONCRETE_ARRAY', ...
                'totalDays', pastafari.BigInt.coerce(totalDays), ...
                'monthCount', pastafari.BigInt.coerce(monthCount), ...
                'minLength', pastafari.BigInt(4), ...
                'maxLength', pastafari.BigInt(123), ...
                'safeCap', cap, ...
                'lowerBoundProof', proof, ...
                'preflightTooLarge', proof.lowerBound > cap);
        end

        function [ways, descriptor] = listAllWays(totalDays, monthCount)
            descriptor = ...
                pastafari.LegacyAllMonthLengthWaysAPI.probeAllWays( ...
                    totalDays, monthCount);

            [ways, proof] = pastafari.legacyMaterializeMonthLengthWays( ...
                totalDays, monthCount, descriptor.safeCap);

            descriptor.lowerBoundProof = proof;
            descriptor.concreteCount = pastafari.BigInt(numel(ways));
        end
    end
end
