classdef LegacyGrindTableAdapter
    % Historyczna, celowo przesunięta tablica 11 mielenia.
    % Legacy wylicza fizyczny indeks jako grindNumber+1. Bez wiersza
    % sentinel pod logicznym indeksem 0 pierwsze mielenie pobiera wiersz 2.
    methods (Static)
        function rows = rowsWithoutSentinel()
            rows = [ ...
                3 5 7 11 1; ...
                5 7 11 13 2; ...
                7 11 13 17 3; ...
                11 13 17 19 4; ...
                13 17 19 23 5; ...
                17 19 23 29 1; ...
                19 23 29 31 2; ...
                23 29 31 37 3; ...
                29 31 37 41 4; ...
                31 37 41 43 5; ...
                37 41 43 47 1];
        end

        function [row, requestedIndex, resolvedIndex] = ...
                rowForGrind(rows, grindNumber)
            if ~isnumeric(rows) || size(rows, 2) ~= 5 || isempty(rows)
                error('Pastafari:GrindTable:Shape', ...
                    'Tabela mielenia musi być niepustą macierzą Nx5.');
            end
            if ~(isnumeric(grindNumber) && isscalar(grindNumber) && ...
                    isfinite(grindNumber) && fix(grindNumber) == grindNumber && ...
                    grindNumber >= 1 && grindNumber <= 11)
                error('Pastafari:GrindTable:Index', ...
                    'Numer mielenia musi należeć do zakresu 1..11.');
            end

            requestedIndex = grindNumber + 1;
            resolvedIndex = min(requestedIndex, size(rows, 1));
            row = rows(resolvedIndex, :);
        end
    end
end
