function result = sauceWithCurrentScars(calculationDay, targetDay)
% Zbuduj pełny sauce używając aktualnie naprawionych warstw produkcyjnych.
% Funkcja jest neutralna wobec roli targetDay: wylicza dokładnie Sauce(c,t).

pastafari.ValidationManager.requireExactIntegerInput(calculationDay);
pastafari.ValidationManager.requireExactIntegerInput(targetDay);

cDay = pastafari.BigInt.coerce(calculationDay);
tDay = pastafari.BigInt.coerce(targetDay);
inner = pastafari.MonsterContext(cDay, tDay);

[inner, counts] = pastafari.WorkCountsCompatibilityRoute.call( ...
    inner, cDay, tDay);
[inner, stones] = pastafari.StoneTableCompatibilityRoute.call(inner);
[inner, hidden] = pastafari.HiddenCompatibilityRoute.call( ...
    inner, counts, stones);
[inner, priorVisible] = ...
    pastafari.VisibleDropCompatibilityRoute.call( ...
        inner, counts, stones, hidden);
[inner, visible] = ...
    pastafari.GrindTableCompatibilityRoute.call( ...
        inner, counts, stones, hidden, priorVisible);
[inner, preInPlaceBowls] = ...
    pastafari.BowlPourCompatibilityRoute.call( ...
        inner, counts, stones, visible);
[inner, bowlsAfterDrop46] = ...
    pastafari.BowlStirCompatibilityRoute.call( ...
        inner, counts, stones, visible, preInPlaceBowls);
[inner, finalBowls, orderAt46] = ...
    pastafari.OrderAt46CompatibilityRoute.call( ...
        inner, visible, bowlsAfterDrop46); %#ok<ASGLU>

result = struct( ...
    'calculationDay', cDay, ...
    'targetDay', tDay, ...
    'bowls', {finalBowls}, ...
    'orderAt46Latch', orderAt46, ...
    'bowl2', finalBowls{2});
end
