function catalog = sourceLanguageCatalog()
% Zwraca zamrożony katalog źródłowy nazw w języku polskim.
% Kolejność normatywna wynika wyłącznie z canonicalIndex.

persistent frozenCatalog
if isempty(frozenCatalog)
    cutletText = { ...
        'brąz', ...
        'lis', ...
        'nerka', ...
        'Lagasz', ...
        'myśl', ...
        'cztery części z dziewięciu', ...
        'Palgurasz', ...
        'papirus', ...
        'kiść', ...
        'skorpion', ...
        'popiół', ...
        'pszenica', ...
        'rzeka', ...
        'śmiech', ...
        'Akad', ...
        'róg', ...
        'pusty dzban'};

    monthText = { ...
        'glina', ...
        'granat', ...
        'łokieć', ...
        'zazdrość', ...
        'Eridu', ...
        'pasta do zębów', ...
        'trzy części z pięciu', ...
        'Karszumb', ...
        'tygrys', ...
        'cyna', ...
        'mgła', ...
        'kadzidło', ...
        'wrzeciono', ...
        'żebro', ...
        'karob', ...
        'Uruk', ...
        'wstyd', ...
        'wielbłąd', ...
        'miedź', ...
        'studnia', ...
        'żółtko', ...
        'gwiazda', ...
        'miód', ...
        'śledziona', ...
        'wapień', ...
        'radość', ...
        'figa', ...
        'Niniwa', ...
        'żaba', ...
        'smoła', ...
        'świeca', ...
        'zamknięte drzwi', ...
        'sezam', ...
        'kark', ...
        'srebro', ...
        'Suza', ...
        'burza', ...
        'osioł', ...
        'mąka', ...
        'żal', ...
        'Babilon', ...
        'język', ...
        'len', ...
        'sól', ...
        'gruszka', ...
        'łuk', ...
        'piasek'};

    frozenCatalog = struct();
    frozenCatalog.version = '1.0.0';
    frozenCatalog.language = 'pl';
    frozenCatalog.orderRule = 'canonicalIndex';
    frozenCatalog.cutlets = makeRows(cutletText);
    frozenCatalog.months = makeRows(monthText);
end

% MATLAB stosuje semantykę kopiowania przy zapisie dla struktur, więc zwrócona
% kopia może zostać zmieniona przez wywołującego bez modyfikacji katalogu trwałego.
catalog = frozenCatalog;
end

function rows = makeRows(texts)
rows = repmat(struct('canonicalIndex', 0, 'text', ''), 1, numel(texts));
for k = 1:numel(texts)
    rows(k).canonicalIndex = k;
    rows(k).text = texts{k};
end
end
