function result = calendarDateSpaghetti(calculationDay, targetDay)
% Szkielet produkcyjny rozbudowany do etapu 34; aktywne są PATCH 01-16
% oraz Discovery 17.

pastafari.ValidationManager.requireExactIntegerInput(calculationDay);
pastafari.ValidationManager.requireExactIntegerInput(targetDay);
ctx = pastafari.MonsterContext(calculationDay, targetDay);
ctx.metrics = pastafari.MetricsShell.bump(ctx.metrics, 'calendar.bootstrap.calls');
ctx = pastafari.MonsterDispatcher.dispatch(ctx, @bootstrapHandler);

[ctx, ~] = pastafari.SaveCompatibilityRoute.call(ctx, calculationDay); %#ok<ASGLU>
[ctx, counts] = pastafari.WorkCountsCompatibilityRoute.call( ...
    ctx, calculationDay, targetDay);
[ctx, stones] = pastafari.StoneTableCompatibilityRoute.call(ctx);
[ctx, hidden] = pastafari.HiddenCompatibilityRoute.call( ...
    ctx, counts, stones);
[ctx, priorVisible] = pastafari.VisibleDropCompatibilityRoute.call( ...
    ctx, counts, stones, hidden);
[ctx, visible] = pastafari.GrindTableCompatibilityRoute.call( ...
    ctx, counts, stones, hidden, priorVisible);

[ctx, ~] = pastafari.PermutationCompatibilityRoute.call( ...
    ctx, visible{1}); %#ok<ASGLU>

[ctx, preInPlaceBowls] = pastafari.BowlPourCompatibilityRoute.call( ...
    ctx, counts, stones, visible);

[ctx, bowlsAfterDrop46] = pastafari.BowlStirCompatibilityRoute.call( ...
    ctx, counts, stones, visible, preInPlaceBowls);

[ctx, finalBowls, orderAt46] = ...
    pastafari.OrderAt46CompatibilityRoute.call( ...
        ctx, visible, bowlsAfterDrop46);

queriedBowlId = orderAt46(4);
[ctx, ~] = pastafari.NextBowlCompatibilityRoute.call( ...
    ctx, orderAt46, queriedBowlId); %#ok<ASGLU>

selectionBowlId = 1;
selectionNextId = ...
    pastafari.LatchedSuccessorPatch.apply(orderAt46, selectionBowlId);
stream = pastafari.AnswerRingStreamFactory.fromSauce( ...
    finalBowls, selectionBowlId, selectionNextId, 1);

[ctx, ~] = pastafari.SmallPickCompatibilityRoute.call( ...
    ctx, stream, pastafari.BigInt(922)); %#ok<ASGLU>

M = pastafari.BigInt('170141183460469231731687303715884105727');
[ctx, ~] = pastafari.GeneralSelectionCompatibilityRoute.call( ...
    ctx, stream, M + pastafari.BigInt(1)); %#ok<ASGLU>

[ctx, ~] = pastafari.GateGapCompatibilityRoute.call( ...
    ctx, pastafari.BigInt(-1)); %#ok<ASGLU>

% PATCH 16 pozostaje aktywny przed sortowaniem Year 5000.
year5000Probe = { ...
    yearCandidate(1, 30, 3000, 400), ...
    yearCandidate(2, 50, 5000, 300), ...
    yearCandidate(3, 10, 1000, 400), ...
    yearCandidate(4, 20, 2000, 300), ...
    yearCandidate(5, 25, 2500, 400), ...
    yearCandidate(6, 1, 100, 500)};
[ctx, filteredYear5000Probe] = ...
    pastafari.YearCandidateCompatibilityRoute.call( ...
        ctx, year5000Probe);
[ctx, ~] = pastafari.Year5000OrderingCompatibilityRoute.call( ...
    ctx, filteredYear5000Probe); %#ok<ASGLU>

error('Pastafari:Bootstrap:NotImplementedYet', ...
    ['Etap 34 aktywuje historyczną ścieżkę Discovery 17; ', ...
     'pełna semantyka kalendarza nie jest jeszcze zaimplementowana.']);

    function inner = bootstrapHandler(inner)
        inner.phase = 'BOOTSTRAP_READY';
        inner.status = 'SKELETON_ONLY';
        inner.diagnostics{end + 1} = ...
            'Neutralny szkielet rozruchowy pozostaje aktywny pod historycznymi warstwami.';
    end

    function candidate = yearCandidate(id, openIndex, openDay, lengthDays)
        candidate = struct( ...
            'id', id, ...
            'openGateIndex', pastafari.BigInt(openIndex), ...
            'closeGateIndex', pastafari.BigInt(openIndex + 6), ...
            'openGateDay', pastafari.BigInt(openDay), ...
            'closeGateDay', pastafari.BigInt(openDay + lengthDays));
    end
end
