function result = calendarDateSpaghetti(calculationDay, targetDay)
% Szkielet produkcyjny rozbudowany do etapu 42; aktywne są PATCH 01-20
% oraz Discovery 21.

pastafari.ValidationManager.requireExactIntegerInput(calculationDay);
pastafari.ValidationManager.requireExactIntegerInput(targetDay);
ctx = pastafari.MonsterContext(calculationDay, targetDay);
ctx.metrics = pastafari.MetricsShell.bump(ctx.metrics, 'calendar.bootstrap.calls');
ctx = pastafari.MonsterDispatcher.dispatch(ctx, @bootstrapHandler);

[ctx, ~] = pastafari.SaveCompatibilityRoute.call(ctx, calculationDay); %#ok<ASGLU>
[ctx, counts] = pastafari.WorkCountsCompatibilityRoute.call( ...
    ctx, calculationDay, targetDay);
[ctx, stones] = pastafari.StoneTableCompatibilityRoute.call(ctx);
[ctx, hidden] = pastafari.HiddenCompatibilityRoute.call( ...
    ctx, counts, stones);
[ctx, priorVisible] = pastafari.VisibleDropCompatibilityRoute.call( ...
    ctx, counts, stones, hidden);
[ctx, visible] = pastafari.GrindTableCompatibilityRoute.call( ...
    ctx, counts, stones, hidden, priorVisible);

[ctx, ~] = pastafari.PermutationCompatibilityRoute.call( ...
    ctx, visible{1}); %#ok<ASGLU>

[ctx, preInPlaceBowls] = pastafari.BowlPourCompatibilityRoute.call( ...
    ctx, counts, stones, visible);

[ctx, bowlsAfterDrop46] = pastafari.BowlStirCompatibilityRoute.call( ...
    ctx, counts, stones, visible, preInPlaceBowls);

[ctx, finalBowls, orderAt46] = ...
    pastafari.OrderAt46CompatibilityRoute.call( ...
        ctx, visible, bowlsAfterDrop46);

queriedBowlId = orderAt46(4);
[ctx, ~] = pastafari.NextBowlCompatibilityRoute.call( ...
    ctx, orderAt46, queriedBowlId); %#ok<ASGLU>

selectionBowlId = 1;
selectionNextId = ...
    pastafari.LatchedSuccessorPatch.apply(orderAt46, selectionBowlId);
stream = pastafari.AnswerRingStreamFactory.fromSauce( ...
    finalBowls, selectionBowlId, selectionNextId, 1);

[ctx, ~] = pastafari.SmallPickCompatibilityRoute.call( ...
    ctx, stream, pastafari.BigInt(922)); %#ok<ASGLU>

M = pastafari.BigInt('170141183460469231731687303715884105727');
[ctx, ~] = pastafari.GeneralSelectionCompatibilityRoute.call( ...
    ctx, stream, M + pastafari.BigInt(1)); %#ok<ASGLU>

[ctx, ~] = pastafari.GateGapCompatibilityRoute.call( ...
    ctx, pastafari.BigInt(-1)); %#ok<ASGLU>

year5000Probe = { ...
    yearCandidate(1, 30, 3000, 400), ...
    yearCandidate(2, 50, 5000, 300), ...
    yearCandidate(3, 10, 1000, 400), ...
    yearCandidate(4, 20, 2000, 300), ...
    yearCandidate(5, 25, 2500, 400), ...
    yearCandidate(6, 1, 100, 500)};
[ctx, filteredYear5000Probe] = ...
    pastafari.YearCandidateCompatibilityRoute.call( ...
        ctx, year5000Probe);
[ctx, ~] = pastafari.Year5000OrderingCompatibilityRoute.call( ...
    ctx, filteredYear5000Probe); %#ok<ASGLU>

% Discovery 18: kontrolowany łańcuch lat pokazuje drift po /365.
yearWalkProbe = probeYearChain();
anchorYear = yearWalkProbe{5}; % numer 5000
[ctx, ~] = pastafari.TargetYearCompatibilityRoute.call( ...
    ctx, anchorYear, pastafari.BigInt(1500), yearWalkProbe); %#ok<ASGLU>

% Discovery 19: pierwszy structure-cache lookup keyed tylko przez year number.
cacheProbeYear = struct( ...
    'number', pastafari.BigInt(5000), ...
    'openGateDay', pastafari.BigInt(0), ...
    'closeGateDay', pastafari.BigInt(365));
[ctx, ~] = pastafari.YearStructureCacheCompatibilityRoute.call( ...
    ctx, cacheProbeYear, calculationDay, ...
    @() cacheProbeValue(calculationDay, cacheProbeYear)); %#ok<ASGLU>

% Discovery 20: structure sauce nadal używa oryginalnego target day.
structureYearProbe = struct( ...
    'number', pastafari.BigInt(5000), ...
    'openGateDay', pastafari.BigInt(calculationDay) + pastafari.BigInt(9), ...
    'closeGateDay', pastafari.BigInt(calculationDay) + pastafari.BigInt(409));
[ctx, ~] = pastafari.StructureSauceCompatibilityRoute.call( ...
    ctx, calculationDay, targetDay, structureYearProbe); %#ok<ASGLU>

% Discovery 21: pełna rodzina dodatnich kompozycji ignoruje gate wewnętrzny.
cutletPartitionProbeStream = struct( ...
    'first', pastafari.BigInt(87), ...
    'directionStep', 1);
[ctx, ~] = pastafari.CutletPartitionCompatibilityRoute.call( ...
    ctx, cutletPartitionProbeStream, ...
    pastafari.BigInt(10), pastafari.BigInt(8), ...
    pastafari.BigInt(4)); %#ok<ASGLU>

error('Pastafari:Bootstrap:NotImplementedYet', ...
    ['Etap 42 aktywuje historyczną ścieżkę Discovery 21; ', ...
     'pełna semantyka kalendarza nie jest jeszcze zaimplementowana.']);

    function inner = bootstrapHandler(inner)
        inner.phase = 'BOOTSTRAP_READY';
        inner.status = 'SKELETON_ONLY';
        inner.diagnostics{end + 1} = ...
            'Neutralny szkielet rozruchowy pozostaje aktywny pod historycznymi warstwami.';
    end

    function candidate = yearCandidate(id, openIndex, openDay, lengthDays)
        candidate = struct( ...
            'id', id, ...
            'openGateIndex', pastafari.BigInt(openIndex), ...
            'closeGateIndex', pastafari.BigInt(openIndex + 6), ...
            'openGateDay', pastafari.BigInt(openDay), ...
            'closeGateDay', pastafari.BigInt(openDay + lengthDays));
    end

    function years = probeYearChain()
        years = { ...
            probeYear(4996, -1930, -1565), ...
            probeYear(4997, -1565, -965), ...
            probeYear(4998, -965, -365), ...
            probeYear(4999, -365, 0), ...
            probeYear(5000, 0, 365), ...
            probeYear(5001, 365, 730), ...
            probeYear(5002, 730, 1330), ...
            probeYear(5003, 1330, 1930), ...
            probeYear(5004, 1930, 2295)};
    end

    function year = probeYear(number, openDay, closeDay)
        year = struct( ...
            'number', pastafari.BigInt(number), ...
            'openGateDay', pastafari.BigInt(openDay), ...
            'closeGateDay', pastafari.BigInt(closeDay));
    end

    function value = cacheProbeValue(cDay, year)
        value = struct( ...
            'kind', 'STAGE38_STRUCTURE_PROBE', ...
            'calculationDay', pastafari.BigInt.coerce(cDay), ...
            'openGateDay', pastafari.BigInt.coerce(year.openGateDay), ...
            'closeGateDay', pastafari.BigInt.coerce(year.closeGateDay));
    end
end
