;; Faste normative konstanter for kalenderkernen.

(define M (- (expt 2 127) 1))
(define TABLETS-DAY -278522)
(define FOUNDATION-DAY -15055671)

(define GATE-GAP-MIN 42)
(define GATE-GAP-MAX 963)
(define YEAR-MIN-DAYS 252)
(define YEAR-MAX-DAYS 5778)
(define MIN-GATE-GAPS-PER-YEAR 6)
(define MIN-CUTLETS 6)
(define MAX-CUTLETS 17)
(define MIN-MONTHS 3)
(define MAX-MONTHS 47)
(define MIN-MONTH-DAYS 4)
(define MAX-MONTH-DAYS 123)

(define SEAL-GATE-GAP 1)
(define SEAL-YEAR-5000 10)
(define SEAL-NEXT-YEAR 11)
(define SEAL-PREVIOUS-YEAR 12)
(define SEAL-CUTLET-COUNT 20)
(define SEAL-CUTLET-PARTITION 21)
(define SEAL-CUTLET-NAMES 22)
(define SEAL-MONTH-COUNT 30)
(define SEAL-MONTH-LENGTHS 31)
(define SEAL-MONTH-WEAVING 32)
(define SEAL-MONTH-NAMES 33)

(define WHEAT 1)
(define BARLEY 2)
(define SALT 3)
(define BITTER 4)
(define RED 5)
