(defpackage #:pastafari.lv
  (:use #:cl)
  (:export
   #:*source-language-catalog-version*
   #:cutlet-name-by-index
   #:month-name-by-index
   #:all-cutlet-entries
   #:all-month-entries
   #:catalog-entry-canonical-index
   #:catalog-entry-text
   #:catalog-entry-origin-class
   #:make-monster-context
   #:monster-context-calculation-day
   #:monster-context-target-day
   #:monster-context-phase
   #:monster-context-status
   #:monster-context-semantic-state
   #:monster-context-observability-state
   #:make-base-dispatcher
   #:dispatcher-register
   #:dispatcher-dispatch
   #:make-validation-manager
   #:validation-require
   #:make-error-wrapper
   #:wrapped-monster-error
   #:make-metrics-shell
   #:metrics-bump
   #:metrics-read
   #:make-log-shell
   #:log-record
   #:log-entries
   #:calendar-date-spaghetti))

(defpackage #:pastafari.lv.oracle
  (:use #:cl)
  (:export
   #:m
   #:tablets-day
   #:foundation-day
   #:regular-mod
   #:save
   #:day-count
   #:work-counts
   #:work-counts-action
   #:work-counts-target
   #:work-counts-distance
   #:work-counts-connection
   #:work-counts-direction
   #:build-stones
   #:build-hidden-drops
   #:build-visible-drops
   #:initial-bowls
   #:apply-visible-drops-to-bowls
   #:post-stir-12
   #:sauce
   #:make-answer-stream
   #:answer-stream-first
   #:answer-stream-direction-step
   #:ask-bowl
   #:answer-at
   #:choose-rank-short
   #:choose-rank-wide
   #:choose-rank
   #:permutation-unrank-1
   #:bowl-order-from-drop
   #:falling-factorial
   #:unrank-distinct-indices
   #:make-bounded-composition-counter
   #:bounded-composition-count
   #:bounded-composition-unrank1
   #:make-cutlet-partition-counter
   #:cutlet-partition-count
   #:cutlet-partition-unrank1
   #:make-weaving-counter
   #:weaving-count
   #:weaving-unrank1
   #:calendar-date-indices
   #:calendar-date))

(defpackage #:pastafari.lv.tests
  (:use #:cl)
  (:import-from #:pastafari.lv
                #:*source-language-catalog-version*
                #:cutlet-name-by-index
                #:month-name-by-index
                #:all-cutlet-entries
                #:all-month-entries
                #:catalog-entry-canonical-index
                #:catalog-entry-text
                #:make-monster-context
                #:monster-context-calculation-day
                #:monster-context-target-day
                #:monster-context-semantic-state
                #:monster-context-observability-state
                #:make-base-dispatcher
                #:dispatcher-register
                #:dispatcher-dispatch
                #:make-validation-manager
                #:validation-require
                #:make-metrics-shell
                #:metrics-bump
                #:metrics-read
                #:make-log-shell
                #:log-record
                #:log-entries)
  (:import-from #:pastafari.lv.oracle
                #:m
                #:foundation-day
                #:regular-mod
                #:save
                #:day-count
                #:work-counts
                #:work-counts-action
                #:work-counts-target
                #:work-counts-distance
                #:work-counts-connection
                #:work-counts-direction
                #:build-stones
                #:make-answer-stream
                #:choose-rank-short
                #:choose-rank-wide
                #:permutation-unrank-1
                #:bowl-order-from-drop
                #:falling-factorial
                #:unrank-distinct-indices
                #:make-bounded-composition-counter
                #:bounded-composition-count
                #:bounded-composition-unrank1
                #:make-cutlet-partition-counter
                #:cutlet-partition-count
                #:cutlet-partition-unrank1
                #:make-weaving-counter
                #:weaving-count
                #:weaving-unrank1)
  (:export #:run-stage-01-tests))
