NB. Catalogul de limbă-sursă română este înghețat în Stage 1.
NB. Ordinea semantică este dată numai de indicii canonici.

SOURCE_LANGUAGE_CATALOG_VERSION=: '1'
SOURCE_LANGUAGE=: 'română'

CUTLET_CANONICAL_INDEX=: 1 + i. 17
MONTH_CANONICAL_INDEX=: 1 + i. 47

CUTLET_NAMES_RO=: 0$a:
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'bronz'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'vulpe'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'rinichi'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'Lagaș'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'gând'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'patru părți din nouă'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'Palguraș'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'papirus'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'ciorchine'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'scorpion'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'cenușă'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'grâu'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'râu'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'râs'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'Akkad'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'corn'
CUTLET_NAMES_RO=: CUTLET_NAMES_RO, <'ulciorul gol'

MONTH_NAMES_RO=: 0$a:
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'lut'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'rodie'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'cot'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'invidie'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'Eridu'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'pastă de dinți'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'trei părți din cinci'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'Karșumab'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'leopard'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'staniu'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'ceață'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'tămâie'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'fus'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'coastă'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'roșcovă'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'Uruk'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'rușine'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'cămilă'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'cupru'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'fântână'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'gălbenuș'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'stea'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'miere'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'splină'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'calcar'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'bucurie'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'smochină'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'Ninive'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'broască'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'smoală'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'lumânare'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'ușa închisă'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'susan'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'ceafă'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'argint'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'crin'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'furtună'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'măgar'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'făină'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'regret'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'Babilon'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'limbă'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'in'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'sare'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'pară'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'arc'
MONTH_NAMES_RO=: MONTH_NAMES_RO, <'nisip'

cutletNameFromCanonicalIndex=: 3 : 0
  assert. (y >: 1) *. y <: 17
  > (y - 1) { CUTLET_NAMES_RO
)

monthNameFromCanonicalIndex=: 3 : 0
  assert. (y >: 1) *. y <: 47
  > (y - 1) { MONTH_NAMES_RO
)

validateSourceLanguageCatalog=: 3 : 0
  assert. 17 = # CUTLET_NAMES_RO
  assert. 47 = # MONTH_NAMES_RO
  assert. CUTLET_CANONICAL_INDEX -: 1 + i. 17
  assert. MONTH_CANONICAL_INDEX -: 1 + i. 47
  assert. 17 = # ~. CUTLET_NAMES_RO
  assert. 47 = # ~. MONTH_NAMES_RO
  1
)
