(in-package #:pastafari.lv)

(defparameter *source-language-catalog-version* "lv-1.0.0")

(defstruct (catalog-entry (:constructor make-catalog-entry (canonical-index text origin-class)))
  canonical-index
  text
  origin-class)

(defparameter *cutlet-catalog*
  (vector
   (make-catalog-entry 1 "bronza" :semantic)
   (make-catalog-entry 2 "lapsa" :semantic)
   (make-catalog-entry 3 "niere" :semantic)
   (make-catalog-entry 4 "Lagaša" :place)
   (make-catalog-entry 5 "doma" :semantic)
   (make-catalog-entry 6 "četras devītdaļas" :semantic)
   (make-catalog-entry 7 "Palguraš" :invented)
   (make-catalog-entry 8 "meldrs" :semantic)
   (make-catalog-entry 9 "ķekars" :semantic)
   (make-catalog-entry 10 "skorpions" :semantic)
   (make-catalog-entry 11 "pelni" :semantic)
   (make-catalog-entry 12 "kvieši" :semantic)
   (make-catalog-entry 13 "upe" :semantic)
   (make-catalog-entry 14 "smiekli" :semantic)
   (make-catalog-entry 15 "Akada" :place)
   (make-catalog-entry 16 "rags" :semantic)
   (make-catalog-entry 17 "tukšā krūka" :semantic)))

(defparameter *month-catalog*
  (vector
   (make-catalog-entry 1 "māls" :semantic)
   (make-catalog-entry 2 "granātābols" :semantic)
   (make-catalog-entry 3 "elkonis" :semantic)
   (make-catalog-entry 4 "skaudība" :semantic)
   (make-catalog-entry 5 "Eridu" :place)
   (make-catalog-entry 6 "zobu pasta" :semantic)
   (make-catalog-entry 7 "trīs piektdaļas" :semantic)
   (make-catalog-entry 8 "Karšumab" :invented)
   (make-catalog-entry 9 "leopards" :semantic)
   (make-catalog-entry 10 "alva" :semantic)
   (make-catalog-entry 11 "migla" :semantic)
   (make-catalog-entry 12 "vīraks" :semantic)
   (make-catalog-entry 13 "vārpsta" :semantic)
   (make-catalog-entry 14 "riba" :semantic)
   (make-catalog-entry 15 "ceratonija" :semantic)
   (make-catalog-entry 16 "Uruka" :place)
   (make-catalog-entry 17 "kauns" :semantic)
   (make-catalog-entry 18 "kamielis" :semantic)
   (make-catalog-entry 19 "varš" :semantic)
   (make-catalog-entry 20 "aka" :semantic)
   (make-catalog-entry 21 "olas dzeltenums" :semantic)
   (make-catalog-entry 22 "zvaigzne" :semantic)
   (make-catalog-entry 23 "medus" :semantic)
   (make-catalog-entry 24 "liesa" :semantic)
   (make-catalog-entry 25 "kaļķakmens" :semantic)
   (make-catalog-entry 26 "prieks" :semantic)
   (make-catalog-entry 27 "vīģe" :semantic)
   (make-catalog-entry 28 "Nīnive" :place)
   (make-catalog-entry 29 "varde" :semantic)
   (make-catalog-entry 30 "darva" :semantic)
   (make-catalog-entry 31 "svece" :semantic)
   (make-catalog-entry 32 "aizvērtās durvis" :semantic)
   (make-catalog-entry 33 "sezams" :semantic)
   (make-catalog-entry 34 "pakausis" :semantic)
   (make-catalog-entry 35 "sudrabs" :semantic)
   (make-catalog-entry 36 "lilija" :semantic)
   (make-catalog-entry 37 "vētra" :semantic)
   (make-catalog-entry 38 "ēzelis" :semantic)
   (make-catalog-entry 39 "milti" :semantic)
   (make-catalog-entry 40 "nožēla" :semantic)
   (make-catalog-entry 41 "Babilona" :place)
   (make-catalog-entry 42 "mēle" :semantic)
   (make-catalog-entry 43 "lini" :semantic)
   (make-catalog-entry 44 "sāls" :semantic)
   (make-catalog-entry 45 "bumbieris" :semantic)
   (make-catalog-entry 46 "loks" :semantic)
   (make-catalog-entry 47 "smiltis" :semantic)))

(defun all-cutlet-entries ()
  (copy-seq *cutlet-catalog*))

(defun all-month-entries ()
  (copy-seq *month-catalog*))

(defun catalog-text-at (catalog index)
  (unless (and (integerp index) (<= 1 index (length catalog)))
    (error "Kanoniskais indekss ir ārpus kataloga robežām: ~S" index))
  (let ((entry (aref catalog (1- index))))
    (unless (= index (catalog-entry-canonical-index entry))
      (error "Kataloga kanoniskā indeksa invariants ir pārkāpts pie ~S" index))
    (catalog-entry-text entry)))

(defun cutlet-name-by-index (index)
  (catalog-text-at *cutlet-catalog* index))

(defun month-name-by-index (index)
  (catalog-text-at *month-catalog* index))
