#include "pastafari/http_api/strict_json.hpp"
#include <charconv>
#include <cctype>
#include <cstdio>
#include <sstream>
namespace pastafari::http_api::json {
namespace {
class Parser{std::string_view s;std::size_t p=0;[[noreturn]]void fail(const char*m){throw Error(m,p);}void ws(){while(p<s.size()&&(s[p]==' '||s[p]=='\t'||s[p]=='\n'||s[p]=='\r'))++p;}bool take(char c){ws();if(p<s.size()&&s[p]==c){++p;return true;}return false;}
 std::string str(){ws();if(p>=s.size()||s[p]!='"')fail("catena exspectatur");++p;std::string o;while(p<s.size()){unsigned char c=s[p++];if(c=='"')return o;if(c<0x20)fail("character moderans in catena vetatur");if(c!='\\'){o.push_back((char)c);continue;}if(p>=s.size())fail("sequentia effugiens imperfecta est");char e=s[p++];switch(e){case'"':o.push_back('"');break;case'\\':o.push_back('\\');break;case'/':o.push_back('/');break;case'b':o.push_back('\b');break;case'f':o.push_back('\f');break;case'n':o.push_back('\n');break;case'r':o.push_back('\r');break;case't':o.push_back('\t');break;case'u':{if(p+4>s.size())fail("sequentia Unicode nimis brevis est");unsigned cp=0;for(int i=0;i<4;i++){char h=s[p++];cp<<=4;if(h>='0'&&h<='9')cp+=h-'0';else if(h>='a'&&h<='f')cp+=h-'a'+10;else if(h>='A'&&h<='F')cp+=h-'A'+10;else fail("sequentia Unicode invalida est");}if(cp>=0xD800&&cp<=0xDFFF)fail("surrogatum Unicode non accipitur; UTF-8 directe mitte");if(cp<0x80)o.push_back((char)cp);else if(cp<0x800){o.push_back((char)(0xC0|(cp>>6)));o.push_back((char)(0x80|(cp&63)));}else{o.push_back((char)(0xE0|(cp>>12)));o.push_back((char)(0x80|((cp>>6)&63)));o.push_back((char)(0x80|(cp&63)));}break;}default:fail("sequentia effugiens invalida est");}}fail("catena non terminata est");}
 Value number(){ws();std::size_t b=p;if(p<s.size()&&s[p]=='-')++p;if(p>=s.size())fail("numerus invalidus est");if(s[p]=='0')++p;else{if(!std::isdigit((unsigned char)s[p]))fail("numerus invalidus est");while(p<s.size()&&std::isdigit((unsigned char)s[p]))++p;}if(p<s.size()&&s[p]=='.'){++p;if(p>=s.size()||!std::isdigit((unsigned char)s[p]))fail("fractio invalida est");while(p<s.size()&&std::isdigit((unsigned char)s[p]))++p;}if(p<s.size()&&(s[p]=='e'||s[p]=='E')){++p;if(p<s.size()&&(s[p]=='+'||s[p]=='-'))++p;if(p>=s.size()||!std::isdigit((unsigned char)s[p]))fail("exponens invalidus est");while(p<s.size()&&std::isdigit((unsigned char)s[p]))++p;}return Value{Number{std::string(s.substr(b,p-b))}};}
 Value value(){ws();if(p>=s.size())fail("valor exspectatur");char c=s[p];if(c=='"')return Value{str()};if(c=='{'){++p;Object o;ws();if(take('}'))return Value{o};for(;;){std::string k=str();if(!take(':'))fail("colon exspectatur");if(o.contains(k))fail("clavis objecti duplicata est");o.emplace(std::move(k),value());if(take('}'))break;if(!take(','))fail("comma exspectatur");}return Value{o};}if(c=='['){++p;Array a;ws();if(take(']'))return Value{a};for(;;){a.push_back(value());if(take(']'))break;if(!take(','))fail("comma exspectatur");}return Value{a};}if(s.substr(p,4)=="true"){p+=4;return Value{true};}if(s.substr(p,5)=="false"){p+=5;return Value{false};}if(s.substr(p,4)=="null"){p+=4;return Value{nullptr};}if(c=='-'||std::isdigit((unsigned char)c))return number();fail("token inopinatum est");}
public:explicit Parser(std::string_view x):s(x){}Value run(){Value v=value();ws();if(p!=s.size())fail("data superflua post valorem sunt");return v;}};
void write(const Value&v,std::string&o){if(std::holds_alternative<std::nullptr_t>(v.data)){o+="null";return;}if(auto b=std::get_if<bool>(&v.data)){o+=*b?"true":"false";return;}if(auto n=std::get_if<Number>(&v.data)){o+=n->lexeme;return;}if(auto s=std::get_if<std::string>(&v.data)){o+=escape(*s);return;}if(auto a=std::get_if<Array>(&v.data)){o+='[';bool f=true;for(auto&x:*a){if(!f)o+=',';f=false;write(x,o);}o+=']';return;}auto&o2=std::get<Object>(v.data);o+='{';bool f=true;for(auto&[k,x]:o2){if(!f)o+=',';f=false;o+=escape(k);o+=':';write(x,o);}o+='}';}
}
Value parse(std::string_view t){return Parser(t).run();}
std::string escape(std::string_view s){std::string o="\"";for(unsigned char c:s){switch(c){case'"':o+="\\\"";break;case'\\':o+="\\\\";break;case'\b':o+="\\b";break;case'\f':o+="\\f";break;case'\n':o+="\\n";break;case'\r':o+="\\r";break;case'\t':o+="\\t";break;default:if(c<0x20){char b[7];std::snprintf(b,sizeof b,"\\u%04x",c);o+=b;}else o.push_back((char)c);}}o+='"';return o;}
std::string stringify(const Value&v){std::string o;write(v,o);return o;}
const Value* member(const Object&o,std::string_view k){auto i=o.find(k);return i==o.end()?nullptr:&i->second;}
} // namespace pastafari::http_api::json
